- codility_training/lessons.lesson04.CountingElements.MissingInteger/README.md
- codility_training/lessons.lesson04.CountingElements.MissingInteger/eyabc.js
> lessons.lesson04.CountingElements.MissingInteger

- codility_training/lessons.lesson02.Arrays.CyclicRotation/khw970421.js
> create new khw970421.js

- codility_training/lessons.lesson01.Iterations.BinaryGap/pul8219.java
알고리즘 풀이 파일 pul8219.java 작성하였습니다. pr 요청합니다!
> PR 요청 lessons.lesson01.Iterations.BinaryGap

- codility_training/lessons.lesson04.CountingElements.MaxCounters/JeongShin.js
- codility_training/lessons.lesson04.CountingElements.MissingInteger/JeongShin.js
Max_Counter 문제에 대한 풀이가 performance 측정 77프로를 넘지 못해서 
@JunilHwang 님의 코드를 공부하고 다시 작성 해보았습니다. 
[codelink]: https://github.com/JeongShin/Algorithm/blob/master/codility_training/lessons.lesson04.CountingElements.MaxCounters/JeongShin.js
> 일일 pr 요청 합니다 

- programmers/난이도별/level01.K번째수/README.md
- programmers/난이도별/level01.K번째수/dkdlelk99.py
> 0501 일일 커밋 PR

- codility_training/lessons.lesson04.CountingElements.MissingInteger/junilhwang.js
> Codility - Lessons04.ConutingElements - MissingInteger 풀이 완료

- codility_training/lessons.lesson03.TimeComplexity.PermMissingElem/README.md
- codility_training/lessons.lesson03.TimeComplexity.PermMissingElem/junilhwang.js
- codility_training/lessons.lesson03.TimeComplexity.TapeEquilibrium/junilhwang.js
@eyabc 
@khw970421 
@JeongShin 
참고하시게
> PermMissingElem, TapeEquilibrium 해결 완료

- codility_training/lessons.lessons05.PrefixSums.MinAvgTwoSlice/README.md
- codility_training/lessons.lessons05.PrefixSums.MinAvgTwoSlice/eyabc.js
Reverts DKU-STUDY/Algorithm#68
> lessons.lessons05.PrefixSums.MinAvgTwoSlice

- programmers/난이도별/level01.문자열_내_p와_y의_개수/README.md
- programmers/난이도별/level01.문자열_내_p와_y의_개수/dkdlelk99.py
- programmers/난이도별/level01.문자열_다루기_기본/README.md
- programmers/난이도별/level01.문자열_다루기_기본/dkdlelk99.py
- programmers/난이도별/level01.약수의_합/README.md
- programmers/난이도별/level01.약수의_합/dkdlelk99.py
변수 잘못써놓고 한참 해맸네요.
쉬운 코드임에도 본인이 잘못한건 본인이 찾기 힘들다는걸 다시금 알게됨..
> 0505 일일 커밋

- codility_training/lessons.lesson02.Arrays.OddOccurrencesInArray/pul8219.java
PR요청합니다. 반복문으로 배열 요소 하나하나 접근하는 식으로 알고리즘 작성하다가
잘 풀리지 않아 솔루션을 참고했습니다.
자바 컬렉션 공부가 잘 안되어있어서 자료형을 떠올리는게 어렵네요 ㅠㅠ 더더더더 열심히 해야겠어요
> Add pul8219.java file.(OddOccurrencesInArray)

- codility_training/lessons.lesson01.Iterations.BinaryGap/sAp00n.py
- codility_training/lessons.lesson07.StacksandQueues.Brackets/sAp00n.py
- codility_training/lessons.lessons08.Leader.EquiLeader/sAp00n.py
review 받은부분 수정하고, leader 문제 좀 더 풀어봤는데 아직 정답은 아니네요..
추가로 stack 이용하는 예제 풀이 하나 더 커밋합니다.
> 05.14 daily commit

- programmers/난이도별/level01.정수_내림차순으로_배치하기/README.md
- programmers/난이도별/level01.정수_내림차순으로_배치하기/dkdlelk99.py
한번에 풀리는 프로그래머스 level01단계는 오늘까지일듯 합니다!
내일부터는 남겨둔 어려운 level 1 문제들을 풀게될거같아요
> 0517 일일커밋입니다

- programmers/난이도별/level01.시저_암호/README.md
- programmers/난이도별/level01.시저_암호/dkdlelk99.py
1. 딕셔너리로 도전 (실패)
2. 문자열에서 replace 함수 써보려다가 리스트 인덱스 문제로 실패
3. 커밋한 내용
갈길이 멉니다.
> 0518 일일커밋입니다

- codility_training/lessons.lesson07.StacksandQueues.Nesting/sjjyy.java
> lessons.lesson07.StackandQueues.Nesting

- codility_training/lessons.lesson07.StacksandQueues.Fish/sAp00n.py
- codility_training/lessons.lesson09.MaximumSliceProblem.MaxSliceSum/README.md
- codility_training/lessons.lesson09.MaximumSliceProblem.MaxSliceSum/sAp00n.py
어제 실수로 그냥 머지해버려서 어제자 내용도 써놓을께요.
05.18 월----
dominator 코드 수정했습니다.
equileader 배열 인덱싱 부분에서 n의 시간 소모하는걸 반복문 외부로 돌려서 총 시간복잡도를 O(n)으로 수정했습니다.
05.19 화----
fish 예제 재귀적 구현에서 반복문 구현으로 수정했습니다.
maxslicesum 문제풀이와 readme.md 추가했습니다.
> sAp00n 2020.05.19 daily PR

- programmers/난이도별/level.01하샤드_수/README.md
- programmers/난이도별/level.01하샤드_수/dkdlelk99.py
- programmers/난이도별/level01.정수_제곱근_판별/README.md
- programmers/난이도별/level01.정수_제곱근_판별/dkdlelk99.py
- programmers/난이도별/level01.콜라츠_추측/README.md
- programmers/난이도별/level01.콜라츠_추측/dkdlelk99.py
하샤드 수 파일 이름이 level01.하샤드_수 여야되는데 점 위치가 잘못찍혀있습니다 ㅠㅠ
제 개발환경에서 긁어서 직접 알고리즘 레포에 복붙하는 방식으로 항상 커밋해서
어떻게 고치는지를 아직도 모르겠네요...
링크 띄워주신 인프런 git강의 빨리 봐야겠네요
> 0522 일일 커밋입니다.

- programmers/난이도별/level02.탑/README.md
- programmers/난이도별/level02.탑/dkdlelk99.py
아직 푸는중입니다... 다 된줄 알았는데 test 2,4,6 정확도에서 fail..
lv2는 역시 1과는 다르군요.
갈 길이 멉니다!
> 0526 일일 커밋입니다

- codility_training/lessons.lesson10.PrimeAndCompositeNumbers.Flags/Flag.md
- codility_training/lessons.lesson10.PrimeAndCompositeNumbers.Flags/sAp00n.py
- codility_training/lessons.lesson10.PrimeAndCompositeNumbers.MinPerimeterRectangle/sAp00n.py
Flag 풀이 완료했습니다.
md파일 참고해서 풀이했어요.
Minperimeter도 풀이 완료했습니다.
> 05.27 daliyPR

- codility_training/lessons.lesson10.PrimeAndCompositeNumbers.Peaks/sAp00n.py
생각치 않은 예외처리하는데 자꾸 애먹네요.
그냥 별 생각 없이 짯는데 복잡도가 O(N*log(log(n)))나와서 종료했습니다.
> sAp00n 05.28 dailyPR

- codility_training/lessons.lesson11.SieveofEratosthenes.CountNonDivisible/README.md
- codility_training/lessons.lesson11.SieveofEratosthenes.CountNonDivisible/sAp00n.py
README.md 추가.
CountNonDivisible 풀이
> sAp00n 0529 daily PR

- codility_training/lessons.lesson10.PrimeAndCompositeNumbers.CountFactors/sjjyy.java
> lessons.lesson10.PrimeAndCompositeNumbers.CountFactors

- codility_training/lessons.lesson11.SieveofEratosthenes.CountSemiprimes/sAp00n.py
정확도 100% 달성했습니다.
시간 최적화를 위해 자료구조 를 BST를 써야하나 고민중이에요...
> sAp00n 06.02 dailyPR

- programmers/난이도별/level02.위장/README.md
- programmers/난이도별/level02.위장/dkdlelk99.py
문제를 풀다가 2시간이 훌쩍 넘어서 답을 찾아보았습니다..
1. 기초수학이 중요한 이유 => (i+1)을 곱할 생각을 못했음
2. 딕셔너리 사용의 편리성
```딕셔너리이름[key] =  value``` 를 해주는것만으로 딕셔너리에 요소추가 가능
두가지를 배웠습니다!
> 0602 일일 커밋입니다.

- programmers/난이도별/level02.프린터/README.md
- programmers/난이도별/level02.프린터/dkdlelk99.py
124나라 풀다가 어려워서 이 문제를 풀어봤는데 시간초과로 실패했습니다.
반복문을 줄이거나 다른 풀이를 생각해봐야겠습니다.
> 0603 일일 커밋입니다. #실패

- codility_training/lessons.lesson04.CountingElements.PermCheck/khw970421.js
- codility_training/lessons.lesson05.PrefixSums.CountDiv/khw970421.js
- codility_training/lessons.lesson05.PrefixSums.GenomicRangeQuery/khw970421.js
- codility_training/lessons.lesson06.Sorting.Distinct/khw970421.js
- codility_training/lessons.lesson06.Sorting.MaxProductOfThree/khw970421.js
- codility_training/lessons.lesson06.Sorting.Triangle/khw970421.js
CountDiv는 문제없이 해결됐고
Genomic이 정확성은 문제없으나 효율성에서 0점입니다
> lesson05.PrefixSums.GenomicRangeQuery and CountDiv

- codility_training/lessons.lesson16.GreedyAlgorithms.MaxNonOverLappingSegments/JeongShin.js
이상하게 잘 안풀려서 인터넷 참고하여 풀이 했습니다 ㅜㅜ
> lessons.lesson16.GreedyAlgorithms.MaxNonOverLappingSegments

- programmers/난이도별/level01.문자열_내_마음대로_정렬하기/README.md
- programmers/난이도별/level01.문자열_내_마음대로_정렬하기/dkdlelk99.py
주말은 앓아 누웠지만 솔직히 월요일 화요일은 할 수 있었습니다... 죄송합니다 ㅠㅠㅠ
> 0610 일일커밋입니다.

- programmers/난이도별/level01.행렬의_덧셈/README.md
- programmers/난이도별/level01.행렬의_덧셈/dkdlelk99.py
이 쉬운걸 왜 못풀었었을까...
아무튼 예전에 못푼문제였는데 한방에 풀려서 기분 굿입니다. ㅎㅎ
> 0613 일일 커밋입니다

- codility_training/lessons.lesson11.SieveofEratosthenes.CountNonDivisible/sjjyy.java
> lessons.lesson11.SieveofEratosthenes.CountNonDivisible

- codility_training/lessons.lesson92.TasksFromIndeedPrime2016.CollegeCodersChallenge.DiamondsCount/JeongShin.js
- codility_training/lessons.lesson99.FutureTraining.TreeHeight/JeongShin.js
DiamondCounts 는 나중에 다시 풀어보겠습니다.
> lessons.lesson99.FutureTraining.TreeHeight

- codility_training/lessons.lesson13.FibonacciNumbers.FibFrog/README.md
- codility_training/lessons.lesson13.FibonacciNumbers.FibFrog/sjjyy.java
- codility_training/lessons.lesson15.CaterpillarMethod.AbsDistinct/README.md
- codility_training/lessons.lesson15.CaterpillarMethod.AbsDistinct/sjjyy.java
아직 미완성인 코드라 리뷰&머지는 내일이나 모레쯤 해주셔도 될 것 같아요 ㅠㅠ!
> lessons.lesson13.FibonacciNumbers.FibFrog;

- programmers/난이도별/level03.섬_연결하기/JeongShin.js
가장 먼저 풀이 할때는 준일이형을 assignees 로 등록하는걸로 이해했는데 
잘 이해한건지 모르겠네요 😅
> level03.섬_연결하기

- programmers/난이도별/level01.소수찾기/dkdlelk99.py
- programmers/난이도별/level01.크레인_인형뽑기_게임/README.md
- programmers/난이도별/level01.크레인_인형뽑기_게임/dkdlelk99.py
> 0616 일일커밋입니다.

- codility_training/lessons.lesson15.CaterpillarMethod.CountDistinctSlices/sjjyy.java
- codility_training/lessons.lesson15.CaterpillarMethod.CountTriangles/sjjyy.java
- codility_training/lessons.lesson15.CaterpillarMethod.MinAbsSumOfTwo/sjjyy.java
CountDistinctSlices는 large_range에서 틀린 답이 나와서 더 해봐야 할 것 같아요
> lessons.lesson15.CaterpillarMethod.MinAbsSumOfTwo + CountDistinctSlices

- programmers/난이도별/level03.네트워크/JeongShin.js
- programmers/난이도별/level03.베스트앨범/JeongShin.js
일단 하긴 했는데 가독성이 정말 떨어지는거 같네요 ㅠ 
일단 테스트는 통과하였습니다
> level03.베스트앨범

- programmers/난이도별/level01.실패율/dkdlelk99.py
value 기준으로 정렬된 딕셔너리의 키만 리스트로 만드는 더 간단한 방법이 있을 것만 같은데
쫌만 더 생각하면 될거같습니다
> 0703 일일 커밋/ programmers level01.실패율

- codility_training/lessons.lesson17.DynamicProgramming.NumberSolitaire/sjjyy.java
- programmers/난이도별/level.01하샤드_수/sjjyy.java
많이 어렵네요 ㅠㅠ sol2는 다른 코드를 참고했습니다 ㅠㅠ
> lessons.lesson17.DynamicProgramming.NumberSolitaire

- codility_training/lessons.lesson13.FibonacciNumbers.FibFrog/sAp00n.py
고민하다가 시간이 너무길어져서 솔루션 보고 풀었어요 ㅋㅋ
거의 배꼇네요.
피보나치 수열을 27번째까지 구하지 않는게 그냥 그정도면 충분히 큰 수여서 그런건가 싶어요.
마지막 이중 for loop 사용해서 해 구하는건 상당히 신기하네요.
내일 한번 다시 봐서 완전히 이해해봐야겠습니다.
> lessson13.FibonacciNumbers.Fibfrog

- programmers/난이도별/level01.K번째수/sjjyy.java
- programmers/난이도별/level01/수박수박수박수/sjjyy.java
> 프로그래머스 level01.K번째수 + 수박수박수박수

- codility_training/lessons.lesson12.EuclideanAlgorithm.CommonPrimeDivisors/README.md
- codility_training/lessons.lesson12.EuclideanAlgorithm.CommonPrimeDivisors/eyabc.js
인터넷 보고 코드 정리만 한 수준이네요. 공식은 알겠는데, 원리가 뭔지는 이해하고 싶지도 않음
> lessons.lesson12.EuclideanAlgorithm.CommonPrimeDivisors

- programmers/난이도별/level03.여행경로/JeongShin.js
- programmers/난이도별/level03.이중우선순위큐/JeongShin.js
* 이중우선순위 큐
@JunilHwang 형의 코드를 참고하여 풀이하였습니다. 
* 여행경로 
2개의 테스트 케이스를 통과하지 못하고 있는데 틀리는 부분을 알고 있지만 쉽게 솔루션이 안나오네요 ㅠ 
나중에 다시 시도해서 pr 올리겠습니다 😭
> level03.여행경로

- codility_training/lessons.lesson13.FibonacciNumbers.FibFrog/JeongShin.js
- programmers/난이도별/level03.여행경로/JeongShin.js
- programmers/난이도별/level03.이중우선순위큐/JeongShin.js
일단 풀이를 실패해서 추후에 다시 도전해보는걸로 하겠습니다.
> level03.여행경로 👉 실패 ㅠㅠ 

- programmers/난이도별/level01.2016년/s2uyeoii.c
> level01.2016년

- programmers/난이도별/level01.평균_구하기/HyeonJeong.java
java를 사용해서는 처음 programmers를 풀었는데, 오늘은 실패네요.
저는 어느 부분이 문제인지도 모르겠어요...
> level01.평균_구하기

- programmers/난이도별/level01.모의고사/JeongShin.js
- programmers/난이도별/level03.2xn타일링/JeongShin.js
- programmers/난이도별/level03.디스크_컨트롤러/JeongShin.js
디스크 컨트롤러는 나중에 다시 해보겠습니다. 생각보다 어렵네요 ㅠ ㅠ 
Heap 관련 문제가 유독 어렵게 느껴지는거 같네요 ,,
> level03.2xn타일링

- programmers/난이도별/level01.문자열_다루기_기본/sjjyy.java
parseInt를 쓸 때 예외처리 하던 방식인데 적용이 되네요
> 프로그래머스.level01.문자열_다루기_기본

- programmers/난이도별/level01.문자열을_정수로_바꾸기/sjjyy.java
궁금한 게 있는데 코딩테스트로 알고리즘 풀러 가서도 이런식으로 써도 되나요...? 사실 문제 자체는 parseInt 사용하면 바로 풀리는데 이걸 풀어서 한줄한줄 써야하는 거 아닐까 하는 생각이 들어서요!
> 프로그래머스.level01.문자열을_정수로_바꾸기

- programmers/난이도별/level02.소수_만들기/s2uyeoii.cpp
> level02.소수_만들기 파일명 수정

- codility_training/lessons.lesson14.BinarySearchAlgorithm.MinMaxDivision/sAp00n.py
- codility_training/lessons.lesson14.BinarySearchAlgorithm.MinMaxDivision/sAp00n_pseudo.md
> MinMaxDivision

- programmers/난이도별/level01.완주하지_못한_선수/rockmiin.py
시간 초과가 계속 떠서 은근 고민을 많이 했던 문제네요. 
시간 초과가 뜰 경우 어떤 것을 우선적으로 고려를 해야 될지 알려주시면 정말 감사할 것 같습니다 !
> level01.완주하지못한선수

- programmers/난이도별/level02.큰_수_만들기/JeongShin.js
- programmers/난이도별/level03.줄_서는_방법/JeongShin.js
- programmers/난이도별/level03.하노이의_탑/JeongShin.js
하노이의 탑 같은 경우는 도저히 어려워서 유튜브에서 알고리즘 구현 방법 검색해봐서 풀이하였습니다. 
https://www.youtube.com/watch?v=q6RicK1FCUs
> level03.줄_서는_방법 & level03.하노이의_탑 

- programmers/난이도별/level02.기능개발/rockmiin.py
문제를 잘못 해석해서 애를 먹었던 문제입니다. 
"뒤에 있는 기능은 앞에 있는 기능이 배포될 때 함께 배포됩니다."라는 말이 헷갈렸는데
작업 순서 기준으로 연속적으로 작업이 완료되어 있어야만 수행이 가능하다는 의미인 것 같습니다.
> level02.기능개발

- programmers/난이도별/level03.거스름돈/JeongShin.js
1. 모든 경우의 수 알고리즘
2. dp : O (n * m) 의 시간복잡도 
두가지 다 시도 해봤는데 둘다 효율성 테스트를 통과하지 못하네요,, pr 올려놓고 내일 다시 시도해보겠습니다  😨😰
개인적으로 dp 문제들이 어렵게 느껴지네요 ㅠ ㅠ
> level03.거스름돈 

- programmers/난이도별/level03.거스름돈/JeongShin.js
결국 인터넷에 풀이 검색하여 겨우 이해했습니다. 이런 코드를 스스로 구현하려면 많은 노력이 필요할꺼 같네요 ㅠ
> level03.거스름돈

- programmers/난이도별/level01.문자열_다루기_기본/HyeonJeong.py
- programmers/난이도별/level01.이상한_문자_만들기/HyeonJeong.py
혼자서는 안되서 이미 만들어 보신 분들의 코드를 참조해서 만들어보았습니다.
그런데 테스트에서 오류가 나는 부분이 있네요. 어디를 수정하면 될지 알려주시면 감사하겠습니다!!
> level01.이상한_문자_만들기(완료)

- programmers/난이도별/level01.정수_제곱근_판별/HyeonJeong.py
나름대로 간단하게 만들었다고 생각하는데, n까지 돌아가야 하는 것에서 더 효율적인 방법이 있다면 알려주시면 감사하겠습니다!
> level01.정수_제곱근_판별

- programmers/난이도별/level03.야근지수/JeongShin.js
- programmers/난이도별/level03.저울/JeongShin.js
효율성에서 불합격 입니다. 
다른 언어 (JAVA)같은 경우 같은 로직으로 라이브러리 priorityqueue 를 사용하여 풀이하면 통과하는데 
JS 에서 직접 구현해주려니까 잘 안되네요 ㅠ ㅠ 
일단 pr 하겠습니다.
> level03.야근지수, level03.저울

- programmers/난이도별/level01.나누어_떨어지는_숫자_배열/HyeonJeong.py
코드를 한줄로 만들기는 실패했지만, 조금씩 고쳐가며 최대한 간단하게 만들어보았습니다.
> level01.나누어_떨어지는_숫자_배열

- programmers/난이도별/level02.타겟_넘버/JeongShin.js
같은 문제를 여러가지 방법으로 풀이해보는거도 좋은거 같네요 ! !
> level02.타겟_넘버

- programmers/난이도별/level01.최대공약수와_최소공배수/rockmiin.py
- programmers/난이도별/level01.평균_구하기/rockmiin.py
- programmers/난이도별/level01.하샤드_수/rockmiin.py
1일 1커밋하려고 늦은 시간에라도 간단한 문제 여러개 풀어봤습니다. 의식의 흐름대로 푼거라 효율적이지 않을 수도 있을거 같네요 :(
> level01.하샤드_수

- programmers/난이도별/level01.콜라츠_추측/HyeonJeong.py
전에 c언어로 비슷한걸 만들어 본적이 있어서 이번에는 빨리 코드를 완성할 수 있었습니다.
코드 중에 500번이상 돌아가면 return하는 조건에서 if tries >= 500와 if tries == 500 중 어떤 것을 사용하는게 더 나은 건가요?
> level01.콜라츠_추측

- programmers/난이도별/level01.최대공약수와_최소공배수/HyeonJeong.py
while문을 이용해 나름대로 간단하게 만들어 보았습니다.
주어지는 수가 클 때 더 효율적으로 계산할 수 있는 방법은 무엇이 있나요?
> level01.최대공약수와_최소공배수

- programmers/난이도별/level02.H-Index/rockmiin.py
테스트 케이스 한 개가 계속 안되서 애 먹었던 문제네요. 보다 효율적인 방법으로 코드를 짜려고 생각을 했던 문제였네요.
> level02.H-index

- programmers/난이도별/level01.제일_작은_수_제거하기/HyeonJeong.py
결과가 정해진 것은 바로 return 시키는게 더 효율적인 코드로 만든다는 것을 다시 인지합니다!!
temp를 없애고 그자리에 min(arr)를 넣으면 오류가 발생하는데, 어디가 문제인지는 모르겠네요..
> level01.제일_작은_수_제거하기

- programmers/난이도별/level03.방문_길이/JeongShin.js
제가 작성한 코드지만 제가봐도 좀 좋은 코드는 아닌거 같네요 ,,,,,
> level03.방문 길이

- BOJ/2740.행렬곱셈/sAp00n.py
괜히 행렬 객체로 선언해서 풀다가
__str__ 매소드로 이쁘게 출력하는거에 꽂혀서 시간 다보냈습니다.
백준 문제 풀이의 입출력에 관해서는 어느정도 감을 잡은거 같네요!
코딜리티보다 채점결과에 대해서 불친절하지만, 이 떄문에 뭐 틀렸는지 더 스트레스받아가면서 고민해서 실력이 느는 느낌은 납니다..
> BOJ.2740.행렬곱셈

- programmers/난이도별/level02.124_나라의_숫자/README.md
- programmers/난이도별/level02.124_나라의_숫자/dkdlelk99.py
풀이에 집중해서 코드가 많이 번잡스러움
'124'진수끼리 더해주는 방법을 잘 생각해보면 첫번째 while에서 끝낼 수 있을 것 같은데...
> 0729 일일커밋 / 프로그래머스 레벨2 124 나라의 숫자

- programmers/난이도별/level02.주식가격/rockmiin.py
- programmers/난이도별/level03.정수삼각형/rockmiin.py
level03.정수삼각형 dp문제 처음 풀어봤는데 좀 더 깔끔하게 하는 법이 있으면 알려주시면 감사하겠습니다 !
> level02.주식가격 & level03.정수삼각형

- programmers/난이도별/level01.핸드폰_번호_가리기/HyeonJeong.py
더 간단하게 하고 싶었는데, 생각보다 잘 안되네요.
조금 더 빠르게 작동되려면 어떤 식으로 고쳐야 할까요?
> level01.핸드폰_번호_가리기

- programmers/난이도별/level03.징검다리_건너기/JeongShin.js
문제 제한사항 제대로 안읽고 풀이하다가 시간만 날려먹었네요 ,, 🤯
> level03.징검다리_건너기

- programmers/난이도별/level01.x만큼_간격이_있는_n개의_숫자/HyeonJeong.py
런타임 에러가 발생하는데, 왜 발생하고 어디를 고쳐야 하는지 모르겠습니다.  도움 부탁드립니다!!
> level01.x만큼_간격이_있는_n개의_숫자

- programmers/난이도별/level01.서울에서_김서방_찾기/HyeonJeong.java
- programmers/난이도별/level01.서울에서_김서방_찾기/HyeonJeong.py
- programmers/난이도별/level01.정수_내림차순으로_배치하기/HyeonJeong.py
format()를 이용해서 문자열 사이에 원하는 값을 넣을 수 있다는 것을 알게 되었습니다.
> level01.서울에서_김서방_찾기

- programmers/난이도별/level04.가사_검색/JeongShin.js
처음 구현해보는 자료구조라 쉽지 않네요 ㅠ 그래도 풀이 성공하니까 뿌듯합니당 ,, 😅
> level04.가사검색

- programmers/난이도별/level01.완주하지_못한_선수/sjjyy.java
해시 문제인데 해시맵이 익숙하지 않아서 솔루션을 참고했습니다 😂
> 프로그래머스.level01.완주하지_못한_선수

- programmers/난이도별/level02.타겟_넘버/JeongShin.js
- programmers/난이도별/level04.호텔_방_배정/JeongShin.js
level02.타겟넘버의 경우 지난번에 풀이하였는데 실수로 merge 한 걸 revert 한 뒤로 내용이 삭제되었길래 다시 pr 올립니다. 
레벨 4 문제들부턴 제가 잘 모르는 새로운 개념들이 많이 필요해서 문제를 풀어보기보단 접해보는 느낌이 더 강하네요,, 
JS Map 의 중요성에 대해 다시 한번 느꼈습니다
> level04.호텔_방_배정 

- programmers/난이도별/level04.지형_이동/JeongShin.js
모든 테스트 케이스를 통과하긴 하지만 정말 가까스로 통과하네요. 
하나라도 가독성 높이려고 수정하면 바로 불합격하네요,, 
찝찝하지만 일단 pr 해놓고 나중에 다시 풀이해봐야겠어요
> level04.지형이동

- programmers/난이도별/level01.문자열_내_p와_y의_개수/HyeonJeong.py
- programmers/난이도별/level01.소수찾기/HyeonJeong.py
여러 방식으로 코드를 고쳐봤는데, 시간은 줄어들어도 마지막 3개의 테스트에서 시간 초과로 계속 실패가 뜨네요.
제가 풀이법을 생각하는 방식에서 오류가 있었던 걸까요??
문자열 내 p와 y의 개수 코드도 한번 확인 부탁드려요!!
> level01.소수찾기(미완료) & 문자열 내 p와 y의 개수

- programmers/난이도별/level03.2xn타일링/rockmiin.py
BOJ 푸느라고 프로그래머스는 오랜만에 올리네요 .
DP문제입니다. 아직까지는 직관적으로 점화식 찾는 방법이 가능한 것 같습니다 !
> level03.2*n타일링

- programmers/난이도별/level01.문자열을_정수로_바꾸기/HyeonJeong.py
저는 실수일 때는 생각을 못했는데, 다른 분들은 그것도 고려하셨더라구요.
문자열을 숫자로 바꾸기 위해서는 int() 사용만으로도 가능하다는 것도 알아갑니다!
> level01.문자열을_정수로_바꾸기

- BOJ/solved.ac_class/Class02/1018.채스판 다시 칠하기/sAp00n.py
- BOJ/solved.ac_class/Class02/1085.직사각형에서 탈출/sAp00n.py
- BOJ/solved.ac_class/Class02/1181.단어정렬/sAp00n.py
- BOJ/solved.ac_class/Class02/1259.팰린드롬수/sAp00n.py
- BOJ/solved.ac_class/Class02/1920.수 찾기/sAp00n.py
- codility_training/lessons.lesson13.FibonacciNumbers.Ladder/sAp00n.py
lesson 13. Fibonacci Num 에 발생한 충돌 수정했습니다.
노트북하고 pc하고 옮겨다니면서 풀이하느라 그랬나봐요 ㅋㅋ
> Fix conflict

- programmers/난이도별/level01.체육복/HyeonJeong.py
테스트12만 실패로 뜨는데, 조건에서 어떤 부분을 고려를 못한 걸까요??
> level01.체육복

- programmers/난이도별/level01.자릿수_더하기/HyeonJeong.py
비슷한 코드를 만들어 본 적이 있어서 이번에는 쉽게 했네요!!
> level01.자릿수_더하기

- programmers/난이도별/level01.문자열_내림차순으로_배치하기/HyeonJeong.py
> level01.문자열_내림차순으로_배치하기

- programmers/난이도별/level01.모의고사/HyeonJeong.py
초기에 했을 때는 엄청 어려워서 미뤄두고 있었는데, 이제야 코드를 완성하네요!!
> level01.모의고사

- programmers/난이도별/level01.완주하지_못한_선수/HyeonJeong.py
다른 분들 코드를 참고해서 sort()를 이용해 보았습니다.
> level01.완주하지_못한_선수

- LeetCode/Trie/Design_Add_and_Search_Words_Data_Structure/JeongShin.js
- programmers/난이도별/level03.여행경로/JeongShin.js
LeetCode 가 효율성을 총 정답들 중에서 상위 몇 프로인지 알려주니까 더 신경써서 코딩하게 되네요
> LeetCode/Design_Add_and_Search_Words_Data_Structure 풀이 & level03.여행경로 복습 및 수정

- programmers/난이도별/level02/조이스틱/HyeonJeong.py
- programmers/난이도별/level02/조이스틱/README.md
경우를 하나하나 다 써가면서 체크했는데, 실패가 계속 뜨네요..
어디가 문제인가요? 도움 부탁드립니다!!
> level02.조이스틱

- programmers/난이도별/level02.가장_큰_수/rockmiin_가장큰수.py
생각해보는데 왜 안되는지 모르겠네요
도움 주시면 감사하겠습니다
> level02.가장 큰 수 (미완)

- programmers/난이도별/level02.최댓값과_최솟값/rockmiin_최댓값과최솟값.py
> level02.최댓값과최솟값

- programmers/난이도별/level02.주식가격/dkdlelk99.py
간만에 솔루션 안보고 혼자 풀어내니까 뿌듯하네요!
대신 풀이에만 집중해서 코드는 조금 더럽네요
> 프로그래머스 level2 주식가격

- programmers/난이도별/level03.네트워크/rockmiin_네트워크.py
DFS BFS 문제입니다. 시작한지 얼마 안되서 부족하지만 피드백 주시면 수정하겠습니다 !
> level03.네트워크

- programmers/난이도별/level02/영어_끝말잇기/HyeonJeong.py
- programmers/난이도별/level02/영어_끝말잇기/README.md
#코드1을 깔끔하게 만들고 싶었는데 정리가 잘 안된 것 같네요..
> level02.영어_끝말잇기

- programmers/난이도별/level03.불량_사용자/JeongShin.java
2번째 솔루션은 다른 분의 풀이를 참고했는데 
보면서 이 문제 풀이 정석 이구나 느꼈습니다,,,
> level03.불법 사용자 풀이 

- programmers/난이도별/level02.기능개발/dkdlelk99_v2.py
풀었다는 표시를 못보고 또풀었습니다.... 어쩐지 엄청 빨리 풀리더라고요...ㅠㅠㅠ
이번에는 배운 스택/큐를 써먹어봤습니다.
> 프로그래머스 LV2 기능개발

- programmers/난이도별/level02/올바른_괄호/HyeonJeong.py
준일님의 코드리뷰 전에 Merge를 해버려서 고쳐서 올립니다!
> level02.올바른_괄호 2

- programmers/난이도별/level01.하샤드_수/s2uyeoii.cpp
> s2uyeoii.cpp

- programmers/난이도별/level02/최대값과_최솟값/HyeonJeong.py
> level02.최대값과 최솟값

- programmers/난이도별/level01.이상한_문자_만들기/s2uyeoii.cpp
- programmers/난이도별/level01.자연수_뒤집어_배열로_만들기/s2uyeoii.cpp
간단한 자릿수 문제입니다. 
c++보다 c언어가 훨씬 불편하네요,,ㅜ
> level01.자연수뒤집어배열만들기 & 이상한 문자 만들기

- programmers/난이도별/level02.가장_큰_수/sjjyy.java
3과 30을 구분하는 방법이 떠오르지 않아서 다른 코드도 참고했습니다
> 프로그래머스.level02.가장_큰_수

- programmers/난이도별/level01.문자열_내_p와_y의_개수/HyeonJeong.java
JAVA를 사용 안 하다보니 너무 잊어버려서 계속 JAVA도 해야겠네요
> level01.문자열 내 p와 y의 개수

- BOJ/2193.이친수/rockmiin.py
- BOJ/9461.파도반수열/rockmiin.py
- LeetCode/DFS/Number_of_Islands/JeongShin.js
- LeetCode/DFS/Target_Sum/JeongShin.js
- LeetCode/Sliding_Window/Longest_Substring_Without_Repeating_Characters/JeongShin.js
주석 처리한 풀이는 처음에 했던 풀이 인데 메모리 초과가 나더라구요. 이런식으로 풀 때 메모리 초과 안나는 방법이 있다면 알려주시면 감사하겠습니다.
메모리 초과나서 아래와 같이 다시 풀어봤습니다.
> 2193.이친수 / 9461.파도반수열

- BOJ/1181.단어 정렬/rockmiin.py
맞게 푼 것 같은데 자꾸 런타임 에러가 뜨네요. 찾아보니까 인덱스 에러인것 같은데 제 눈에만 안 보이네요. 피드백 주시면 감사하겠습니다 !
> 1181.단어정렬(미완)

- LeetCode/Dynamic_Programming/Coin_Change/JeongShin.js
- programmers/난이도별/level04.올바른_괄호의_갯수/JeongShin.js
https://leetcode.com/problems/coin-change/
```JS
const coins = [1,2,5], amount = 11;
```
과 같이 동전이 주어졌을 때, amount 를 만드는데 필요한 최소 동전의 개수를 구하는 문제
프로그래머스 level 3 에 있는 문제와 동일한 문제를 풀었던게 생각나서
시간은 좀 걸렸지만 지난번과 다르게 풀이를 보지 않고 풀이 성공해서 기분이 좋네요ㅎ,,,
https://programmers.co.kr/learn/courses/30/lessons/12909
```js
const n = 5; 
```
n이 주어질 때 n 개의 쌍의 괄호를 만드는 경우의 수를 구하는 문제
이 문제는 Catalan Number 를 구하는 알고리즘으로 풀이할 수 있는데
이전에 릿 코드에서 같은 알고리즘을 사용하는 [unique binary search tree](https://github.com/DKU-STUDY/Algorithm/blob/master/LeetCode/Tree/Unique_Binary_Search_Trees/JeongShin.js) 예제를 보다가 이 문제가 해당되는걸 봐놔서 다시 공부해봤습니다,, 하지만 코테에서 나오면 못풀꺼 같네요 ,, ㅠㅠ
> leetcode/dp/coin change 풀이

- programmers/난이도별/level02/JadenCase_문자열_만들기/HyeonJeong.py
- programmers/난이도별/level02/JadenCase_문자열_만들기/README.md
> 프로그래머스.level01.JadenCase_문자열_만들기

- LeetCode/Union_Find/Surrounded_Regions/eyabc.js
문제 설명은 주석에 있습니다
https://leetcode.com/problems/surrounded-regions/
> [UnionFind]Surrounded Regions

- programmers/난이도별/level02.짝지어_제거하기/eyabc.js
문제: https://programmers.co.kr/learn/courses/30/lessons/12973
b aa baa → bb aa → aa →
의 순서로 문자열을 모두 제거할 수 있으므로 1을 반환 /모두 제거할 수 없으면 0 을 반환
제한사항
문자열의 길이 : 1,000,000이하의 자연수
문자열은 모두 소문자
s | result
-- | --
baabaa | 1
cdcd | 0
> [level02] 짝지어 제거하기

- programmers/난이도별/level02.짝지어_제거하기/HyeonJeong.py
- programmers/난이도별/level02.짝지어_제거하기/README.md
문제 설명
> s : baabaa -> result : 1
> s : cdcd -> result : 0
문자열에서 같은 알파벳이 2개 붙어 있는 짝을 찾습니다.  그 둘을 제거한 뒤, 앞뒤로 문자열을 이어 붙입니다. 이 과정을 반복해서 문자열을 성공적으로 모두 제거한다면 1을, 아닐 경우 0을 리턴해주면 됩니다.
제한사항
> 문자열의 길이 : 1,000,000이하의 자연수
> 문자열은 모두 소문자
https://programmers.co.kr/learn/courses/30/lessons/12973
> [level02]짝지어_제거하기

- programmers/난이도별/level01.완주하지_못한_선수/sangmandu.py
- programmers/월간코드_챌린지1/9월/01. 두 개 뽑아서 더하기/sangmandu.py
- programmers/카카오-2019_하반기_인턴_코딩테스트/01. 크레인 인형뽑기 게임/sangmandu.py
- programmers/카카오-2019_하반기_인턴_코딩테스트/02. 튜플/sangmandu.py
- programmers/카카오_2020_블라인드채용_코딩테스트/01.문자열압축/sangmandu.py
- programmers/카카오_2020_블라인드채용_코딩테스트/02.괄호변환/sangmandu.py
[level1]
완주하지 못한 선수 https://programmers.co.kr/learn/courses/30/lessons/42576
- 완주하지 못한 선수 단 1명을 찾아라!
input [leo, kiki, eden]  [eden, kiki] 
return leo
[월칸코드챌린지1]
두 개 뽑아서 더하기 https://programmers.co.kr/learn/courses/30/lessons/68644
numbers | result
- 입력값 중 2개를 더해서 만들 수 있는 모든 수
[2,1,3,4,1] | [2,3,4,5,6,7]
[5,0,2,7] | [2,5,7,9,12]
[2019하반기 인턴]
크레인 인형뽑기 게임 https://programmers.co.kr/learn/courses/30/lessons/64061
- 인형뽑기 알고리즘
board | moves | result
[[0,0,0,0,0],[0,0,1,0,3],[0,2,5,0,1],[4,2,4,4,2],[3,5,1,3,1]] | [1,5,3,5,1,2,1,4] | 4
튜플 https://programmers.co.kr/learn/courses/30/lessons/64065
- 많이 나오는 수부터 리스트에 담기
s | result
"{{2},{2,1},{2,1,3},{2,1,3,4}}" | [2, 1, 3, 4]
"{{1,2,3},{2,1},{1,2,4,3},{2}}" | [2, 1, 3, 4]
"{{20,111},{111}}" | [111, 20]
"{{123}}" | [123]
"{{4,2,3},{3},{2,3,4,1},{2,3}}" …
> [level1]완주하지 못한 선수 [월칸코드챌린지1] 두 개 뽑아서 더하기 [2019하반기 인턴] 크레인 인형뽑기 게임, 튜플 [2020 블라인드 채용] 문자열 압축, 괄호 변환

- programmers/난이도별/level02.더 맵게/HyeonJeong.py
정확성은 다 통과하는데, 효율성에서 문제가 발생하네요
https://programmers.co.kr/learn/courses/30/lessons/42626
> [level02] 더_맵게

- programmers/난이도별/level01.문자열_내_마음대로_정렬하기/HyeonJeong.py
strings : [sun, bed, car], n : 1 -> return [car, bed, sun]
strings : [abce, abcd, cdx] n : 2 -> return [abcd, abce, cdx]
문제 설명
문자열로 구성된 리스트 strings와, 정수 n이 주어졌을 때, 각 문자열의 인덱스 n번째 글자를 기준으로 오름차순 정렬하려 합니다.
제한 조건
strings는 길이 1 이상, 50이하인 소문자 알파벳으로 이루어진 배열
strings 원소는 길이 1 이상, 100이하인 문자열
모든 strings의 원소의 길이는 n보다 큼
인덱스 n의 문자가 같은 문자열이 여럿 일 경우, 사전순으로 위치
https://programmers.co.kr/learn/courses/30/lessons/12915
> [level01] 문자열 내 마음대로 정렬하기

- BOJ/solved.ac_class/Class03/1764.듣보잡/sAp00n.py
- BOJ/solved.ac_class/Class03/1927.최소 힙/sAp00n.py
힙을 라이브러리를 안 쓰고 구현하려다가 그냥 포기했습니다.
C++풀이도 보니까 라이브러리 쓰더라구요 ㅋㅋ
1764. 듣보잡.
https://www.acmicpc.net/problem/1764
문제
김진영이 듣도 못한 사람의 명단과, 보도 못한 사람의 명단이 주어질 때, 듣도 보도 못한 사람의 명단을 구하는 프로그램을 작성하시오.
입력
첫째 줄에 듣도 못한 사람의 수 N, 보도 못한 사람의 수 M이 주어진다. 이어서 둘째 줄부터 N개의 줄에 걸쳐 듣도 못한 사람의 이름과, N+2째 줄부터 보도 못한 사람의 이름이 순서대로 주어진다. 이름은 띄어쓰기 없이 영어 소문자로만 이루어지며, 그 길이는 20 이하이다. N, M은 500,000 이하의 자연수이다.
출력
듣보잡의 수와 그 명단을 사전순으로 출력한다.
1927.최소 힙
https://www.acmicpc.net/problem/1927
문제
널리 잘 알려진 자료구조 중 최소 힙이라는 것이 있다. 최소 힙을 이용하여 다음과 같은 연산을 지원하는 프로그램을 작성하시오.
배열에 자연수 x를 넣는다.
배열에서 가장 작은 값을 출력하고, 그 값을 배열에서 제거한다.
프로그램은 처음에 비어있는 배열에서 시작하게 된다.
입력
첫째 줄에 연산의 개수 N(1≤N≤100,000)이 주어진다. 다음 N개의 줄에는 연산에 대한 정보를 나타내는 정수 x가 주어진다. 만약 x가 자연수라면 배열에 x라는 값을 넣는(추가하는) 연산이고, x가 0이라면 배열에서 가장 작은 값을 출력하고 그 값을 배열에서 제거하는 경우이다. 입력되는 자연수는 2^31보다 작다.
출력
입력에서 0이 주어진 …
> BOJ 1764. 듣보잡, 1927.최소 힙

- BOJ/1699.제곱수의 합/제곱수의_합_1699.py
오랜만에 푸는거라 생각보다 오래 걸렸던 것 같네요.
조금씩이라도 꾸준히해야겠네요
> BOJ 1699.제곱수의 합

- programmers/난이도별/level02.더 맵게/sjjyy.java
https://programmers.co.kr/learn/courses/30/lessons/42626
> [level02] 더 맵게

- LeetCode/Binary_Search/Minimum_Size_Subarray_Sum/JeongShin.js
https://leetcode.com/problems/minimum-size-subarray-sum/
```JS
const s = 7, nums = [2,3,1,2,4,3]; 
```
와 같이 필요한 합 s 가 주어지고 배열 nums 가 주어질 때 subarray 로 s 보다 큰 수를 만들수 있는 최소 길이를 구하는 문제 입니다. 
Bin Search 로 분류 되어 있지만 풀이는 이분탐색과는 조금 다른게 아닌가 싶습니다... 
nums 의 값을 하나씩 더해가면서 앞에서부터 필요 없는 값들을 버려가면서 최소 길이를 구하는 방법으로 풀이하였습니다.
> [LeetCode] Min Size Subarray Sum 풀이

- programmers/난이도별/level02.위장/sjjyy.java
> [level02] 위장

- LeetCode/DFS/Course_Schedule/JeongShin.js
https://leetcode.com/problems/course-schedule/
```JS
numCourses = 2, prerequisites = [[1,0],[0,1]]
```
위와 같이 들을 수 있는 총 강의 수 : numCourses, 선수과목  prerequisites 가 배열로 주어질 때 모든 과목을 수강 가능하면 true/ 아니면 false 를 반환 하는 문제 
위의 경우 1 번 과목을 듣기 위해 0번 과목을 들어야하지만 0번 과목은 1번 과목을 필요로 하기 때문에 논리적으로 순서가 맞지 않기 때문에 false 를 반환해야 합니다.
> [dfs]course_schedule

- programmers/난이도별/level02.최댓값과_최솟값/sjjyy.java
> [level02] 최댓값과 최솟값

- LeetCode/DFS/Course_Schedule_II/JeongShin.js
https://leetcode.com/problems/course-schedule-ii/
numCourses = 4, prerequisites = [[1,0],[2,0],[3,1],[3,2]]
와 같이 강의 수와 선수과목의 배열이 올때 가능한 수업 순서의 배열을 반환하면 됩니다. 
가능한 모든 경우 중 하나라도 해당되는걸 반환하면 되고 0번 ~ n번 강의를 수강하면서 가능한 지 확인 해야합니다. 
course schedule 에서 조금만 더 생각하면 되는 문제인데 조금 어렵게 느껴졌네요 ㅠ
> [dfs]Course_Schedule_II

- LeetCode/Array/Missing_Number/HyeonJeong.py
- LeetCode/Array/Running_Sum_of_1d_Array/HyeonJeong.py
https://leetcode.com/problems/missing-number/
`nums = [3,0,1]` -> [0 : n]에서 nums에서 존재하지 않는 값 반환 -> `2`
시간복잡도O(n)이나 O(1)을 사용하는 문제라 for문과 len()을 사용해서 해당 수가 존재하는지 확인하였습니다.
https://leetcode.com/problems/running-sum-of-1d-array/
`nums = [1,2,3,4]` -> `[1, 1+2, 1+2+3, 1+2+3+4]` -> `[1,3,6,10]` 반환
각 리스트의 요소가 차례대로 누적된 값이 리스트로 반환하는 문제로 이중for문을 통해서 더해지는 값의 범위를 조절하였습니다.
> [LeetCode] Missing Number & Runnung Sum of 1d Array

- LeetCode/Union_Find/Redundant_Connection/JeongShin.js
https://leetcode.com/problems/redundant-connection/ 
```js
const edges = [[1,2], [1,3], [2,3]]; 
``` 
와 같이 edge 에 대한 정보가 담긴 배열이 주어질 때 싸이클을 만드는 edge 중 가장 마지막 요소를 반환하는 문제 입니다. 
Union Find 개념 처음 풀이하기 좋은 난이도라 생각 됩니다. 
다만 Redundant Connection II 는 상당히 풀이가 어렵게 느껴지네요,,,
> [LeetCode] Redundant Connection

- LeetCode/BFS/01_Matrix/JeongShin.js
- LeetCode/Union_Find/Redundant_Connection/JeongShin.js
https://leetcode.com/problems/01-matrix/submissions/
```JS
[[0,0,0],
[0,1,0],
[0,0,0]]
```
위와 같이 배열에서 가장 가까운 0과의 거리를 매핑하여 반환하는 문제 입니다. 
bfs 로 풀이해봤는데 성능이 하위 17%라 좀 아쉽네요,,, 
여러개 pr 올려보려고 브랜치 새로 생성해서 올려봤는데 이 방법이 맞는지 잘 모르겠습니다.
> [LeetCode] 01 matrix

- LeetCode/Backtracking/Palindrome_Partitioning/JeongShin.js
https://leetcode.com/problems/palindrome-partitioning/
backtracking, dfs 알고리즘 문제 입니다. 
```JS
const str = "aab"
// [
//  ["aa","b"],
//  ["a","a","b"]
// ]
```
위와 같이 string 을 쪼개어 palindrome 이 가능하면 배열에 푸쉬하고 문자열이 palindrome subset 전체를 이루면 
저장하여 반환 합니다. 
어려워서 discussion 을 참고했는데 possibleAnswer 를 전부 초기화 시킬 필요 없이 하나씩 차례대로  pop 해주면 되는걸 생각해내지 못한게 아쉽네요.
> [DFS, Backtacking] Palindrome Partitioning

- LeetCode/String/Longest_Substring_Without_Repeating_Characters/HyeonJoeng.py
https://leetcode.com/problems/longest-substring-without-repeating-characters/submissions/
Input: s = "pwwkew" -> Output: 3
문자열s에서 같은 문자가 존재하지 않는 최대 길이의 문자열을 찾는 문제로
for문으로 문자열의 처음부터 끝까지 시작점으로 잡게 하여 같은 문자를 만나는 경우 그 전까지 누적한 문자열의 길이를  반환하게 하여서 길이의 최대 값을 리턴하게 구성하였습니다.
> [LeetCode] Longest Substring Without Repeating Characters

- programmers/난이도별/level01.x만큼_간격이_있는_n개의_숫자/sangmandu.py
- programmers/난이도별/level01.다트_게임/sangmandu.py
- programmers/난이도별/level01.비밀지도/sangmandu.py
- programmers/난이도별/level01.실패율/sangmandu.py
- programmers/난이도별/level01.예산/sangmandu.py
- programmers/난이도별/level01.직사각혁_별찍기/sangmandu.py
- programmers/난이도별/level01.콜라츠_추측/sangmandu.py
- programmers/난이도별/level01.평균_구하기/sangmandu.py
- programmers/난이도별/level01.하샤드_수/sangmandu.py
- programmers/난이도별/level01.핸드폰_번호_가리기/sangmandu.py
- programmers/난이도별/level01.행렬의_덧셈/sangmandu.py
> [level01] x만큼 간격이 있는 n개의 숫자, 다트 게임, 비밀지도, 실패율, 예산, 직사각형 별찍기, 콜라츠 추측, 평균 구하기, 하샤드 수, 핸드폰 번호 가리기, 행렬의 덧셈

- BOJ/solved.ac_class/Class03/11399. ATM/sAp00n.py
- BOJ/solved.ac_class/Class03/11723.집합/sAp00n.py
- BOJ/solved.ac_class/Class03/11724.연결 요소의 개수/sAp00n.py
- BOJ/solved.ac_class/Class03/11726.2xn 타일링/sAp00n.py
- BOJ/solved.ac_class/Class03/18870.좌표 압축/sAp00n.py
- BOJ/solved.ac_class/Class04/1149.RGB거리/sAp00n.py
클레스 5는 좀 어렵네요... 첫문제에서 고민중입니다.
> BOJ 11724. 연결요소의 개수 BOJ 11726. 2xn 타일링 BOJ 18870. 좌표 압축

- programmers/난이도별/level01.두 개 뽑아서 더하기/develop-sell.js
- programmers/난이도별/level01.문자열_내림차순으로_배치하기/develop-sell.js
안녕하세요! 알고리즘 스터디에 참여하게 된 박세일입니다! 
잘 부탁드립니다. 
const ans = new Set(answer);
answer = [ ...ans ];
answer.sort((a,b) => { return(a-b);})
Set함수로 중복되는 숫자를 지우고, 전개 연산자(spread operator)  "..." 로 다시 set형태를 배열로 바꿨습니다
이후 배열의 sort함수로 순서대로 나열했습니다. 
배운 것 : 전개연산자, Set함수, sort함수 
사이트 : https://programmers.co.kr/learn/courses/30/lessons/68644
참고: (자바스크립트 ES6 — Set에 대해 알아보자)
https://medium.com/@khwsc1/%EC%9E%90%EB%B0%94%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8-es6-set%EC%97%90-%EB%8C%80%ED%95%B4-%EC%95%8C%EC%95%84%EB%B3%B4%EC%9E%90-9b7294dfba99
> [Programmers]level01. 두개 뽑아서 더하기

- LeetCode/Array/Search_in_Rotated_Sorted_Array/HyeonJoeng.py
[https://leetcode.com/problems/search-in-rotated-sorted-array/]
Input : nums = [4,5,6,7,0,1,2], target = 0 -> Output : 4
nums와 target이 주어지면 target이 nums에 없으면 -1을 반환, 있으면 target의 인덱스 번호를 반환하는 문제
target이 nums에 존재하는지 확인해서 없으면 반환시키고, 있는 경우는 enumerate를 이용한 for문에서 비교후 반환하게 만듦
> [LeetCode] Search in Rotated Sorted Array

- LeetCode/Dynamic_Programming/Word_Break/JeongShin.js
https://leetcode.com/problems/word-break/
```js
Input: s = "catsandog", wordDict = ["cats", "dog", "sand", "and", "cat"]
Output: false
```
과 같이 있을때 s 의 문자열을 정확하게 wordDict 에 있는 단어들로 나누어 지는 경우 true, 그렇지 않은 경우 false 를 반환하는 문제 입니다. 
효율성에서 하위 7% 가 나왔는데 아마 trie 를 이용하여 단어 탐색을 더 빠르게 하려했으나 
테스트 케이스에서 wordDic 에서 trie 를 만드는데 비용이 탐색 비용보다 더 많이 들어 그런거 같습니다. 
만약 wordDic 에 word들이 더 많아지면 trie 를 이용하는게 더 효율적이라 생각합니다.
> [DP] Word Break

- programmers/난이도별/level02.튜플/JeongShin.js
정규식 이용하여 "{}," 을 " " 공백으로 만들어 준 뒤, 숫자의 빈도를 이용하여 정렬하여 배열을 반환했습니다. 
다만 문제에 숫자의 빈도에 따라 정렬을 해야한다는 내용이 빠져있는게 이해가 안가네요,, discussion 에서 읽고 알았습니다.
> [프로그래머스 level2] 튜플

- programmers/난이도별/level02.위장/6047198844.cpp
- programmers/난이도별/level02.카펫/6047198844.cpp
- programmers/난이도별/level02.타겟_넘버/6047198844.cpp
**1**
출처 : 프로그래머스 카펫
https://programmers.co.kr/learn/courses/30/lessons/42842
**2**
input :  갈색 격자의 수
output :  노란색 격자의 수
**3**
풀이 아이디어
노란색의  높이 * 2 = 모서리를 제외한 갈색의 왼쪽변/오른쪽변의 길이
노란색의  너비 * 2 = 모서리를 제외한 갈색의 위쪽변/아래쪽변의 길이
따라서 갈색의 길이는 (노란색의 높이 * 2 + 노란색의 너비 * 2 + 4)
여기서 4는 모서리를 더해준것입니다.
yellow의 크기를 1부터 yellow의 제곱근까지 나누어줍니다.
제곱근인이유는 제곱근 이상 할경우 중복이 발생하기 때문입니다.
예를 들면
10같은 경우
1 * 10
2 * 5
5 * 2
10 * 1
여기서 1 * 10 / 2 * 5의 경우의 수만 보면 되니까요. 5 * 2는 2 * 5와 같아요.
그래서 제곱근까지만 해줍니다.
이제 모든 yellow의 높이와 yellow 너비를 고려해줬습니다.
여기서 brown의 갯수 == (yellow 높이 * 2) + (yellow 너비 * 2 ) + 4 인것을 찾습니다.
brown의 너비+2 , brown의 높이+2 를 반환합니다.
**4**
후기
쉬운 문제였습니다.
**1**
출처 : 프로그래머스
https://programmers.co.kr/learn/courses/30/lessons/43165
**2**
input : 숫자의 개수가 주어집니다. 만들고 싶은 수가 주어집니다.
output :  경우의 수를 리턴합니다.
**3**
풀이 아이디어
일단 더하는 경우와 …
> 카펫/타겟넘버/위장

- programmers/난이도별/level01.두 개 뽑아서 더하기/6047198844.cpp
- programmers/난이도별/level01.완주하지_못한_선수/6047198844.cpp
**1**
출처 : 프로그래머스
https://programmers.co.kr/learn/courses/30/lessons/68644
**2**
input : numbers
output : numbers에서 두개를 뽑아 더한값,  중복허용 X
**3**
numbers의 길이가 100이하이기때문에 브루트 포스로 풀었음. 중복허용하지 않으므로 answer에서 2개를 골라 더하고 set에 넣은 뒤 set에 있는 값을 answer에 놓았음. set은 중복허용하지 않음.
**4**
후기
매우 쉬움
**1**
출처 : 프로그래머스
https://programmers.co.kr/learn/courses/30/lessons/42576
**2**
input : 참가자
output : 완주한 사람
**3**
map에 참가자들을 넣음. 동명이인이 있을수있으므로 넣을때마다 해당 이름(key)의 int값(value)을 증가시킴.
이제 map에서 완주자를 뺌.
항상 완주자가 한명 작으므로 반드시 한명이 완주하지 않았다고 볼수있음. 즉 map의 value가 1인 경우 완주하지 않은것과 같음. 해당 key를 리턴함. 
**4**
매우쉬움 return이 if안에 있어서 위험하지만 반드시 한명이 완주하지 않으므로 if안에 넣었음.
> 완주하지 못한 선수& 두 개 뽑아서 더하기

- programmers/난이도별/level01.크레인_인형뽑기_게임/turquoiseluv.py
https://programmers.co.kr/learn/courses/30/lessons/64061
1) zip(*list)로 2d 배열 뒤집기
2) 각 move의 행마다 0이 아닌 값을 만나면 basket에 넣기
3) 최종 basket에서 같이 붙은 두 원소들을 빼주는 방식으로 뽑힌 인형 개수 세기
> [level01] 크레인 인형뽑기 게임

- programmers/난이도별/level02.구명보트/6047198844.cpp
- programmers/난이도별/level02.소수_찾기/6047198844.cpp
**1**
출처 : 프로그래머스
https://programmers.co.kr/learn/courses/30/lessons/42885
**2**
input : 사람들의 몸무게를 담은 배열 , 부개 제한
output : 필요한 구명보트 개수의 최솟값
**3**
풀이 아이디어
가장 무거운 사람은 가장 가벼운 사람과 연결되어야 합니다.
내림차순으로 정리합니다.
for문을 돌리는데 for문의 최대 인덱스가 min_element입니다.
이것의 의미는 다음과 같습니다.
min_element의 의미는 현재 남아있는것중 가장 작은 것의 인덱스입니다.
i는 현재 남아있는것중 가장 큰것의 인덱스입니다.
남아있는것중 가장 큰값과 가장 작은 값을 더한값이 limit을 초과하지 않으면 둘을 짝지어 줍니다. 짝이 되었으니 i의 범위가 줄어들었습니다. 따라서 min_element는 감소합니다.
정리하면
i는 타야할 사람중 가장 무거운 사람을 가리키는 인덱스이고.
min_element는 타야할 사람중 가장 가벼운 사람을 가리키는 인덱스입니다.
i가 증가한다는것은 가장 무거운 사람이 탑승한다는 뜻입니다.
min_element가 감소한다는것은 가장 가벼운사람이 탑승한다는 뜻입니다.
예를 들면 limit가 100일때 100 80 70 60 50 30 20 을 예로 들면
answer은 각 단계마다 증가합니다.
1. 100+20은 100을 넘습니다. i만 증가합니다. 100이 탑승했습니다.
2. 80+20은 100입니다. 따라서 80과 20이 탑승합니다. 따라서 i가 증가하고 min_element가 감소합니다. 80이 탑승하고 20이 …
> [level02]구명보트

- programmers/난이도별/level02.쿼드압축 후 개수 세기/6047198844.cpp
- programmers/난이도별/level02.튜플/6047198844.cpp
- programmers/난이도별/level02/올바른_괄호/6047198844.cpp
튜플
**1**
출처 : 프로그래머스
https://programmers.co.kr/learn/courses/30/lessons/64065
**2**
input : 중복되는 원소가 없는 튜플
output :  튜플
**3**
풀이 아이디어
1. 각 튜플을 백터에 넣습니다.
2. 백터를 사이즈크기 오름차순으로 정렬 합니다.
3. 백터를 처음부터 탐색하며 탐색되지 않았던 원소를 추가합니다.
4. 다음 튜플로 넘어갑니다. 모든 튜플을 탐색할때까지 반복합니다.
예를 들면,
"{{1,2,3},{2,1},{1,2,4,3},{2}}" 문자열을 백터(vt)에 문자열 처리를 해서 저장하면 백터에 똑같이 저장합니다. 이 과정은 1번 각 튜플을 백터에 넣는것과 같습니다.
{{1,2,3},{2,1},{1,2,4,3},{2}} 
백터를 사이즈크기 오름차순으로 정렬합니다.
{{2},{2,1},{1,2,3},{1,2,4,3}}
튜플을 처음부터 탐색합니다.
{2} -> 2, 방문안했습니다. 정답에 추가후 방문표시를 합니다.
{2,1} -> 2, 방문했습니다. 통과합니다. 1, 방문하지 않았습니다, 정답에 추가후 방문표시를 합니다.
{1,2,3} -> 1, 방문했습니다. 통과합니다. 2, 방문했습니다. 통과합니다. 3, 방문하지 않았습니다, 정답에 추가후 방문표시 합니다.
{1,2,4,3} -> 1, 방문했습니다. 통과합니다. 2, 방문했습니다. 통과합니다. 4, 방문하지 않았습니다, 정답에 추가후 방문표시 합니다. 3, 방문했습니다. 통과합니다.
정답 {2,1,3,4}
**4**
후기
카카오문제는 문자열이 많아서 C++로 풀기 좀 …
> [level02] 튜플&올바른 괄호&쿼드압축 후 개수 세기

- LeetCode/Array/3Sum/HyeonJeong.py
[https://leetcode.com/problems/3sum/submissions/](url)
ex) Input: `nums` = [-1,0,1,2,-1,-4] -> Output: [[-1,-1,2],[-1,0,1]]
주어진 `nums`배열의 요소 3개(a,b,c)를 뽑았을 때, 합쳐서 0이 되는 경우는 [a,b,c]로 만들어 리스트에 넣어서 반환하는 문제
3중 for문으로 3개의 요소를 전부 받아와서 합치면 0이 될 수 있는지 확인하게 하였고, 맞는 경우에 slist에 저장하게 하였습니다. 같은 숫자도 `nums`에 존재할 수 있기 때문에 *이중 for문을 통해서 같은 a,b,c를 가지지 않게 구성하였습니다. * 부분에서 제가 보기에는 잘 돌아가야 하는데, 오류가 발생합니다. 어디가 문제인가요?
> [LeetCode] 3Sum

- programmers/난이도별/level02.다리를_지나는_트럭/6047198844.cpp
**1**
출처 : 프로그래머스
https://programmers.co.kr/learn/courses/30/lessons/42583
**2**
input : 다리의 길이 , 다리가 견딜수있는 무게, 트럭의 무게 
**3**
풀이 아이디어
대기트럭은 queue로 표현하고  다리를 건너는 트럭은 deque로 표현했습니다.
queue에 우선 모든 대기트럭을 넣습니다.
만약에 다리가 무게를 지탱할수있다면 트럭을 운송합니다.
아닐경우에 다리에 있는 트럭이 빠져나오게 트럭의 시간을 측정합니다. 이때 트럭의 시간은 다리에서 트럭이 어디있는지를 판단하게 합니다. 만일 트럭의 시간이 다리의 길이와 같을경우에는 트럭을 빠져나오게합니다.
전체 시간을 측정하고 , 그 시간을 반환합니다.
> [Level2] 다리를 지나는 트럭

- LeetCode/Math/Reverse_Integer/HyeonJeong.py
[https://leetcode.com/problems/reverse-integer/](url)
Input: x = -123 -> Output: -321
숫자를 역순으로 해서 [-2**31, 2**31 - 1] 범위 내인 수를 리턴하는 문제입니다.
우선 음수인지 확인해서 문자로 만들어서 역순으로 숫자가 저장되게 만드는데, 음수인 경우는 -를 제외하고 역순이 되게 하였습니다.
다음으로 숫자가 맨 앞은 0이 될 수 없는데, 이것은 문자를` int()`로 숫자로 만들면서 제거되는 것을 이용해서 해결하였습니다.
마지막으로 해당 범위인지 검사하고 범위 외의 숫자는 0을 리턴하게 하였습니다.
> [LeetCode] Reverse Integer

- programmers/난이도별/level01.두_정수_사이의_합/develop-sell.js
- programmers/난이도별/level01.수박수박수박수/develop-sell.js
삼항연산자를 활용해 최대한 코드를 줄여봤다.
재원님의 코드를 보고 '//'연산자를 이용하면 더 효율적임을 알게 되었다. 
'//'연산자는 나누기 연산 후 소수점 이하의 수를 버리고, 정수 부분의 수만 구함
> [Programmers Lv.1] 수박수박수박수 (watermelon problem)

- LeetCode/DFS/Course_Schedule_II/JeongShin.js
https://leetcode.com/problems/course-schedule-ii/
전에 풀이 했던 문제에서 @sAp00n 님이 추천해주신 위상 정렬 문제를 풀어보려고 찾아보다가 
위상 정렬 알고리즘 중 하나인 Kahn’s algorithm 으로 다시 풀이해보았습니다. 
위상 정렬 알고리즘에 대한 유튜브를 찾아보고서 이런 문제가 위상 정렬이라는 알고리즘으로 풀이하는 (정형화 된?) 방법이 있단걸 알았습니다. 
기존 방법은 dfs 알고리즘에 visited 정보를 이용하여 풀이한 반면 이번 풀이는 bfs 를 응용한 위상 정렬 풀이 입니다.
> [DFS] Course Schedule II 풀이

- programmers/난이도별/level02.최댓값과_최솟값/6047198844.cpp
- programmers/난이도별/level02.최솟값만들기/6047198844.cpp
- programmers/난이도별/level02.폰켓몬/6047198844.cpp
- programmers/난이도별/level02.행렬의곱셈/6047198844.cpp
- programmers/난이도별/level02/숫자의_표현/6047198844.cpp
최댓값과 최소값
**1**
출처 : 프로그래머스
https://programmers.co.kr/learn/courses/30/lessons/12939
**2**
input : 문자열
output : 최솟값 / 최댓값
**3**
풀이 아이디어
주어진 문자열을 토크나이저를 이용. 띄어쓰기를 기준으로 잘라냄.
잘라낸 정수들을 배열에 넣고 정렬. -> 최댓값 최소값 알아낼수있다.
최소값 만들기
**1**
출처 : 프로그래머스
https://programmers.co.kr/learn/courses/30/lessons/12941
**2**
input : 두개의 백터
output : 최소곱
**3**
풀이 아이디어
그리디 알고리즘
가장 작은 값과 가장 큰 값의 곱이 최소값을 만들수있다.
폰켓몬
**1**
출처 : 프로그래머스
https://programmers.co.kr/learn/courses/30/lessons/1845
**2**
input : 폰켓몬의 종류 번호
output : 가장 많은 종류의 폰켓몬을 선택하는 방법
**3**
풀이 아이디어
폰켓몬의 종류의 크기를 구한다.
해당 크기가 N/2보다 작다면 폰켓몬 종류의 크기가 정답.
크다면 N/2이 정답. (최대 N/2뽑을수있기때문에 종류도 N/2뽑을수있다.)
행렬의 곱셈
**1**
출처 : 프로그래머스
https://programmers.co.kr/learn/courses/30/lessons/12949
**2**
input : 두개의 행렬
output : 두개의 행렬 곱셈 값
**3**
풀이 아이디어
행렬의 곱셈을 그대로 구현.
숫자의 표현
**1**
출처 : …
> [Level02]최댓값과_최소값&최솟값_만들기&폰켓몬&행렬의_곱셈&숫자의_표현

- LeetCode/Math/Add_Binary/HyeonJeong.py
- LeetCode/Math/Sqrt(x)/HyeonJeong.py
Add Binary
2진수 형태의 문자열 두 개가 주어지면 두 수를 합쳐서 2진수로 반환(0b 없이)하는 문제
-> `int(문자열, 2)`를 이용해서 두 숫자가 2진수로 읽어져서 더해진 후 10진수를 `sum`에 저장되게 하고, `sum`에 `bin()`를 해서 이진수 문자열로 바꾸고 슬라이싱을 이용해서 앞의 0b제외후 반환하게 만들었습니다.
Sqrt(x)
해당 정수를 받아서 제곱근을 구하고, 제곱근이 정수가 아닌 경우는 내림을 하는 문제
-> `sqrt()`를 이용해서 제곱근을 구하고, `n != int(n)`를 통해서 정수인지 확인 후 아닌 경우는 내리고, 맞는 경우에는 int형으로 반환(`sqrt()`는 실수로 반환)하게 만들었습니다.
> [LeetCode] Add Binary & Sqrt(x)

- programmers/난이도별/level02/H_Index/6047198844.cpp
**1**
출처 : 프로그래머스
https://programmers.co.kr/learn/courses/30/lessons/42747
**2**
input : 논문 인용 횟수
output : H-Index
**3**
풀이 아이디어
정렬을 먼저합니다. H-index의 범위는 0부터 ~ length까지입니다.
lower_bound를 이용합니다. h를 0부터 ~ length까지 증가시키면서 H-index인지 아닌지 판단합니다.
예를 들면
3, 0, 6, 1, 5 일경우
정렬을 먼저합니다.
0, 1, 3, 5, 6
5편의 논문이 0편 이상 인용되었습니다. lower_bound가 0번째 인덱스를 가르키므로 length - lower_bound의 index => 5
4편의 논문이 1편 이상 인용되었습니다. lower_bound가 1번째 인덱스를 가르키므로 length - lower_bound의 index => 4
3편의 논문이 2편 이상 인용되었습니다. lower_bound가 2번째 인덱스를 가르키므로 length - lower_bound의 index => 3
3편의 논문이 3편 이상 인용되었습니다. lower_bound가 3번째 인덱스를 가르키므로 length - lower_bound의 index => 3
2편의 논문이 4편 이상 인용되었습니다. lower_bound가 4번째 인덱스를 가르키므로 length - lower_bound의 index => 2
--> H인덱스가 아님. 따라서 이전의 값 '3편이상 인용되었다'가 H-index가 된다.
> [Level02] H-index

- LeetCode/Two_Pointers/Sort_Colors/JeongShin.js
https://leetcode.com/problems/sort-colors/
```js
[2,0,2,1,1,0]
```
다음과 같이 0, 1, 2 로 이루어 진 수를 정렬하는 문제 입니다. 
정렬 알고리즘 n*log(n) 을 사용하지 않고 
시간 복잡도 N 
공간 복잡도 1 로 풀이 하는 문제 입니다. 
쉬운 문제인 줄 알았는데 응근 까다롭더라고요.. 
left, right 로 인덱스를 따져서 pointer 변수로 0일 경우 왼쪽 2일 경우 오른쪽으로 바꿔가는 방식으로 풀이했습니다.
> [two pointers] sort colors 풀이

- LeetCode/String/Length_of_Last_Word/HyeonJeong.py
- LeetCode/String/ZigZag_Conversion/HyeonJeong.py
[https://leetcode.com/problems/length-of-last-word/](url)
Input: s = "Hello World" -> Output: 5
공백으로 구분된 단어가 들어간 문자열s에서 마지막 단어의 길이를 반환하는 문제
-> 문자열의 맨 끝에 ' '이 있을 경우에는 제거하고, 해당 문자열을 리스트로 만들었습니다. 그리고 reverse()를 이용하여 뒤에서 부터 문자를 읽을 수 있게 하여 for문에서 ' '가 나올때 까지 숫자가 계산되게 하였습니다.
> [LeetCode] Length of Last Word

- programmers/난이도별/level01.문자열 다루기 기본/develop-sell.js
맨 마지막에 return false를 주는 것. 만약 안 주면 undefined가 나온다..!! 
// 코드를 보다보니 조건이 있는것들은 미리미리 없애주는게 좋아보인다
// 이 경우 4, 6이 아니면 바로 return false를 해주는 것이다. 
//아래는 새롭게 짠 코드 
function solution(s) {
let answer = false;
//먼저 길이가 4, 6인지 체크한다 (아니면 return false)
if (s.length !== 4 && s.length !== 6)
return false;
// for each문으로 바로 char값을 확인한다 (chatAt 쓸 필요 없도록)  
for (const char of s) {
if (isNaN(char * 1))
return false;
}
return true;
}
배운 것 : isNan(값) => 숫자인지, 아닌지 확인해줌
> [Programmers Lv1.] 문자열 다루기 기본 basic_string_problem

- programmers/난이도별/level02.N개의 최소공배수/6047198844.cpp
- programmers/난이도별/level02.가장_큰_수/6047198844.cpp
- programmers/난이도별/level02.다음_큰_숫자/6047198844.cpp
- programmers/난이도별/level02.멀쩡한_사각형/6047198844.cpp
- programmers/난이도별/level02.소수_만들기/6047198844.cpp
- programmers/난이도별/level02.짝지어_제거하기/6047198844.cpp
- programmers/난이도별/level02/JadenCase_문자열_만들기/6047198844.cpp
N개의 최소공배수
**1**
출처 : 프로그래머스
https://programmers.co.kr/learn/courses/30/lessons/12953
**2**
input : n개의 숫자를 담은 배열
output :  최소공배수
**3**
풀이 아이디어
n개의 숫자에서 공통이 되는 소수부분중 가장 갯수가 많은 소수부분만 추출해서 곱합니다. 예를 들면,
2, 6, 8, 14이면
2부터 검사하면 -> 2 소수 1개 
6 -> 2,소수(1개) 3,소수(1개)
8 -> 2,소수(3개)
14 -> 2,소수(1개) 7,소수(1개)
따라서 2, 소수(3개) / 3,소수(1개) / 7,소수(1개) 입니다.
다 곱하면 168.
**4**
후기 : 좀 특이하게 풀었습니다. 원소하나하나씩 최소공배수를 만들어가도 됩니다.
가장 큰 수
**1**
출처 : 프로그래머스
**2**
input : 양의 정수가 담긴 배열
output :  가장 큰수
**3**
풀이 아이디어
정렬을 이용했는데요. 핵심은 제가 정렬을 직접 정의해서 사용한것입니다. 
(a+b) > (b+a)로 정의 했습니다.
예를 들면 [6,10,2]가 주어진다면, 610 > 106 true , 102 > 210 false, 62 > 26 true 이므로
6,2,10 으로 정렬됩니다. 정렬된걸 처음부터 그냥 더해주면 됩니다. 
6210이 정답입니다.
**4**
후기 : 이 문제는 그냥 정렬하면 안됩니다. 꼭 정렬을 정의해야합니다. 그래야 2번 케이스를 통과가능합니다. 그냥 기본정렬하게되면 [3 , 30, 34]의 경우 [34,30,3] -> 34303이 되는데 이건 정답이 …
> [level02] N개의 최소공배수 / 가장 큰 수 / 다음 큰 숫자 / 멀쩡한 사각형 / 소수 만들기 / JadenCase 문자열 만들기

- programmers/난이도별/level01.가운데_글자_가져오기/develop-sell.js
원리:
- 홀수, 짝수 분기 처리해서 진행했습니다.
- isOdd가 true면 홀수, 아니면 짝수입니다
- 홀수의 경우 가운데 1자만 빼고, 짝수는 2자를 빼게 됩니다. 
헷갈린점:
1. 
- 네이밍에서 isOdd로 했는데, 말 그래도 Odd(홀수)인지를 묻는 걸로 네이밍했으면 그렇게 믿어야함
- 즉, isOdd가 true면 홀수이고, 아니면 짝수인건데 반대로 생각하고 있었다 
2. 
- 홀수에서 s.length와 i가 같을 때 return s.charAt(i) 가운데 한 글자만 빼려고 했는데
- s.length / 2 가 처음에 몫만 나오는 줄 알았는데, js는 저절로 형변환을 해서 소수점이 나오게 된다
- ex. 5 -> 2.5가 나옴!! (c언어는 안 그랬던거 같은데... 아닌가? )
- 자동 형변환 잘 확인할 것 ! 
다른 사람 코드 참고 (eyabc.js)
const middle = s.length / 2;
const floor = ~~middle;
return (Number.isInteger(middle) ? s[floor - 1] : '') + s[floor];
정확히 반 나눈 middle(소수점 포함 값)이 int가 아니면 홀수니까 s[floor]만
짝수면 s[floor - 1] + s[floor] 로 return 한다
double tilde( ~~ ) 연산자 : Math.floor() 연산자와 비슷하다 => "내림" 같은 표현 (소수점 없애는)
참고자료 : https://dreamyoungs.github.io/js/tilde-and-double-tilde-operator
느낀점: 
애초에 …
> [Programmers Lv.1] 가운데_글자_가져오기 (middle_string_problem)

- programmers/난이도별/level02.n진수_게임/sangmandu.py
- programmers/난이도별/level02.압축/sangmandu.py
- programmers/난이도별/level02.오픈채팅방/sangmandu.py
- programmers/난이도별/level02.캐시/sangmandu.py
- programmers/난이도별/level02.후보키/sangmandu.py
> [level02] n진수 게임, 압축, 오픈채팅방, 캐시, 후보키

- programmers/난이도별/level01.K번째수/develop-sell.js
>문제풀이방법
slice함수를 통해 배열의 일부분을 선택하여 새로운 배열로 만들었다.
그 후 sort함수로 정렬을 해주고 
그 안에서 k번째 숫자를 찾아 배열에 push해주면 된다. 
>헷갈린점
1. 문제에서 2번쨰 ~ 5번째라고 했지만, 실제 배열에선 [1] , [4] 였다. 
-> console.log()를 통해 편하게 알 수 있었다! 
2. sort함수 , 뒤에 sortFunction도 넣어줘야한다
-> 아무것도 안 넣으면 배열 각 요소를 문자열로 변환하고 유니코드값에 따라 정렬한다. 
-> 즉, 여기선 숫자를 또 문자열로 변환해서 유니코드값에 따라 정렬하기 때문에 어떤 경우는 문제가 될 수 있었다
-> 따라서 숫자 배열을 정렬할 때는 반드시 함수 "(a, b) => a - b" 를 넣어준다(오름차순)
출처: https://fluorite94.tistory.com/220
3. array(배열)은 push 함수를 통해 넣는다! "+=" 이건 string의 경우에 사용! 
junihwang.js 참고 
return commands.map(([i, j, k]) => array.slice(i-1, j).sort((a, b) => a- b)[k-1])
코드 보고 감탄했네요..!
map은 배열에 접근해 각 요소들에게 행한 값들을 따로 배열로 만드는 것이다. 
이 경우 2차원 배열에 접근해 각 [0],[1],[2]를 i,j,k로 명칭하고
각각 i,j,k를 용도에 맞게 사용해서 나오는 값들을 따로 배열로 만들어주는, 이 문제에 아주 적합한 용도이다.
> [Lv.1] K번째 수 (k_number_problem)

- programmers/난이도별/level02.캐시/6047198844.cpp
**1**
출처 : 프로그래머스
https://programmers.co.kr/learn/courses/30/lessons/17680
**2**
input : 캐시 크기 / 도시 이름
output : 실행시간
**3**
풀이 아이디어
대소문자를 가리지 않으므로, 우선 ㅜ문자열을 소문자로 모두 변경해줍니다.
cache size가 0일 경우는 무조건 실행시간이 5*도시개수이므로 바로 반환합니다.
cache_map에는 cache에 해당 스트링이 존재하는지 존재안하는지가 저장됩니다. 존재한다면 value값으로 해당 string이 저장되어 있는 cache위치를 가집니다.
cache는 도시를 저장합니다. queue형식으로 관리됩니다.
if(캐쉬에 존재하지 않는다면,){
if(캐쉬가 가득 찻다면,){
cache마지막에 존재하는 값을 pop한다(최근에 가장 적게 쓰인 값
cache_map에서도 해당값을 없엔다.
}
시간 += 5; // cache miss이므로.
}
if(캐쉬에 존재한다면,){
cache_map의 value를 참고하여 캐쉬에 있는 값을 찾아서 지웁니다. (어쩌피 아래에서 cache의 맨앞에 추 가됩니다)
시간 += 1 // cache hit이므로.
}
주어진 도시를 캐쉬의 맨앞에 push합니다.
해당 cache의 주소를 cache_map에 넣습니다.
**4**
후기
cache로 문제를 내니까 신기하네요.
그리고 unordered_map은 처음써보네요. 그리고 value값을 이터레이터를 활용해서 다룰수있다는것을 배웠습니다.
> [level2]캐시

- programmers/난이도별/level02.튜플/sjjyy.java
- programmers/난이도별/level02.폰켓몬/sjjyy.java
브랜치를 만들었는데 잘못 커밋해서 문제가 각각 pr 되지 않고 합쳐서 올라가네요 😅
> [level02] 폰켓몬

- programmers/난이도별/level02.오픈채팅방/6047198844.cpp
**1**
출처 : 프로그래머스
https://programmers.co.kr/learn/courses/30/lessons/42888
**2**
input : 채팅창
output :  최종 채팅창
**3**
풀이 아이디어
Enter과 Leave만 따로 백터에 {"ID" , 명령어"} 형식으로 저장합니다.
Enter과 Change는 map을 변화시킵니다. 
해당 명령어는 Key(ID)에 해당하는 Value(닉네임)을 변경시킵니다.
백터에 저장된 string들을 변역해주면됩니다. 위에서 가장 최근의 변경사항이 최종 변경사항이 됩니다. map의 ID에 해당되는 닉네임을 찾아넣기만 하면됩니다.
**4**
코드가 이쁘지 않네요..
> [Level02]오픈채팅방

- programmers/난이도별/level03.2xn타일링/sangmandu.py
- programmers/난이도별/level03.N으로_표현/sangmandu.py
> [level03] 2 x n 타일링, N으로 표현

- programmers/난이도별/level03.2xn타일링/6047198844.cpp
**1**
출처 : 프로그래머스
https://programmers.co.kr/learn/courses/30/lessons/12900
**2**
input : 타일의 길이
output : 경우의 수
**3**
길이가 N인 전체 경우의수는 두가지 경우의 수로 나누어 볼 수 있습니다.
N-1의 경우와
N-2의 경우의 합이라고 볼수있습니다.
이외의 경우는 모두 N-1의 경우의수와 N-2의 경우의수에 포함됩니다.
따라서 dp(n) = dp(n-1) + dp(n-2)라고 볼수있습니다.
dp(n)의 정의는 길이 n 일때의 경우의 수입니다.
dp(0)인 경우는 '아무것도 존재하지 않는 경우'로 판단하여 1을 넣었습니다.
n이 음수인 경우는 '처음부터 존재하지 않는 경우'로 판단하여 0을 반환합니다.
**4**
기말도 있고 취업시즌이라 여러가지 생각이 많아 요즘 게을렀네요. 열심히 하겠습니다.
> [Level03]2xn타일링

- programmers/난이도별/level02.[1차]_프렌즈4블록/6047198844.cpp
- programmers/난이도별/level03.2xn타일링/.vscode/launch.json
**1**
출처 : 프로그래머스
https://programmers.co.kr/learn/courses/30/lessons/17679
**2**
input : 프랜즈4블록
output : 제거된 블록의 수
**3**
풀이 과정
column단위로 뽑아서 다시 board를 재정의하고,
위에서 부터 지우고 위는 ' '으로 채웠습니다. 아래서부터 지우면 안됩니다. 보드가 이상해집니다.
**4**
후기
카카오는 까다롭네요
> [Level02][1차]_프렌즈4블록

- LeetCode/Array/Remove_Duplicates_from_Sorted_Array/HyeonJeong.py
오름차순으로 정렬된 주어진 리스트를 중복된 값을 제거하는 문제(다른 배열에 추가 공간을 할당하지 않게 해야 함)
while문을 통해서 주어진 리스트의 값을 다 가져올 수 있게 했습니다.
그리고 중복된 값이 있으면 뒤의 값을 없애고, 당겨진 인덱스 비교가 될 수 있게 만들었습니다.
> [LeetCode] Remove Duplicates from Sorted Array

- programmers/난이도별/level02.[3차]_방금_그곡/6047198844.cpp
- programmers/난이도별/level02.후보키/6047198844.cpp
[3차]_방금_그곡
**1**
출처 : 프로그래머스
https://programmers.co.kr/learn/courses/30/lessons/17683
**2**
input : 기억하는 멜로디 , 방송된 곡의 정보
output :  조건과 일치하는 음악제목
**3**
풀이 아이디어
토큰으로 다 잘라서 비교합니다.
핵심아이디어는 #을 가지는 경우에는 한글자로 줄이는 과정이 필요합니다.
예를 들면 C#을 c로 바꾸는 과정이 필요합니다.
"12:00,12:14,cdcdf,cdcdcdf"의 경우도 유심히 볼 필요가있습니다. 
다음의 조건을 조심합시다.
- 조건이 일치하는 음악이 여러 개일 때에는 라디오에서 재생된 시간이 제일 긴 음악 제목을 반환한다. 재생된 시간도 같을 경우 먼저 입력된 음악 제목을 반환한다.
- 조건이 일치하는 음악이 없을 때에는 `(None)`을 반환한다.
-'(None)'이 아니고 (None)입니다.
후보키
**1**
출처 : 프로그래머스
https://programmers.co.kr/learn/courses/30/lessons/42890
**2**
input : 릴레이션
output : 후보키개수
**3**
풀이 아이디어
col을 검사합니다.
if(고른 col이 후보키에 포함됩니다) --> 최소성의 원칙 위배
return 0;
if(후보키입니다) --> 유일성 만족하는지 검사
후보키를 만드는 column을 저장합니다. 
후보키를 먼저 검사합니다. 검사 길이는 1부터  column의 갯수만큼 검사합니다.
예제를 예시로 들면
학번 / 이름 / 전공 / 학년이 있습니다.
검사길이 1을 …
> [Level2]_[3차]_방금_그곡, [Level2]후보키

- programmers/난이도별/level02.[3차]파일명_정렬/6047198844.cpp
- programmers/난이도별/level02.단체사진_찍기/6047198844.cpp
**1**
출처 : 프로그래머스
https://programmers.co.kr/learn/courses/30/lessons/1835
**2**
input : 조건의갯수, 조건
output : 조건을 만족하는 문자열
**3**
풀이 아이디어
스트링에 대해서 모든 정렬을 다한뒤. 각각의 정렬에 대해서 조건에 맞는지 확인하기만 하면됩니다. 쉬운문제입니다.
**4**
후기
참고 : https://velog.io/@woga1999/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4-%EB%8B%A8%EC%B2%B4%EC%82%AC%EC%A7%84-%EC%B0%8D%EA%B8%B0
계속 고민고민하다가 어떻게 풀어야할지몰라서 답을 봤는데 허무하네요. Brute force로 그냥 풀리는 문제였다니.. 카카오 문제라서 괜히 어렵게 생각했나봅니다.
**1**
출처 : 프로그래머스
https://programmers.co.kr/learn/courses/30/lessons/17686
**2**
input : 파일명
output : 정렬된 파일명
**3**
풀이 아이디어
몇가지 관계를 만족해야합니다.
-대소문자 관계없습니다. -> 모두 소문자로 변경
-앞에 붙은 0은 정렬과 관계없습니다. -> string을 int로 변경함으로써 앞에 있는 0이 자동으로 없어짐
-HEAD의 알파벳 순으로 정렬함 
-HEAD가 같을경우 NUMBER의 순으로 정렬함
-다 같을 경우 들어온 순서대로 정렬
주어진 문자를 HEAD / NUMBER로 나눕니다. TAIL은 정렬과는 무관하니 버려도 상관없습니다. …
> [Level02]단체사진_찍기 / [3차]파일명_정렬

- programmers/난이도별/level01.서울에서_김서방_찾기/develop-sell.js
문제 풀이: 
처음에는 배열의 길이보다 작은 배열을 뽑기 때문에 
index를 빼기 위해 기존의 filter라는 함수를 쓰려고 했다. 
그러다가 filter 함수는 요소(배열의 원소) 내용을 
바꿀 수 없다는 것을 알게 되었다. 
그래서 고민하다가 구글링을 통해 findIndex라는 함수를 알게 되어
사용해서 풀게 되었다.
배운점: 
console.log(seoul.indexOf('Kim'))
indexOf 라는 함수도 동일한 역할을 한다. 
console.log(seoul.filter((i) => i ==="Kim"))
filter는 이런 경우 사용 용도가 불분명하다.
filter는 string의 가운데 값이 뭐인 경우만 뺄 때, 
혹은 int값이 뭐보다 크거나 작은 경우 , 뺄 때 사용한다
> [Programmers Lv.1] 서울에서 김서방 찾기 (find_kim_from_array)

- programmers/난이도별/level02.수식_최대화/6047198844.cpp
**1**
출처 : 프로그래머스
https://programmers.co.kr/learn/courses/30/lessons/67257
**2**
input : 수식
output : 수식 최대값
**3**
풀이 아이디어
완전탐색으로 풀었습니다.
*+-을 정렬하는 수는 6!입니다.
문자열의 길이가 최대 100이므로 1억은 어림잡아도 안나옵니다. 크게잡아서 100길이 연산을 100번해도 10000밖에 안됩니다.
10000*6! <<<< 1억이므로 1초 내에 가능합니다. 따라서 완전탐색으로 구현했습니다.
주의할점은 *+-의 아스키코드입니다. 아스키 코드순 * < + < - 인 오름차순이기떄문에 next_permutation을 사용할때 순열의 초기값으로 *+-을 주어야합니다.
**4**
후기
마지막 Level2 문제였네요
> [Leve02]수식_최대화

- programmers/난이도별/level03.네트워크/6047198844.cpp
**1**
출처 : 프로그래머스
https://programmers.co.kr/learn/courses/30/lessons/43162
**2**
input :  컴퓨터의 연결개수 / 컴퓨터의 연결 현황
output : 네트워크의 개수
**3**
풀이 아이디어
DFS로 풀었습니다. 이어진 간선의 개수가 몇개인지 묻는것같았습니다.
> [level03]네트워크

- programmers/난이도별/level01.키패드 누르기/6047198844.cpp
**1**
출처 : 프로그래머스
https://programmers.co.kr/learn/courses/30/lessons/67256
**2**
input : 키패드명령
output : 사용한 손의 순서
**3**
풀이 아이디어
1  2  3
4  5  6
7  8  9
10 11 12
0을 11로 표현하여 거리 재는것이 관건
거리 = 절댓값(차이)/3 + 절댓값(차이)%3
거리를 비교하여 정답을 구하면 됨
**4**
후기
Level1이긴 한데 약간의 아이디어가 팔요하네요
> [Level01]키패드 누르기

- programmers/난이도별/level01.3진법_뒤집기/develop-sell.js
문제풀이:
먼저 무한루프를 돌면서 3의 n제곱으로 나뉘는 값이 1,2인 경우의 n값을 구한다
여기서 n값은 big이고, big부터 0까지 계속 값을 나눈다.
먼저 (3의 n제곱 * 2)으로 나뉘는지 보고 나눠지면 '2'를 arr에 푸시한다
그 다음 3의 n제곱으로 나눠지는지 보고 나눠지면 '1'를 arr에 푸시한다 
마지막으로는 '0'를 푸시한다
그 후 array를 reverse해주고 
array의 사이즈 -1 만큼 돌면서 3의 n제곱을 하나씩 줄면서 answer에 값에 더해준다. 
헷갈린 점 / 어려운 점:
1. for문 감소문
- for(let i = 10 ; i > 0; i--)  => 감소문의 가운데 조건은 부등호가 '>'로 바꿔야하는데, 계속 헤맸다.
2. 3진법은 0,1,2까지 있다는 점
- 2까지 있다는 것을 뒤늦게 캐치해서 경우를 추가해줬다! (처음엔 0,1만 있는줄 알았다)
배운점:
1. arr는 reverse()라는 함수가 있다! str는 따로 없으니 참고
2. forEach문도 array의 한 함수로 취급!! 다음에 짤 때 참고
3. Math.pow(n, m) => n의 m제곱 !! 
참고풀이:
(1)
n = n.toString(3).split('').reverse().join('')
return parseInt(n, 3)
toString(n)으로 10진법 => n진법으로 변경
split('')으로 str 한 문자씩 저장한 배열 리턴 
join('')으로 배열을 str으로 붙여서 리턴 
parseInt(n, 3) n진법 => 10진법으로 변경 
(2)
return …
> [Programmers Lv.1] 3진법 뒤집기 ternary_problem

- programmers/난이도별/level01.크레인_인형뽑기_게임/6047198844.cpp
**1**
출처 : 프로그래머스
https://programmers.co.kr/learn/courses/30/lessons/64061
**2**
input : board
output : 제거된 인형수
**3**
풀이 아이디어
스택을 이용해서 풀었습니다.
> [Level01]크레인_인형뽑기_게임

- programmers/난이도별/level01.완주하지_못한_선수/develop-sell.js
문제 풀이: 
효율성 문제 때문에 최대한 이중 for문을 안 사용하려고 고민을 많이 했다. 
그러나 해결하기 어려워서, 우선 sort함수로 순서를 맞춰주면 비교적
괜찮을 것 같아보였다. 
그래도 해결이 안되어서 length 함수를 계속 호출하지 않도록 밖으로 뺐다.
그래도 해결이 안되어서 고민하다 
eyabc.js 님의 풀이를 참고했다. 
sort를 하면 순서대로 짜지기 때문에 달라지는 순번의 요소가 정답이었다. 
participant와 completion의 길이 차이가 -1이기 때문. 
배운 점: 
for문을 줄이는 연습을 더 해보자..!
> [Programmers Lv.1] 완주하지 못한 선수 not_finished_runner

- BOJ/2659.십자카드 문제/6047198844.cpp
- BOJ/2668.숫자 고르기/6047198844.cpp
- BOJ/6800.Huffman Encoding/6047198844.cpp
Huffman Encoding
**1**
출처 : 백준
https://www.acmicpc.net/problem/6800
**2**
input : huffman code , encoded code
output : decoded code
**3**
풀이 아이디어
huffman code는 유일합니다. 또한 각각의 code중 한 code가 길다고 해서 짧은 코드를 포함하지 않습니다.
예를 들면 , 110 : A / 11 : B 같은 경우는 없다는 뜻입니다. 따라서 key-value값이 유일합니다. map을 사용해서 변환하였습니다.
숫자 고르기
**1**
출처 : 백준
https://www.acmicpc.net/problem/2668
**2**
input : 표에 들어가는 정수
output : 조건을 만족하는 정수를 최대한 많이 뽑는 수
**3**
풀이 아이디어
원소들에 대해서 cycle을 찾습니다.
십자 카드문제
**1**
출처 : 백준
https://www.acmicpc.net/problem/2659
**2**
input : 십자카드
output : 시계수
**3**
풀이 아이디어
완전탐색으로 시뮬레이션 한뒤에 시계수를 알아냅니다.
> [해시]Huffman Encoding&[map]숫자 고르기

- programmers/난이도별/level01.제일_작은_수_제거하기/develop-sell.js
문제풀이:
예전에 처음 프로그래밍 배울 때 풀던 문제 같다
min값을 갖고 있는 index를 구하고,
그 위치의 요소를 찾아 없애는 방식이다.
한줄 풀이:
arr.splice(arr.indexOf(Math.min(...arr)),1);
Math.min 이라는 함수로 최소값을 구할 수 있고, 
이때 배열을 ... 로 빼낸 다음 실행해야 가능하다.
indexOf 함수로 해당 값을 찾아서 splice로 값을 없애준다. (min에 해당되는 index를 구하는 작업이 불필요)
> [Programmers Lv.1] 제일 작은 수 삭제하기 delete_smallest_num

- programmers/난이도별/level03.방문_길이/sangmandu.py
- programmers/난이도별/level03.여행경로/sangmandu.py
> [level03] 방문 길이, 여행경로

- LeetCode/Trie/Replace_Words/JeongShin.js
https://leetcode.com/problems/replace-words/
```js
sentence = 'the cattle was rattled by the battery'
dictionary = ['cat', 'bat', 'rat'];
result = 'the cat was rat by the bat'
```
와 같이 sentence 있을때 dictionary 에 있는 가장 짧은 string 으로 교체하는 문제 입니다.
Sentence 를 공백으로 잘라서 모든 단어를 Trie 자료구조를 이용하여 가장 짧은 단어를 찾아 교체 해준뒤 join 해주는 방식으로 풀이하였습니다.
> [Trie] Replace Words 풀이

- BOJ/11653.소인수분해/6047198844.cpp
- BOJ/1707.이분그래프/.vscode/launch.json
**1**
출처 : 백준
https://www.acmicpc.net/problem/11653
**2**
input : 정수
output : 소인수
**3**
풀이 알고리즘
에라토스테네스의 채로 소수를 찾은뒤 해당 소수로 나눠지는지 확인합니다.
> [에라토스테네스의채]소인수분해

- BOJ/2651.자동차경주대회/2651_자동차경주대회.cpp
- BOJ/2669.직사각형 네개의 합집합의 면적 구하기/2669_직사각형 네개의 합집합의 면적 구하기.cpp
**1**
출처 : 백준
https://www.acmicpc.net/problem/2669
**2**
input : 직사각형의 좌측하단xy좌표, 직사각형의 우측상단xy좌표
output : 직사각형의 넓이
**3**
풀이 아이디어
좌표를 이차원 배열로 생각하고 각 직사각형마다 1로 채운뒤 1의 갯수를 새었습니다.
**4**
질문
다른 사람 컴퓨터에서 계정 변경해서 commit 어떻게 하나요.. 여자친구 계정으로 commit됬네요. 
그리고 memset 부분을 없애면 틀렸습니다 나오는데 그이유도 궁금합니다
> [백준]직사각형 네개의 합집합의 면적 구하기 + 질문

- BOJ/1600.말이 되고픈 원숭이/6047198844.cpp
- BOJ/2468.안전 영역/6047198844.cpp
- BOJ/2606.바이러스/6047198844.cpp
말이 되고픈 원숭이
**1**
출처 : 백준
https://www.acmicpc.net/problem/1600
**2**
input : 말로 움직일수있는 수 , 가로길이, 세로길이
output : 원숭이 동작수의 최소값
**3**
풀이 아이디어
편하게 생각해서 틀렸었는데요. 0,1로 단순하게 생각하면 안됩니다. 사실
1
4 4
0 0 1 1
0 0 1 1
0 0 1 1
1 1 1 0
입력값이 위와 같은 경우에 한번의 탐색이 끝나면
0 1 1 1
1 0 1 1
0 1 1 1
1 1 1 0
이렇게 될탠데요. 이렇게되면 0으로 도달할수없게 됩니다. 하지만 초기값에서 오른쪽 -> 아래 -> 아래 -> 말로 움직여서 최종목적지가 가능합니다. 이경우를 생각하지못해서 질문게시판 반례를 참고했습니다. 차원을 하나 더 늘려주면 답이 나옵니다.
즉. 말을 한번 움직였을때의 판과, 말을 두번 움직였을때의 판을 따로 분리하여 생각해야합니다.
안전 영역
**1**
출처 : 백준
https://www.acmicpc.net/problem/2468
**2**
input : 어떤 지역을 나타내는 2차원 배열의 행과 열의 개수를 나타내는 수 N , 지역높이정보
output : 장마철에 물에 잠기지 않는 안전한 영역의 최대 개수
**3**
풀이 아이디어
0부터 K높이까지 물을 부어가면서 잠기지 않은 부분에 대해서 BFS를 수행하여 갯수를 샙니다. 
바이러스
**1**
출처 : 백준
https://www.acmicpc.net/problem/2606
**2**
input : 간선
output : 컴퓨터 1과 연결된 컴퓨터의 수
**3**
풀이 …
> [BFS]말이 되고픈 원숭이,안전 영역,바이러스

- programmers/난이도별/level01.약수의_합/develop-sell.js
문제풀이: 
약수를 구해서 배열에 넣고 해당 배열의 합을 구하는 식으로 구현했다.
지난번 풀었던 문제 중 약수를 구할 때 Math.sqrt()까지 진행해도 약수를 구할 수 있음을 알고
이 문제에 적용시켰다. 
알게된 점: 
배열을 굳이 만들 필요 없이 바로 sum이라는 integer형 변수에 더하면 더 효율적이었을 것 같다. 
reduce 함수를 통해 배열의 합을 구할 수 있다. 
arr.reduce((sum, num) => sum + num, 0); => num은 배열 요소, sum은 최종 합
> [Programmers Lv.1] 약수의 합 factor_num

- programmers/난이도별/level01.시저_암호/develop-sell.js
문제풀이:
먼저 split함수로 str을 배열로 만들고, 
배열을 forEach문으로 돌면서 n값만큼 더해준 값을 다시 ans_arr에 push하고,
ans_arr를 join함수로 다시 str로 바꿔서 제출한다. 
사용한 함수:
char.charCodeAt(0): 영문자인 char를 숫자로 바꿔주는 함수
String.fromCharCode(num): 숫자인 num을 영문자로 바꿔주는 함수 
알게된 점:
1. str함수인 split를 통해 str를 배열로 만들기 
2. forEach문은 continue문이 안 먹힌다.. return문 사용해야 함
3. array함수인 join을 통해 배열의 모든 요소의 병합을 str로 바꿔준다
> [Programmers Lv.1] 시저 암호 Caesar_cipher

- BOJ/2747.피보나치 수/6047198844.cpp
**1**
출처 : 백준
https://www.acmicpc.net/problem/2747
**2**
input : n
output : 피보나치 수
**3**
풀이 아이디어
DP를 이용해 풉니다. 작은 문제와 큰 문제가 같다는 사실을 이용합니다.
> [DP]피보나치의 수

- programmers/난이도별/level01.이상한_문자_만들기/develop-sell.js
변수 설명:
arr : 단어별 Array
str : 단어, string 값. (ex. try)
char : 단어의 한 글자 (ex. try의 t)
index : 단어마다 나타나는 index값 (단어마다 새로고침된다)
문제풀이: 
배열을 공백 기준으로 나누고, map함수를 통해 각각 단어별로 접근하게 한다. 
다시 split함수로 단어를 char별로 나누고, 이를 map함수를 통해
index가 짝수(0 포함)면 대문자, 아니면 소문자로 변환해서 return한다.
그렇게 변환된 str를 다시 join하면 단어별 배열이 되고,
다시 join를 ' ' 빈칸 기준으로 하면 해당 string 값이 나온다 
어려웠던 점:
1.처음에 단어(공백을 기준)이 무슨 말인지 잘 이해가 안 갔다..! 
2.원래는 map함수 안에서는 forEach문으로 돌려서 받으려고 했는데, 
잘못된 판단이었다. 
이 문제에서 요구한 건 배열 안의 값을 변경한 배열을 가져오는 것인데, 
이때는 무조건 map함수를 쓴다. 
forEach는 배열의 요소에 접근하는 용도로만 사용할 때 쓴다. 즉 배열의 요소를 바꿀 때는 아니다. 
(접근해서 해당 값들을 다른 식에 적용해야할 때 사용)
잘 확인해둘 것! 
반드시 가져가야할 점: 
map, join, split 함수를 사용할 때, 함수가 적용된 객체를 다시 받는 변수를 둬야한다. 
(이것 때문에 시간 낭비를 많이 했다)
ex. str.split("") 그냥 이렇게만 하면 배열로 쪼개지지만, str이 그렇게 변경되는 것이 아니다. 
즉 str = str.split("") 이런식으로 받아주는 객체가 …
> [Programmers Lv.1] 이상한_문자_만들기 make_strange_number

- BOJ/11048.이동하기/6047198844.cpp
- BOJ/1890.점프/6047198844.cpp
점프
**1**
출처 : 백준
https://www.acmicpc.net/problem/1890
**2**
input : 게임판
output : 경로의 수
**3**
풀이 아이디어
현재 칸에서 갈수있는 경우의수 = 오른쪽 / 아래로 자신의 칸수만큼 이동한 경우의 수.
x,y좌표가 범위를 벗어날경우 0을 반환한다.
이동하기
**1**
출처 : 백준
https://www.acmicpc.net/problem/11048
**2**
input : 미로
output : 사탕의 수
**3**
풀이 아이디어
문제를 잘못읽었었는데, 현 위치에서 상하좌우로 움직이는 줄알았다.
현 위치에서 가장 사탕을 많이 먹을수있는수는 자신의 수 + 우측 / 우측하단대각선 / 하단 중 가장 많이 먹을수 있는 사탕의 위치 중 하나이다 .
> [DP]점프, [DP]이동하기

- BOJ/2293_동전 1/6047198844.cpp
**1**
출처 : 백준
https://www.acmicpc.net/problem/2293
**2**
input : 동전의 가치
output : 경우의수
**3**
풀이 아이디어
사용한 동전의 구성이 같은데, 순서만 다른 것은 같은 경우이다.라는 조건때문에 중복을 제거하는 경우의 수만 고려해야했는데요.
동전 : 1 / 2 / 5
목표 : 10
value[k] = 가치의 합(k)를 동전들로 만들수있는 경우의수
bottom-up 방식으로 풀었는데요. 
동전 1을 사용하여 가치의합(k)를 만들고.
동전 1 / 동전2를 사용하여 가치의합(k)를 만들고
동전 1 / 동전2 / 동전 5를 사용하여 가치의합(k)을 만들었습니다.
동전 k라 함은 k가치를 가지는 동전을 뜻합니다.
여기서 중요한건 value[0]은 1입니다. 가치가 0일려면 아무것도 선택하지 않으면 되기때문에 해당 경우의 수는 1이라고 두었습니다.
동전 1 을 가지고 
가치 1을 만드는 경우의 수는 value[0]입니다. > value[1] += value[0]
가치 2를 만드는 경우의 수는 value[1] 입니다. > value[2] += value[1]
가치 3을 만드는 경우의 수는 value[2] 입니다. > value[3] += value[2]
..
..
가치 10을 만드는 경우의 수는 value[9] 입니다. > value[10] += value[9]
그 이유는 value[k]는 유일한 경우의 수입니다. 해당 경우의 수에 동전의 가치만 얹으면 됩니다.
쉽게 설명드리면 동전 1를 고정시켜 놓고 남는 가치에 대한 경우의 수를 더하기만 하면됩니다. …
> [DP]동전 1 + *질문*

- programmers/난이도별/level01.자연수_뒤집어_배열로_만들기/develop-sell.js
문제풀이:
숫자를 문자로 형변환 후, char 한 글자씩 반대로 접근(len - i -1)해서 answer 배열에 추가(push)한다. 
알게된 점: 
reverse()라는 함수가 존재하는걸 깜빡했네요!! 
배열 크기 그대로 안의 내용을 바꿀 때 (여기선 문자 -> 숫자로 변경) map() 함수를 사용하면 효율적이다. 
toString == n + "" (숫자 -> 문자)
Number(char) == n * 1 (문자 -> 숫자)
> [Programmers Lv.1] 자연수_뒤집어_배열로_만들기 reverse_numbers_array

- programmers/난이도별/level03.블록_이동하기/sangmandu.py
> [level03] 블록 이동하기

- BOJ/15591.MooTube (Silver)/6047198844.cpp
**1**
출처: 백준
https://www.acmicpc.net/problem/15591
**2**
input : 유사도/질문
output : 답변
**3**
풀이 아이디어
DFS탐색을 하면서 간선에 대해서 업데이트를 하면됩니다.
위 그림에서 노드1에서 노드2으로 탐색을 할때. 노드1과 노드2 사이의 간선과 node[1]의 값을 비교합니다. node[n]값은 작은 값을 만날경우 작은 값으로 업데이트됩니다. 단 0의 값을 만날경우에는 간선값으로 대체됩니다.
위에서 node[1]의 값은 0이기때문에 1과 2의 간선값, 3이 node[2]가 됩니다.
node[2]와  node[3]의 간선값은 2이고, node[2]의 값은 3이기 때문에 node[3]은 2의 값을 가집니다.
> [DFS]MooTube (Silver)

- BOJ/16929.Two Dots/6047198844.cpp
**1**
출처 : 백준
https://www.acmicpc.net/problem/16929
**2**
input : 게임판
output : 사이클이 존재하는 경우 Yes, 아닌경우 No
**3**
풀이 아이디어
- 모든 k개의 점은 서로 다르다. 
- k는 4보다 크거나 같다.
- 모든 점의 색은 같다.
- 모든 1 ≤ i ≤ k-1에 대해서, di와 di+1은 인접하다. 또, dk와 d1도 인접해야 한다. 두 점이 인접하다는 것은 각각의 점이 들어있는 칸이 변을 공유한다는 의미이다.
마지막 조건은 결국에는 상/하/좌/우로 탐색이 가능하다는 의미입니다. 물론 범위안에서요.
결론적으로. 현재 점을 기준으로 상/하/좌/우 탐색을 하되, 보드의 범위, 현재점과 같은 알파벳이여야합니다.
이 기본 조건으로 처음의 점에 도달하게 되면, 4개이상의 점을 탐색했는지 확인합니다.
아닐 경우에는 false를 반환합니다. 모든 점에 대해서 이 과정을 수행하고, 한번이라도 true가 나올경우에는 Yes를 출력하고 한번이라도 안나온경우에는 No를 출력합니다.
> [DFS]Two Dots

- programmers/난이도별/level01.정수_내림차순으로_배치하기/develop-sell.js
문제풀이: 
스트링으로 변환 후 => (n + "") 
한 글자씩 배열로 변환 => split('')
큰 숫자순으로 정렬 => sort((a,b) => b-a)
배열을 스트링으로 변환 -> join('')
스트링으로 숫자로 변환 -> Number(num)
> [Programmers Lv.1] 정수 내림차순으로 배치하기 sort_number

- programmers/난이도별/level01.짝수와_홀수/develop-sell.js
문제풀이:
2로 나눠지면 짝수, 아니면 홀수 
음... 오늘은 좀 너무 쉬운 문제를 풀었네요.. 하하 
그래도 하루에 하나 푸는 게 중요하니까..!! 
(이만 다른 일 하러 가봅니당..!!)
> [Programmers Lv.1] 짝수와 홀수 odd and even

- LeetCode/String/Complex_Number_Multiplication/HyeonJeong.py
- LeetCode/String/Rearrange_Words_in_a_Sentence/HyeonJeong.py
Input: "1+1i", "1+1i"  -> Output: "0+2i"
복소수 두 개가 주어졌을 때 계산이 되어서 계산 결과를 문자열로 반환하는 문제입니다.
(1 + i) * (1 + i) = 1 + i2 + 2 * i = 2i에서 i*i는 -1이 되므로 해당 결과에 -1을 붙이고, i의 계수끼리 결과에는 'i'를 붙여서 문자열로 계산 결과가 출력될 수 있게 구성하였습니다.
* 정수 부분과 소수 부분의 계수를 구하기 위해서 find() 함수로 '+'의 위치를 찾게 하였습니다.
> [LeetCode] Complex Number Multiplication

- programmers/난이도별/level01.정수_제곱근_판별/develop-sell.js
문제풀이:
n을 루트씌운 것이 integer인지 아닌지에 따라 -1, x+1의 제곱을 리턴한다.
사용 함수: 
Math.sqrt(n) : 제곱근을 구하는 함수
Number.isInteger(num) : 정수인지 아닌지 확인하는 함수 (return true or false)
배운 점:
제곱하는 함수가 생각 안 나서 위에 식처럼 풀었다. 
(num) ** 2  : 제곱하는 함수 ( 숫자 ** 2 / 숫자 ** 3 이면 세제곱)
> [Programmers Lv.1] 정수_제곱근_판별 distinction_num_sqrt

- BOJ/13549.숨바꼭질 3/6047198844.cpp
- BOJ/1759.암호만들기/6047198844.cpp
**1**
출처 : 백준
https://www.acmicpc.net/problem/13549
**2**
input : 출발점 / 도착점
output :가장 빠른 시간
**3**
풀이 아이디어
방문을 했어도 최소값으로 갱신을 해줘야 하는곳이 있다고 생각이 들었습니다. 
예를 들면
1에서 2를 가는 경우
덧셈을 수행하고 방문했다고 처리를 해버리면 결과값은 2가 됩니다.
왜냐하면 방문을 했기 때문에 뒤에 곱셈수행이 안되기때문입니다.
따라서 방문을 했더라도, 비교하는 과정이 필요합니다.
> [BFS]숨바꼭질3&[brute-force]암호 만들기

- programmers/난이도별/level01.콜라츠_추측/develop-sell.js
문제풀이:
짝수면 나누기 2, 홀수면 3 곱하고 + 1 해준다. 
언제까지? 숫자가 1이 되거나, 돌린 횟수가 500번이 되는 경우(return -1)
아쉬운점:
eyabc.js님 코드 확인 후 무한루프가 아니라, 
num != 1로 돌리면 한 줄 더 줄일 수 있음을 알게 되었다. 
// const process = (num) => isEven(num) ? num / 2 : num * 3 + 1;
프로세스를 이렇게 함수로 명칭해서 보니까 눈으로 보기 좋음을 알게 되었습니다. 
앞으론 네이밍도 한번 도전해보겠습니다.
> [Programmers Lv.1] 콜라츠_추측 Collatz_problem

- LeetCode/String/Rearrange_Words_in_a_Sentence/HyeonJeong.py
' '로 단어가 분리된 문장이 문자열로 주어지는데, 단어의 길이에 따라 긴 순으로 정리해서 문자열 반환하는 문제
-> 문자열을 단어로 분리해서 리스트로 만들고, 리스트의 정렬을 이용해서 정리 후 다시 문자열로 만들었습니다. 그리고 단어의 길이를 lambda() 함수에서 이용해 길이 순으로 정렬을 시켰습니다.
인덱스를 이용해 문장의 첫번째 글자만 소문자 or 대문자로 변환할 수 있게 하였습니다!
> [LeetCode] Rearrange Words in a Sentence

- LeetCode/Math/Complement_of_Base_10_Integer/HyeonJeong.py
10진수를 2진수로 변경하였을 때 1 -> 0으로, 0 -> 1로 변경해 만들어진 2진수의 10진수 값 반환하는 문제
-> 이진수의 '0b'를 제외하기 위해서 bin()이 반환한 문자열의 인덱스 2부터 읽게 하였고, int(숫자,2)를 이용해서 2진수 숫자를 10진수의 형태로 변경시켜 반환하게 하였습니다.
> [LeetCode] Complement of Base 10 Integer

- programmers/난이도별/level01.평균_구하기/develop-sell.js
문제풀이:
지난 번에 배웠던 reduce 함수를 통해 값을 구할 수 있었다.
reduce의 맨 앞 값(result)은 함수 적용된 후의 함수이고, 
present는 현재 값이다.
결과에 현재값을 다 더하고, array의 길이 만큼 나누면 평균값이 나온다.
> [Programmers Lv.1] 평균 구하기 find_average

- LeetCode/String/Roman_to_Integer/HyeonJoeng.py
기호로 표시되는 로마 숫자를 정수로 변환하는 문제
: 우선 기호에 해당하는 값과 해당하는 수를 딕셔너리로 만들어서 이용하였습니다. 
주의해야 할 점은 4를 'IV', 9를 'IX', 40을 'XL' 같이 두 문자를 이용해서 표현되는 숫자인데, 현재 불러들인 문자열의 인덱스의 문자보다 인덱스+1의 문자의 수가 더 큰 경우로 해당 경우에 알맞은 수가 처리될 수 있게 하였습니다.
> [LeetCode] Roman to Integer

- BOJ/2447.별찍기 - 10/6047198844.cpp
**1**
출처 : 백준
https://www.acmicpc.net/problem/2447
**2**
input : 패턴의 수
output : 패턴에 따라 찍힌별
**3**
풀이 아이디어
y,x좌표를 3등분하여 분할정복 알고리즘을 이용하여 별찍기를 수행했습니다.
바로바로 찍는것이 아니라 배열에 넣고 모두수행했을때 배열에 있는 값들을 꺼냈습니다.
> [분할정복]별찍기 - 10

- LeetCode/String/Letter_Combinations_of_a_Phone_Number/HyeonJeong.py
2-9까지 숫자의 매핑에 따라 만들어질 수 있는 모든 문자열을 리스트로 반환하는 문제
-> 2-6까지는 3개씩 알파벳이 정해져서 아스키코드를 문자로 바꾸는 방식을 이용해서 각 해당하는 문자들이 담기게 하고, 7-9까지는 각각의 문자열에서 문자들이 가져와 이용되게 하였습니다. 이렇게 사용될 수 있는 문자들을 받은 배열이 for문에서 돌아가면서 각 숫자에 해당되는 문자를 가져오게 해보았습니다.
받는 문자열의 길이가 4이하여서 제 방식으로 구현이 가능하였고, for의 횟수를 줄여보려고 했지만 그 부분은 해결하지 못했습니다!
> [LeetCode] Letter Combinations of a Phone Number

- programmers/난이도별/level01.하샤드_수/develop-sell.js
문제풀이:
먼저 숫자를 str로 변환 후, 
split으로 한 글자씩 arr에 저장한다. 
그 후 reduce함수를 통해 각 한 글자씩 더한 값을 구한다. (== num)
만약 주어진 x가 num으로 나눠지지 않으면 false, 나눠지면 true이다. 
한 줄 코드:
return !(n % (n + "").split("").reduce((a, b) => +b + +a ));
js에서 0이면 false, 아니면 true로 인식하니까, 
앞에 !(부정)으로 반환해주면 아래 if문을 한 줄 더 줄일 수 있다.
> [Programmers Lv.1 ]하샤드 수 hasHad_num

- BOJ/9095.1,2,3 더하기/6047198844.cpp
**1**
출처 : 백준
https://www.acmicpc.net/problem/9095
**2**
input : 정수 n
output : 방법의수
**3**
풀이 아이디어
주석에 첨부했습니다. 점화식을 세우고 다이나믹 프로그래밍을 이용하여 풀었습니다.
> [다이나믹프로그래밍]1,2,3더하기

- LeetCode/String/Valid_Parentheses/HyeonJeong.py
괄호를 동일한 유형끼리 올바른 순서로 닫았는지 확인해서 True나 False를 반환하는 문제
-> 리스트를 생성해서 열린 괄호를 담게 하고, 닫힌 괄호가 나오면 마지막 리스트에 담긴 괄호에 해당하는 것이 맞는지 확인하게 하였습니다. 올바른 경우에는 리스트에서 괄호를 지우고, 문자열을 다 확인한 후 빈리스트가 남으면 True를 반환하게 하였습니다. 아닌 경우에는 올바른 순서로 닫힌 문자열이 아니므로 False가 반환되게 하였습니다.
> [LeetCode] Valid Parentheses

- BOJ/10819.차이를 최대로/6047198844.cpp
**1**
출처 : 백준
https://www.acmicpc.net/problem/10819
**2**
input : 배열
output : 식의 최대값
**3**
풀이 아이디어
구하고자하는 값의 크기가 작아서 완전탐색을 이용하여 풀었습니다.
> [완전탐색]차이를 최대로

- LeetCode/Array/Contains_Duplicate/HyeonJeong.py
주어진 배열에 중복된 항목이 있는지 확인하고 있는 경우는 True, 아닌 경우는 False를 반환하는 문제
-> 배열을 크기 순으로 정렬하면 중복되는 수끼리 모이게 되어서 for문을 돌리면서 (현재 인덱스)+1의 값이 현재 인덱스와 같으면 True를 반환하게 하고, 끝까지 앞과 뒤의 인덱스에 같은 값이 없는 경우는 False를 반환하게 하였습니다.
> [LeetCode] Contains Duplicate

- BOJ/12865.평범한 배낭/6047198844.cpp
**1**
출처 : 백준
https://www.acmicpc.net/problem/12865
**2**
input : 최대 배낭무게 / 물건 무게 / 물건 가치
output : 들을수있는 물건의 최대 가치
**3**
풀이 아이디어
다이나믹 프로그래밍을 이용했습니다.
이차원 배열을 이용했는데, 물건을 하나하나 늘려가면서 가질수있는 최대가치에 대해서 구했습니다.
```
4 7
6 13
4 8
3 6
5 12
```
위의 예시에서 최대 배낭의 크기는 7이고, 각각 물품의 무게/가치는 6/13 , 4/8, 3/6 , 5/12 입니다.
최대 얻을수있는 가치를 점점늘려가면서 계산합니다.
첫번째 물건
첫번쨰 물건 + 두번째 물건
첫번째 물건 + 두번째 물건 + 세번째물건
첫번째 물건 + 두번째 물건 + 세번째물건 + 네번째 물건
첫번째 물건 + 두번째 물건 + 세번째물건 + 네번째 물건 + 다섯번째 물건
배낭의 최대 크기도 1부터 ~ 최대크기까지 들어갈수있는 최대가치에 대해 계산합니다.
첫번째 물건은
배낭크기 
1일때 0
2일때 0
3일때 0
4일때 0
5일때 0
6일때 13
7일때 13
첫번쨰 물건 + 두번째 물건은
1일때 0
2일때 0
3일때 0
4일때 8
5일때 8
6일때 13
7일때 13
첫번째 물건 + 두번째 물건 + 세번째물건은
1일때 0
2일때 0
3일때 6
4일때 8
5일때 8
6일때 13
7일때 14
첫번째 물건 + 두번째 물건 + 세번째물건 + 네번째 물건은
1일때 0
2일때 0
3일때 6
4일때 8
5일때 8
6일때 13
7일때 14
첫번째 물건 + 두번째 물건 + 세번째물건 + 네번째 물건 + …
> [다이나믹프로그래밍]평범한 배낭

- programmers/난이도별/level01.x만큼_간격이_있는_n개의_숫자/develop-sell.js
문제풀이: 
간단한 배열 문제였다. 
한줄 풀이: 
return Array(n)
.fill(x)
.map((v, i) => (i + 1) * v)
Array(n) : n 크기의 배열을 만든다
fill(x) : x값으로 배열을 다 채운다 
=> 만약 이미 다른 값이 들어있어도 x값으로 배열을 다 채워버린다. 
map((v, i)) : 여기서 v는 값, i는 인덱스이고, "인덱스 + 1" 만큼 값으로 곱해주면 된다.
> [Programmers Lv.1] x만큼 간격 있는 n개의 숫자 number_with_interval

- programmers/난이도별/level01.핸드폰_번호_가리기/develop-sell.js
문제풀이: 
phone_number str를 한 글자씩 split하고, 
같은 사이즈의 배열의 조건에 따라 요소 값만 변하니까 map함수를 사용했다. 
그래서 배열의 전체 사이즈에서 인덱스("index")를 뺀 값이 4 이하인 경우만 
실제 값("value")를, 아니면 "*"를 반환하도록 했다. 
마지막으로 join('')으로 배열을 다시 str로 만들어준다. 
프로그래머스 풀이: 
//1 정규식
return s.replace(/\d(?=\d{4})/g, "*");
참고: https://beomy.tistory.com/21 
//2 repeat
var result = "*".repeat(s.length - 4) + s.slice(-4);
맨 뒤 4자리 빼고 앞 부분 : (s.length - 4)
만큼은 repeat 함수를 통해 "*"를 반복해서 str를 만들어준다. 
그 다음 뒤에 slice 함수를 통해, 맨 뒤 4자리를 짤라서 붙인다. 
slice는 '음수'가 지원되니 slice를 쓰는 것을 추천한다 (즉, 뒤에서부터 index하는 것도 가능) <=> substr
> [Programmers Lv.1] 핸드폰_번호_가리기 hide_phone_number

- programmers/난이도별/level01.행렬의_덧셈/develop-sell.js
문제풀이: 
빈 배열에 더한 값을 temp 변수에 넣고, temp를 
다시 배열에 push하는 방식으로 구현함. 
해결 안된 점: 
맨 처음에는 temp에 push하지 않고, array[i]에 바로 push하도록 했는데, 
값이 이상하게 들어가서 못 풀었습니다. 
let array = Array(out_len).fill([]);
for(let i = 0; i < out_len; i ++){
for(let j = 0; j < in_len; j++){
array[i].push(arr1[i][j] + arr2[i][j]);
}
}
혹시 위 방식이 왜 안되는지 알 수 있을까요?? 
한줄 풀이: 
return A.map((a,i) => a.map((b, j) => b + B[i][j]));
여기선 A부터 map으로 접근하고, 그 후에 또 다시 나온 값 a 배열의 map을
또 걸어서 그 값인 b에 B배열의 i,j 인덱스에 해당되는 값을 더한 배열을 return하도록 했다.
> [Programmers Lv.1] 행렬의 덧셈 matrix_sum

- BOJ/9251.LCS/6047198844.cpp
**1**
출처 : 백준
https://www.acmicpc.net/problem/9251
**2**
input : 두개의 문자열
output : 가장 긴 길이의 문자열 길이
**3**
풀이 아이디어
3개의 점화식이 있는데요.
끝이 같으면 끝을 제거한값 + 1
끝이 다르면 하나 끝을 제거한값 + 1 중 가장 큰 값
길이가 0이면 0을 반환
일단 
ACAYKP와 CAPCAK를 예를 들면
끝이 다릅니다.
따라서 끝을 하나 제거한값들을 비교하고 큰값이 정답입니다.
ACAYK, CAPCAK 하고 ACAYKP, CAPCAK 가 있습니다.
ACAYK, CAPCAK는 끝이 같습니다.
따라서 ACAY, CAPCA의 값과 같습니다.
길이가 0일때까지 반복하면 됩니다.
> [다이나믹프로그래밍]LCS

- BOJ/2178.미로 탐색/rockmiin.py
BFS문제 입니다. 
미로에서 각 정점마다 이동 횟수를 세주며 방문 여부를 확인시켜주는 visited 리스트를 사용하여 구현하였습니다.
> 2178. 미로 탐색

- BOJ/1932.정수 삼각형/6047198844.cpp
**1**
출처 : 백준
https://www.acmicpc.net/problem/1932
**2**
input : 정수 삼각형
output :  합이 최대가 되는 경로에 있는 수의 합
**3**
풀이 아이디어
다이나믹 프로그래밍. bottom up 방식으로 위에서 부터 아래까지 모든 경로에 대해서 탐색했습니다.
> [BOJ]정수 삼각형

- LeetCode/Array/Merge_Intervals/HyeonJeong.py
- LeetCode/Array/Unique_Paths/HyeonJeong.py
Merge Intervals
intervals 2차원 배열이 주어지면 겹쳐지는 간격들은 합쳐서 겹치지 않는 간격의 배열을 하는 문제
Input: intervals = [[1,3],[2,6],[8,10],[15,18]] -> Output: [[1,6],[8,10],[15,18]]
배열을 정렬해서 배열의 앞과 뒤 인덱스를 비교해서 간격이 합쳐질 수 있으면 합쳐서 배열에 추가되는 방식으로 코드를 작성하였습니다. tuple()과 set()을 사용해서 2차원 배열에서 중복된 리스트를 제거하게 하였고, lambda를 이용해 리스트의 첫 번째 인덱스 값에 따라 정렬이 되게 하였습니다. while문 내에서는 정렬된 리스트의 첫 번째 인덱스 값을 비교해서 겹쳐지는 값을 확인하고, 합쳐서 만들어질 첫 번째 인덱스 값과 배열의 리스트의 값을 비교해서 넣어질 인덱스 위치를 찾아서 해당 위치에 두 리스트가 합쳐서 큰 범위를 가지게 된 리스트가 추가되게 하였습니다.
[https://leetcode.com/problems/merge-intervals/](url)
*저에게는 너무 어려웠는데,  몇 일에 걸쳐 코드를 결국 완성하게 되었네요!!
Unique Paths
m x n 격차에서 왼쪽 상단 모서리에 있는 로봇이 오른쪽 하단 모서리에 도달하는 경로의 수를 반환하는 문제
m-1개의 '아래'와 n-1개의 '오른쪽'의 순서를 정하는 순열 계산으로 코드를 작성하였습니다. nCr = n!/(r!*(n-r)!)에서 r = m으로 생각하여 해당 팩토리얼을 for문을 통해 계산되게 하였습니다.
> [LeetCode] Merge Intervals & Unique Paths

- BOJ/4963.섬의 개수/rockmiin.py
> 4963.섬의 개수

- LeetCode/Array/Summary_Ranges/HyeonJeong.java
범위가 담긴 배열을 받아서 이어진 정수들은 a->b(a, a+1, ... , b)를 이용해서 표현한 문자열을 리스트로 반환하는 문제
-> while문을 통해서 다음 인덱스가 앞 인덱스와 이어지는지 확인을 하고, 범위의 수가 1개 인지, 2개 이상 인지 확인해서 해당하는 범위를 구분해 리스트에 넣게 하였습니다
> [LeetCode] Summary Ranges

- LeetCode/Array/Merge_Intervals/kth496.kt
- LeetCode/Backtracking/Path_with_Maximum_Gold/kth496.kt
> [LeetCode] Merge Intervals, Path with Maximum Gold

- programmers/난이도별/level01.예산/develop-sell.js
문제풀이: 
문제 조건 1) 최대한 많은 부서에게 물품을 구매할수록 있도록 한다 
문제 조건 2) 각 부서마다 비용이 다르다
문제 조건 3) 한 부서에게 지불해줄 시 신청한 금액 전체를 다 지원해줘야 한다.
(ex. 신청 금액이 5원인데, 4원만 지원 불가능)
가장 작은 비용의 부서부터 지원해줘야 최대한 많은 부서들에게 지원해주는 것이다. 
그래서 비용이 작은 순으로 부서별 비용 배열을 sort 시켰다. 
그 다음 for문을 돌면서 총 비용(total_cost)가 budget를 넘기 전까지 
부서들을 지원해주면 된다. 
(부서 지원해주면 total_cost가 그 만큼 늘어나고(total_cost +=d[i]), 지원해준 부서 숫자(answer)도 늘어남)
궁금한 점: 
원래는 reduce 함수를 써서, 
total 값이 budget을 넘지 않기 전까지의 answer 값을 구하려고 했는데, 
아직 개념이 헷갈려서 쉽지 않았다. 
그런데 생각해보니, reduce는 중간에 break 기능이 없어 배열은 엄청 긴데 비용이 높아 이제부턴 못 지원해주는 경우에 
모든 요소를 다 돌아야하니 덜 효율적이라고 생각했다. (for문은 break문으로 빠져나오기 때문)
그래도 reduce로 짜는 방법을 알고 싶은데, 
아래 코드까진 짜보았는데, 뭔가 문제가 있어 보입니다. 
sort_arr.reduce((total, current) => ((total + current <= budget) ? (answer ++ , total+= current) : answer ), 0) 
return answer 
budget보다 작으면 …
> [Programmers Lv.1] 예산 budget_problem

- LeetCode/Math/Maximum_Product_of_Three_Numbers/HyeonJeong.java
배열에서 3개의 수를 곱해 가장 큰 값이 되는 경우의 결과를 반환하는 문제
-> 배열을 오름차순으로 정렬하여 뒤에서 3개를 곱했을 때 결과와 음수가 2개 이상 존재하는 경우에는 앞에서 2개와 맨 뒤 1개의 수를 곱했을 때 결과를 확인하여 더 큰 값을 반환하게 하였습니다.
[https://leetcode.com/problems/maximum-product-of-three-numbers/](url)
> [LeetCode] Maximum Product of Three Numbers

- BOJ/9184.신나는 함수 실행/6047198844.cpp
**1**
출처 : 백준
https://www.acmicpc.net/problem/9184
**2**
input : 입력 데이터
output : 결과값
**3**
풀이 아이디어
다이나믹 프로그래밍, 같은 유형 문제가 반복되기때문에 메모제이션기법을 활용했습니다.
> [DP]신나는 함수 실행

- BOJ/1520.내리막길/6047198844.cpp
- BOJ/5014.스타트링크/6047198844.cpp
스타트링크 [210103]
**1**
출처 : 백준
https://www.acmicpc.net/problem/5014
**2**
input : 층수
output : 버튼을 눌러야하는 최소횟수
**3**
풀이 아이디어
브루트 포스, 주석에 설명 첨부.
내리막길 [210104]
**1**
출처 : 백준
https://www.acmicpc.net/problem/1520
**2**
input : 각 지점의 높이
output : 경우의수
**3**
풀이 아이디어
DFS를 하면서 목적지에 도달하는 경우. 해당 루트가 가지는 경우의수가 1이 됩니다.
DP랑 결합되서 DFS구조가 특이한데요. 방문을 하였더라도, 해당 부분을 방문할 수 있게했습니다. memo값을 얻기 위해서요.
> [완전탐색]스타트링크 && [DP&DFS]내리막길

- programmers/난이도별/level02.구명보트/dkdlelk99.py
처음에는 pop을 사용하여 보트에 태울 수 있는 사람을 제거해 나가는 방식으로 풀었지만 효율성 테스트에서 실패
그래서 start와 end라는 counter를 이용하여 풀이하였습니다.
> [Programmers Lv.2] 구명 보트

- BOJ/2667. 단지번호붙이기/rockmiin.py
> 2667. 단지번호붙이기 

- programmers/난이도별/level01.모의고사/develop-sell.js
문제풀이: 
player 1,2,3의 답이 계속 중복되는데, 
이때 중복되는 구간의 사이즈가 다르다. 1부터 5,8,10 사이즈 
그래서 먼저 그 구간을 값을 넣은 배열로 const 지정해줬다.
그 후 filter 함수를 통해 answers 배열과 맞는 경우만 탐색해서 그것의 length를 구해서
맞은 갯수가 알게 되었다. 
이때 p2[i % 8] 이런식으로 하면 딱 안 나눠지는 부분까지 캐치하게 된다 (중요 포인트!)
그 후 값들의 가장 큰 값을 max 구해서, max과 같거나 큰 answer를 filter해서 제출한다. 
배운점: 
Math.max 함수 존재
var max = Math.max(a1c,a2c,a3c);
> [Programmers Lv.1] 모의고사mock_test

- BOJ/10867.중복 뺴고 정렬하기/rockmiin.py
- BOJ/11399.ATM/rockmiin.py
> 10867.중복 빼고 정렬하기 & 11399. ATM

- BOJ/9663.N-Queen/6047198844.cpp
**1**
출처 : 백준
**2**
input : 크기
output : 경우의수 
**3**
풀이 아이디어
백트래킹을 이용하여 풀었습니다. 워낙 기본 문제라 설명은 생략합니다.
> [DFS/Brute_force]N-Queen

- LeetCode/Array/Third_Maximum_Number/HyeonJeong.java
3번째 큰 수를 반환하는 문제로 3번째 큰 수가 존재하지 않는 경우에는 가장 큰 수를 반환하는 문제
-> 수를 비교하기 위해서 정렬을 이용하고, 정렬된 배열의 뒤 인데스부터 값을 비교해서 각 값보다 작은 값이 나오는 경우를 계산해서 3번째로 큰 수를 반환할 수 있게 하고, for문이 끝나고도 반환되지 않았으면 가장 큰 수가 반환되게 코드를 작성하였습니다.
[https://leetcode.com/problems/single-number/](url)
> [LeetCode] Third Maximum Number

- programmers/난이도별/level02.멀쩡한_사각형/README.md
- programmers/난이도별/level02.멀쩡한_사각형/dkdlelk99.py
이 문제로 알 수 있던 점
1. 아는 함수 있으면 그냥 가져다 쓰자. 나보다 이쁘게 잘 구현해놨다.
2. 사칙 연산 순서가 성능에 영향을 끼칠 수 있다. 
ex) x / y * z보다 x * z / y가 더 빠름
아마 실수형 연산 2번 vs 정수형 연산 1번 + 실수형 연산 1번의 차이가 아닐까 싶다.
> [Programmers Lv.02] 멀쩡한 사각형

- LeetCode/String/Reverse_String/HyeonJeong.java
주어진 문자 배열을 뒤집어서 반환하는 문제
-> 새로운 추가 공간을 생성하지 않아야 해서 문자의 개수가 홀수인 경우는 가운데 문자는 두고, 홀수의 나머지와 짝수는 가운데에서 같은 거리만큼 떨어져 있는 인덱스끼리 값이 변경되게 하였습니다.
[https://leetcode.com/problems/reverse-string/](url)
> [LeetCode] Reverse String

- programmers/난이도별/level01.다트_게임/develop-sell.js
문제풀이: 
먼저 숫자인지, S,D,T인지, opiton인지에 따라 분기처리 했습니다. 
숫자의 경우, 만약 숫자가 10이면 i ++해서 다음 index는 실행하지 않게 하고, 대신 temp(현재 변하는 값을 담는 변수)를
10으로 설정했습니다. 
S,D,T의 경우가 가장 쉬웠는데, 
문자에 따라 제곱하는 숫자가 다르도록 함수를 짜서 진행했습니다. 
마지막 옵션의 경우 
*이면 전 값도 두배로 하는 부분이 까다로웠습니다. 
이걸 다른 분들 코드 보니까, 아예 1회차,2회차마다 값을 저처럼 answer에 더하는게 아니라
어떠한 배열에 1회차, 2회차 값 별로 정리하는게 * 옵션을 다룰 때 훨씬 좋겠다는 생각했습니다. 
#이면 현재 값을 -1을 곱해주면 되어서 쉬었습니다. 
마지막으로 옵션은 말그대로 옵션이라서 
있을 수도, 없을 수도 있는데 
그걸 판단하기 위해 checkoption 변수를 둬서 
checkoption은 S,D,T 분기 부분 끝나고 무조건 false로 만들게 했고, 
그 다음 옵션과 숫자로 가는데, 
만약 숫자로 가게 되면 옵션이 없이 연산이 끝난거니까, 바로 temp를 answer에 더했습니다. 
그리고 전 값이 필요해서 post 변수에 temp를 저장했습니다. 
옵션으로 가게 되어도 이 부분을 추가했습니다. 
후기: 
와우... 처음으로 긴 알고리즘을 풀었는데 너무 어려웠네요,
혹시 더 좋은 코드 있으면 알려주시면 감사하겠습니다!
> [Programmers Lv.1 다트게임] dart_game

- BOJ/1238.파티/6047198844.cpp
- BOJ/1753.최단경로/6047198844.cpp
- BOJ/4485.녹색 옷 입은 애가 젤다지/6047198844.cpp
[210107]
최단경로
**1**
출처 : 백준
https://www.acmicpc.net/problem/1753
**2**
input : 거리값
output : 최단거리
**3**
풀이 아이디어
Dijkstra 알고리즘을 공부하고 코딩했습니다.
Dijkstra 알고리즘은 BFS하고 비슷한데, 차이점은 priority_queue를 이용한다는것입니다.
또한 음수값을 가지는 경로값이 있을 경우에는 작동하지 않습니다. 음수값을 가지는 경로값은 어떠한 최단경로 알고리즘으로도  풀수없습니다. Dijkstra 알고리즘은 한 정점에서 모든 정점까지의 최소거리를 구하는 알고리즘입니다.
파티
**1**
출처 : 백준
https://www.acmicpc.net/problem/1238
**2**
input : 거리에 소요되는 시간값
output : 첫 번째 줄에 N명의 학생들 중 오고 가는데 가장 오래 걸리는 학생의 소요시간
**3**
위의 문제와 동일하게 Dijkstra를 이용합니다. 하지만 왕복을 구해야합니다. 이럴경우 세가지로 풀수있는데 , 그중 두가지로 풀었습니다.
1. 플로이드 - 와샬
2. 다익스트라 알고리즘으로 각 정점에서 출발하는 모든 최단경로를 구하는 방법. 정점이 N개라면 N번의 Dijkstra를 이용합니다.
3. 다익스트라 알고리즘으로 한 정점에서 출발하는 모든 최단 경로를 구하고 간선을 뒤집어서 다시 한 정점에서 출발하는 모든 최단 경로를 구합니다. 3번의 방법은 2번의 Dijkstra를 이용합니다.
2,3번 방법을 선택하여 풀었습니다. 3번은 한 정점에서 출발하는 경로를 구하지만 그 경로가 뒤집어진 …
> [다익스트라]최단경로,파티,녹색 옷 입은 애가 젤다지?

- LeetCode/Math/Check_If_It_Is_a_Straight_Line/HyeonJeong.java
점 [x,y] 담긴 배열을 받아서 해당 점들로 직선이 만들어지는 확인하는 문제
해당 점들의 기울기를 비교해서 다 같은 경우에는 true 그렇지 않은 경우에는 false가 반환될 수 있게 하였습니다. 기울기에서는 x축과 평행한 직선이 만들어지는 경우도 있으므로 나눠지는 수가 0이 되는 경우를 확인해서 모두 0이 되면 해당 직선이 만들어진다고 보았고, 일부의 기울기에서만 나눠지는 수가 0이 되면 직선이 만들어지지 않는다고 했습니다. 위의 경우에 해당하지 않으면 값들을 다 계산하고, 기울기가 담긴 배열의 가장 큰 값과 가장 작은 값을 비교해서 모두 같은 값을 가지는지 확인했습니다.
[https://leetcode.com/problems/check-if-it-is-a-straight-line/](url)
> [LeetCode] Check If It Is a Straight Line

- LeetCode/String/To_Lower_Case/HyeonJeong.java
주어진 문자열의 문자들을 소문자로 변경하는 문제
-> 문자들을 읽어서 대문자인 경우는 +32를 해서 해당하는 소문자를 StringBuffer에 넣고, 소문자인 경우에는 해당 문자를  StringBuffer에 넣게 하고, 만들어진 문자열을 String으로 만든 후 반환하게 하였습니다.
> [LeetCode] To Lower Case

- programmers/난이도별/level02.최솟값_만들기/README.md
- programmers/난이도별/level02.최솟값_만들기/dkdlelk99.py
> [Programmers Lv.02] 최솟값 만들기

- BOJ/14502.연구소/rockmiin.py
- BOJ/2583.영역 구하기/rockmiin.py
BFS로 구현하였습니다. 뭔가 매번 비슷한 패턴으로 풀게 되는 것 같은데 좀 더 괜찮은 풀이나 조언 해주신다면 감사하겠습니다 !
> 2583.영역 구하기 & 14502. 연구소

- 알고스팟/울타리 잘라내기/쿼드트리.cpp
**1**
출처 : 알고스팟
https://algospot.com/judge/problem/read/QUADTREE
**2**
input : 쿼드트리
output : 뒤집은 쿼드트리
**3**
풀이 아이디어
쿼드트리를 분할 정복합니다.
w 나 b 가 나오면. 분할하지 않습니다. base case입니다.
x가 나오면 뒤의 값들을 4분할합니다.
왼쪽 위. 오른쪽 위. 왼쪽 아래. 오른쪽 아래
분할후 각각의 값들을 얻습니다.
x + 왼쪽 아래 + 왼쪽 위 + 오른쪽 아래 + 오른쪽 위 를 반납합니다.
> [분할정복]쿼드트리

- LeetCode/Linked_List/Add_Two_Numbers/HyeonJeong.py
- LeetCode/String/Ransom_Note/HyeonJeong.java
ransomNote과 magazine 두 문자열에서 ransomNote이 magazine의 문자들로 만들어질 수 있는지를 확인하는 문제
둘 다  String이므로 char 배열로 변형시켜 각 문자가 포함되는지 비교할 수 있게 이중 for문을 이용하였습니다.
https://leetcode.com/problems/ransom-note/
문자열을 문자 배열로 표현 : char[] array = str.toCharArray();
> [LeetCode] Ransom_Note

- LeetCode/Linked_List/Add_Two_Numbers/HyeonJeong.py
> [LeetCode] Add Two Numbers2

- BOJ/10830.행렬 제곱/10830_행렬 제곱.cpp
**1**
출처 : 백준
**2**
input : 행렬, 제곱할횟수
output : 제곱된 행렬
**3**
풀이 아이디어
분할정복으로 풀었습니다. 행렬간의 곱셈구현만 해주면 되는 문제입니다.
행렬 곱셈이 들어가서 그런가 골4문제네요. 체감상 실버문제였습니다.
**4**
실수
B의 자료형을 long long 으로 했어야함.
잘 분할해놓고, 분할하는 과정을 두번 실행함. 한번 실행하고 그 값을 저장해서 사용했어야함.
문제 조건을 잘읽었어야함(악마의 조건이 있음)
2 1
1000 1000
1000 1000 
의 처리를 잘해줬어야함.
> [분할정복]행렬 제곱

- BOJ/10026. 적록 색약/rockmiin.py
- BOJ/10026. 적록 색약/적록색약_10026.py
- BOJ/11047.동전0/rockmiin.py
- BOJ/2206.벽 부수고 이동하기/rockmiin.py
BFS 2개로 따로따로 일반인과 색약인 사람의 개수를 세줬습니다.
> 10026. 적록 색약 & 2206. 벽 부수고 이동하기

- LeetCode/Linked_List/Remove_Duplicates_from_Sorted_List/HyeonJeong.py
정렬된 링크드 리스트의 중복 항목을 제거하는 문제
value라는 변수를 이용해서 중복된 항목이 아닌 경우는 value에 들어간 값보다 head.val의 값이 크므로 이것을 이용해서 해당 조건을 만족하는 경우에는 새로운 링크드 리스트가 만들어지고 노드들이 연결되게 하였습니다.
https://leetcode.com/problems/remove-duplicates-from-sorted-list/submissions/
> [LeetCode] Remove Duplicates from Sorted List

- LeetCode/Array/Sort_Colors/HyeonJeong.py
순서대로 빨간색, 흰색, 파란색 객체의 색상이 인접하게 정렬하는 문제
빨간색 흰색 파란색이 0,1,2로 표현된 배열이 주어져서 숫자의 오름차순 정렬을 통해서 정렬하였습니다.
https://leetcode.com/problems/sort-colors/
> [LeetCode] Sort Colors

- BOJ/2206.벽 부수고 이동하기/rockmiin.py
- BOJ/7562. 나이트의 이동/rockmiin.py
에러부분 수정했습니다. 모르고 머지를 눌러서.. 리뷰 감사합니다 !
> 2206. 벽 부수고 이동하기 [수정] && 7562. 나이트의 이동

- Algospot/QUADTREE/sAp00n.py
종만북 스터디도중에 풀이한 예제를 여기다가도 같이 공유해봅니다!
알고스팟이라는 온라인저지에 올라온 문제입니다
개인적으로는 풀이는 간단하지만 직접 푸는건 쉽지 않은 아주 좋은 문제라고 생각해요.
저는 풀면서 배운게 많아서 분할정복을 연습중이신분들은 꼭 한번 풀어보시는게 좋을꺼 같아요.
체감한 난이도는 solved.ac 기준으로 골드 4~3 정도였습니다.
> Algospot QUADTREE

- LeetCode/Array/Max_Consecutive_Ones/HyeonJeong.java
이진 배열에서 1이 연속으로 존재하는 최대 개수를 찾는 문제
for문으로 배열의 요소가 1인지 확인을 하고, 1인 경우에는 다음 인덱스들이 1이 나오지 않을 때까지 내부 for문을 돌아가고 j에 0이 나오는 경우를 만들어서 j와 i(외부 for문)의 차이 값으로 연속으로 1이 존재하는 개수를 찾게 하고, i에 j값을 주어 1이 다음으로 연속된 값을 찾을 수 있게 하였습니다.
https://leetcode.com/problems/max-consecutive-ones/submissions/
`for (int i = 0; i < nums.length; i++)`에서 for문의 i 로 연속적인 것을 확인할 때는 확인이 된 부분까지는 다시 for문을 돌리지 않게 i에 확인된 것까지의 값을 주어야 속도가 느려지지 않는다
> [LeetCode] Max Consecutive Ones

- LeetCode/Array/Intersection_of_Two_Arrays/HyeonJeong.py
두 배열의 공통된 요소를 반환하는 함수
우선 중복된 수를 제거하기 위해서 set()을 사용하고, 공통된 요소는 & 연산자로 계산될 수 있게 하였습니다.
intersection()를 사용하는 경우에도 위와 같이 계산됩니다.
https://leetcode.com/problems/intersection-of-two-arrays/
> [LeetCode] Intersection of Two Arrays

- BOJ/1389. 케빈 베이컨의 6단계 법칙/rockmiin.py
> 1389. 케빈 베이컨의 6단계 법칙 #BFS

- LeetCode/Array/Find_Common_Characters/HyeonJeong.py
- LeetCode/Array/Rotate_Array/HyeonJeong.py
Find Common Characters
문자열 배열에서 모든 문자열에 중복되어 존재하는 문자를 반환하는 문제
풀이: 문자가 중복되는 것도 포함되어서 문자열을 우선 문자로 분리하여 2차원 배열로 만들었습니다.
첫 번째 문자열을 기준으로 문자를 확인해서 모든 문자열에 존재하는 경우에는 해당 문자를 결과 리스트에 담고, 2차원 배열의 각 문자열에서 해당 문자를 지우는 방식을 사용하였습니다.
https://leetcode.com/problems/find-common-characters/
Rotate Array
배열을 오른쪽으로 k번 회전 시키는 문제 
풀이: `insert(0, 숫자)`를 이용해서 배열의 인덱스 0에 배열의 마지막 수가 넣어지게 하고, `pop()`을 통해 이용한 수를 지우는 것이 k번만큼 실행되게 하였습니다.
https://leetcode.com/problems/rotate-array/
> [LeetCode] Find Common Characters & Rotate Array

- BOJ/1946.신입 사원/rockmiin.py
그리디 문제 입니다. N의 범위가 100,000이어서 시간 복잡도가 O(nlogn)이 되어야 통과가 가능 -> 정렬 알고리즘을 생각해서 구현하였습니다.
> 1946. 신입사원 

- LeetCode/Array/Squares_of_a_Sorted_Array/HyeonJeong.java
정렬된 숫자의 제곱 배열을 반환하는 문제
풀이: for문으로 배열의 각 숫자를 제곱하고, `Arrays.sort(배열)`을 이용해서 정렬시킨 후 해당 배열을 반환하게 하였습니다.
https://leetcode.com/problems/squares-of-a-sorted-array/
> [LeetCode] Squares of a Sorted Array

- BOJ/1002.터렛/6047198844.cpp
- BOJ/14727.퍼즐 자르기/6047198844.cpp
- BOJ/2553.마지막 펙토리얼 수/6047198844.cpp
터렛
**1**
출처 : 백준
https://www.acmicpc.net/problem/1002
**2**
input : 좌표 / 원의 반지름
output : -1 / 1 / 2 / 0
**3**
풀이 아이디어
두 원의 접점의 개수를 셉니다.
중학교 수학문제인데요.
두점에서 만나는 경우
r - r' < d < r + r'
한점
r' - r = d || r' + r = d
만나지않음
r' - r > d || r' + r < d 
입니다.
퍼즐 자르기
**1**
출처 : 백준
https://www.acmicpc.net/problem/14727
**2**
input : 히스토그램
output : 가장 작은 직사각형
**3**
풀이 아이디어
복습겸 다시 풀었습니다.
마지막 팩토리얼 수
**1**
출처 : 백준
https://www.acmicpc.net/problem/2553
**2**
input : N
output : 팩토리얼 0이 아닌 마지막 수
**3**
풀이 아이디어
생각하기가 조금 까다로웠는데요.
우선 20000!은 계산 불가능합니다. 따로 곱셈을 구현해야하고 0.3초만에 구한다는 보장도 없습니다.
우리가 구하고자하는것은 마지막 수입니다. 따라서 모든수를 곱할필요가 없습니다.
팩토리얼을 곱하고 일정부분만 때서 다시 곱해줘도 마지막수를 구할수있습니다.
주의해야할것은 일정부분땔때 넉넉히 때줘야합니다.
예를들어 한자리수만 때어내면 이런 문제점이 발생합니다.
1! = 1
2! = 2
3! = 6
4! = 4
5! = 0
6! = 0
....
따라서 적당히 큰값. 하지만 너무 크지 않은 수를 때어야합니다.
> [분할정복]퍼즐자르기/[수학]마지막 팩토리얼 수/[수학]터렛

- LeetCode/Linked_List/Reverse_Linked_List_II/HyeonJeong.py
n부터 m까지의 요소들의 위치를 반전시켜 링크드 리스트를 반환하는 문제
풀이
1. 주어진 링크드 리스트를 nlist에 요소들을 담았다. 
2. 요소가 범위(n <= 요소 <= m)에 해당하면 범위의 중간을 기준으로 수가 전환되게 하였다.
3. 만들어진 nlist의 요소로 링크드 리스트를 만들고, 이 리스트를 반환하였다.
https://leetcode.com/problems/reverse-linked-list-ii/
> [LeetCode] Reverse Linked List ll

- BOJ/2042.구간 합 구하기/6047198844.cpp
- BOJ/2217.로프/6047198844.cpp
- BOJ/2517.달리기/6047198844.cpp
- 알고스팟/와일드카드/6047198844.cpp
와일드카드
**1**
출처 : 알고스팟
**2**
input : 패턴 / 문자열들
output : 패턴에 맞는 문자열들
**3**
풀이 아이디어
DP.
완전탐색으로 구합니다. 다만 이 방법에 memoization이 추가되어서 DP가 됬네요. DP를 사용할수있는 근거는. 우선 참조 투명성을 만족합니다. 참조 투명성이란, input이 동일할경우 output도 항상 동일합니다. 참조 투명성을 만족하기때문에 DP를 사용가능했습니다.
구간 합 구하기
**1**
출처 : 백준
**2**
input : 구간 / 바뀌는지, 구간합을 구하는지
output : 구간합을 구할경우. 해당 구간합을 출력합니다.
**3**
풀이 아이디어
인덱스 트리.
세그먼트 트리로도 구할수있습니다. 세그먼트 트리를 공부했었긴했는데 구현이 너무 귀찮아서. 인덱스트리를 사용했습니다.
달리기
**1**
출처 : 백준
**2**
input : 달리기 능력
output : 달리기 등수
**3**
풀이 아이디어.
달리기 능력순대로 정렬합니다. 즉 느린 순부터, 빠른 순까지 정렬하고 각 인덱스를 인덱스 값으로 가집니다.
인덱스 트리에서 인덱스 범위를 실력값이 아닌 N으로 두어야합니다. 아니면 용량이 초과됩니다. 따라서 정렬한것입니다.
처음의 정렬되기 전의 인덱스 배열을 처음부터 끝까지 돌면서 값을 1로 변경하고 덧샘합니다.
현재 등수 - n-1의 누적합이 최선의 등수를 뜻하게 됩니다.
로프
**1**
출처 : 백준
**2**
input : 로프길이
output : 버틸수있는 최대 무개
**3**
풀이 아이디어
정렬후 (배열의 크기- 해당 인덱스) * 값의 …
> [DP] 와일드카드 / [인덱스 트리] 구간 합 구하기 / [인덱스 트리] 달리기 / [정렬] 로프

- BOJ/10773.제로/s2uyeoii.c
입력 값이 0이면 그 전 값을 지우고, 아니면 그 값을 스택에 넣는 문제입니다.
지우는 건 pop, 삽입은 push 함수를 사용합니다. 
요즘 자료구조 공부중이라 풀어봤습니다.
> [BOJ]10773.제로_c

- BOJ/2156.포도주 시식/rockmiin.py
> 2156.포도주 시식 

- LeetCode/Array/Array_Partition_I/HyeonJeong.java
정수 배열의 요소 2개씩 만들어진 그룹이 둘 중의 작은 수 값을 가질 때, 그룹들의 합계가 최대가 되는 합계 반환하는 문제
풀이
정렬한 배열에서 순서대로 2개씩 그룹을 만들면 그룹의 합계를 최대로 만들 수 있어서
배열을 정렬하고, 그룹이 만들어진 수 중 앞의 수가 더 작으므로 0, 3, ... len(배열)-1까지의 인덱스들의 합을 구해서 반환하게 함
https://leetcode.com/problems/array-partition-i/
> [LeetCode] Array Partition I

- BOJ/1009.분산처리/6047198844.cpp
- BOJ/1032.명령 프롬프트/6047198844.cpp
- BOJ/11404.플로이드/6047198844.cpp
- BOJ/1219.오민식의 고민/6047198844.cpp
- BOJ/1738.골목길/6047198844.cpp
210125
오민식의 고민
**1**
출처 : 백준
**2**
input : 도시의 수 / 시작 도시 / 도착 도시  / 교통 수단의 개수
output : 도착 도시에 도착했을때의 정보
**3**
풀이 아이디어
음수가 존재합니다. 게다가 경로문제니 이건 벨만-포드로 접근해야합니다.
골목길도 동일한 아이디어 입니다.
두문제 공통으로 체크해줘야하는게 있습니다. 벨만-포드에서 한점에서 모든점으로 갈때 negative cycle이 존재하면, 경로는 존재하지 않습니다. 하지만 negative cycle이 존재하더라도 특정한 점은 negative cycle의 영향을 받지 않을수있습니다. 그 부분을 BFS알고리즘으로 체크해야합니다.
또 체크해야할부분은 최대 나올수있는 음수(양수)는 -CN^2입니다. N의 절대값이 1,000,000이기때문에 int의 범위를 넘어버립니다. 따라서 long long으로 선언이 필요합니다.
마지막으로 체크해야할부분은 해당 지역까지 갈수있는지 체크해야합니다.
골목길
**1**
출처 : 백준
**2**
input : 골목길/ 골목길 개수 / 금품의 양
output : 최적의 경로
**3**
풀이 아이디어
오민식의 고민과 같습니다. 데이터에러가 좀있는것같습니다. (처음에 잘못풀었는데 맞게 나오네요..)
분산처리
**1**
출처 : 백준
**2**
input : 테스트케이스수 /  a^b
output : 마지막 데이터가 처리될 컴퓨터의 번호
**3**
풀이 아이디어
쉬운 문제인데 답이 바로 안나와서 좀 당황했습니다.
모든 제곱을 할필요없이 1의 자리 숫자만 구하면 되므로. 1의 자리수만 계속 …
> [벨만-포드]오민식의 고민 / [벨만-포드]골목길 / [수학]분산처리 / [구현]명령 프롬프트 /[플로이드] 플로이드

- programmers/난이도별/level02.이진_변환_반복하기/README.md
- programmers/난이도별/level02.이진_변환_반복하기/dkdlelk99.py
`format(value, 'b')` 생각이 안나서 구글링 해봤다. 외우기.
> [Programmers Lv.02] 이진 변환 반복하기

- LeetCode/Math/Distribute_Candies_to_People/HyeonJeong.java
첫 번째 사람부터 1개의 사탕을 주기 시작해서 1개씩 사탕을 늘려서 다음 사람에게 주고, 마지막 사람에게 주고도 사탕이 남은 경우에는 다시 첫 번째 사람에게 사탕을 나눠준 사탕의 배열을 반환하는 문제
풀이
n으로 나눠줄 사탕의 개수를 하나씩 증가시키고, i로 마지막 사람에게 주고 난 후에는 다시 첫 번째 사람에게 다시 줄 수 있게 함.
while문으로 나눠준 만큼 사탕을 줄여서 사탕이 없을 때까지 사탕을 나눠주게 함. 
https://leetcode.com/problems/distribute-candies-to-people/
> [LeetCode] Distribute Candies to People

- BOJ/10159.저울/6047198844.cpp
- BOJ/1613.역사/6047198844.cpp
- BOJ/2437.저울/6047198844.cpp
[플로이드]저울
**1**
출처 : 백준
**2**
input : 물건 / 비교결과
output :  비교결과를 알수없는 물건의 개수.
**3**
풀이 아이디어
플로이드 알고리즘을 이용하여. 한 점에서 다른점까지 이동가능한지에 대해 확인합니다.
한점에서 갈수없는 부분에 대하여, 역으로도 갈수없는지 확인합니다. 역으로도 갈수없다면 비교 결과를 알수없습니다. 
[플로이드]역사
**1**
출처 : 백준
**2**
input : 연대기
output : 역사 순
**3**
풀이 아이디어
위 문제와 같습니다.
[그리디]저울 
**1**
출처 : 백준
**2**
input : 저울
output : 측정할수없는 양의 정수의 무게중 최소값
**3**
풀이 아이디어
추를 1 1 3 7 8 이라고 합시다.
처음에는 아무것도 없으니 최대 만들수있는 무게는 0입니다.
추무게 1을 손에 쥡니다. 만들수있는 무게는 0 / 1입니다.
추무게 1을 손에 쥡니다. 만들수있는 무게는 0 / 1 / 2 입니다.
추무게 3을 손에 쥡니다. 만들수있는 무게는 0 / 1 / 2 / 3 / 4 / 5 입니다.
추무게 7을 손에 쥡니다. 만들수있는 무게는 0 / 1 / 2 / 3 / 4 / 5 / X / 7 / 8 ...... / 12 입니다.
6을 만들수없습니다. 즉. 현재 만들수있는 무게 + 1 보다 다음 고르는 추의 무게가 크다면 반드시 공백이 생길수밖에 없는데, 그 공백의 최소값은 현재 만들수있는 무게 + 1 입니다. 위의 예시에서도 6이 됩니다.
> [플로이드]저울 / [그리디]저울 / [플로이드]역사

- LeetCode/String/Make_The_String_Great/HyeonJeong.py
주어진 문자열에서 연속된 인덱스에 같은 알파벳의 대문자와 소문자인 경우 두 문자를 제거해서 최소로 축소한 문자열을 반환하는 문제
풀이
문자열의 문자를 리스트로 변환시켜서 문자들의 제거가 자유롭게 함
아스키코드를 사용해 인접한 인덱스의 차이가 32가 되는 경우에는 리스트에서 해당 인덱스를 제거되게 함
두 문자가 제거된 후에는 현재 인덱스의 앞 인덱스와 두 문자 뒤의 인덱스가 같은지 확인하기 위해서 (현재 인덱스 -1)한 상태가 확인되게 함
https://leetcode.com/problems/make-the-string-great/
> [LeetCode] Make The String Great

- BOJ/3055.탈출/rockmiin.py
물이 이동 예정인 좌표를 고슴도치가 이동할 수 없는 것을 어떻게 구현하는지가 중요했던 것 같다. 처음에는 단순히 water_bfs 먼저 실행을 하면 될 것이라고 생각을 했지만, 그렇게 구현하면 같은 시간대에 고슴도치가 이동할 수 있는 좌표를 *로 덮어버려 갈 수 없는 좌표로 만들어 준다. 그래서 bfs를 먼저 실행하여 고슴도치가 갈 수 있는 경로를 now에 담아 준 다음에 water_bfs를 사용하여 물이 이동할 예정인 경로의 adj 값을 *로 바꿔주었다. 그런 다음 다시 bfs에 들어가서 pop해진 값의 adj값이 *이면 물이 이동할 예정인 좌표이므로 제거해주었다.
> [BOJ]3055. 탈출

- LeetCode/Greedy/Assign_Cookies/HyeonJeong.java
- LeetCode/String/Make_The_String_Great/HyeonJeong.py
각 어린이가 만족하는 쿠키의 최소 크기가 담긴 g와 쿠키 크기가 담긴 s 배열을 이용해 만족하는 아이의 수를 최대로 하는 문제
풀이
1. 각 배열들을 정렬해서 s가 줄 수 있는 g의 최대 크기의 인덱스를  찾음
2. s의 최대 크기부터 g에게 줄 수 있는지 확인해서 줄 수 있는 경우에는 다음 g값과 s값을 비교하고, 줄 수 없는 경우에는 현재 s값과 다음 g값을 비교할 수 있게 함
https://leetcode.com/problems/assign-cookies/submissions/
> [LeetCode] Assign Cookies

- BOJ/11403.경로 찾기/rockmiin.py
인접 행렬을 arr로 받아와서 adj 리스트에 각 노드에서 인접한 노드의 index를 넣어주고, 시작 노드와 종료 노드의 정보를 bfs 함수로 넘겨 줘서 종료 노드에 도착하게 되면 인접 행렬 arr2의 값을 1로 바꿔주고 return 해주는 식으로 구현을 하였습니다. bfs 함수는 (0, 0) ~ (n-1, n-1)까지 반복하여 호출이 됩니다.
시작 노드와 종료 노드가 같을 때 처리를 해주는 것 중요했습니다. 이 때는 시작 노드와 인접한 노드 정보를 q에 넣어주어 그 노드들에서 시작하여 종료 노드에 도달하게 되면 arr2 값을 1로 변경해주는 식으로 구현을 하였습니다.
> 11403.경로 찾기

- 알고스팟/합친 LIS/6047198844.cpp
**1**
출처 : 알고스팟
**2**
input : 두개의 수열
output : 합친 수열의 증가 부분 수열
**3**
풀이 아이디어
두개의 수열을 따로 따로 증가 수열을 구해서 합치는것이 아니라 처음부터 합친 수열의 증가 부분 수열을 구해야합니다.
> [DP] 합친 LIS

- LeetCode/Array/Sort_Array_By_Parity_II/HyeonJeong.java
배열의 요소가 홀수인 경우는 홀수 인덱스에, 짝수인 경우는 짝수 인덱스에 값을 위치하게 만드는 문제
풀이
1. 정리된 홀수와 짝수의 개수가 담길 변수 odd, even을 선언
2. for문으로 배열의 요소가 홀수와 짝수 중 무엇인지 확인하여 위의 변수를 이용해 알맞은 인덱스에 위치하게 만듦
https://leetcode.com/problems/sort-array-by-parity-ii/
> [LeetCode] Sort Array By Parity II

- LeetCode/Greedy/Can_Place_Flowers/HyeonJeong.java
꽃이 일부가 심어진 화단에서 인접하지 않은 자리에 주어진 꽃을 모두 심을 수 있는지 확인하는 문제
풀이
1. 심을 꽃이 있는지 확인해서 없는 경우는 바로 true를 반환
2. 한 자리만 확인하는 경우, 한 자리에 심겨진 꽃이 없고 심어야 할 꽃이 1개인 경우만 true
3. 두 자리를 확인하는 경우, 맨 앞이나 맨 뒤 자리에 꽃을 심을 때
4. 세 자리를 확인하는 경우, 위에서 확인한 자리 외의 나머지 자리에 꽃을 심을 때
https://leetcode.com/problems/can-place-flowers/submissions/
> [LeetCode] Can Place Flowers

- BOJ/1260.DFS와 BFS/s2uyeoii.c
> [BOJ]DFS와 BFS_c언어

- 알고스팟/QUANTIZE/6047198844.cpp
- 알고스팟/원주율 외우기/6047198844.cpp
**1**
출처 : 알고스팟
**2**
input : 숫자문자열
output : 난이도
**3**
풀이 아이디어
dp함수는 인덱스를 받습니다.
인덱스로 남아있는 문자열의 길이를 얻을수있는데 남아있는 문자열의 길이가 2이하일경우에는 최대값을 리턴합니다. (3/4/5로 쪼갤수있으므로)
아닌 경우에는 3/4/5개의 문자열의 난이도를 구하고 각각에 대해 dp(index+3),do(index+4),dp(index5)를 더합니다.
> [DP]원주율 외우기 / [DP] QUANITIZE

- LeetCode/Queue/Number_of_Recent_Calls/HyeonJeong.py
최근 3000밀리 초 이내에 요청된 개수를 계산하는 클래스
풀이
1. 객체가 해당하는 시간 이내의 수를 저장하고 있을 리스트를 생성
2. t != 0인 값을 가지므로 처음 객체가 만들어지면 t를 0으로 설정해서 해당 경우는 ping 함수에서 null 반환
3. ping 함수 내에서는 범위에 해당하는 시간들을 담을 새로운 리스트에 저장하고, 이에 대한 길이를 반환
https://leetcode.com/problems/number-of-recent-calls/
처음으로 푼 큐 문제인 것 같은데, 이렇게 풀어도 되는지 확인 부탁드립니다!
> [LeetCode] Number of Recent Calls

- programmers/카카오 개발자 겨울 인턴십 2019/불량사용자/불량사용자.py
- programmers/카카오 개발자 겨울 인턴십 2019/크레인 인형뽑기 게임/크레인 인형뽑기 게임.py
- programmers/카카오 개발자 겨울 인턴십 2019/튜플/튜플.py
시간 제한 두고 구현이 되는 대로 푼 거라 허점이 조금 많을 수 있습니다.  나름 수정한다고 수정은 했는데
더 나은 풀이나 피드백 주시면 감사하겠습니다 ! 나머지 문제도 풀이 예정입니다.
> 카카오 개발자 겨울 인턴십 2019

- LeetCode/Queue/Design_Circular_Deque/HyeonJeong.py
순환 양방향 큐 구현을 설계하는 문제
풀이
- 생성자에 항목이 저장될 self.q = deque()를 만듦
- 항목의 추가에는 크기 k를 넘었는지 확인하는 isFull()를 이용
- 항목의 제거에는 크기가 0이 아닌지 확인하는 isEmpty()를 함수를 이용
https://leetcode.com/problems/design-circular-deque/submissions/
> [LeetCode] Design Circular Deque

- 알고스팟/비대칭 타일링/6047198844.cpp
- 알고스팟/장마가 찾아왔다/6047198844.cpp
장마가 찾아왔다
**1**
출처 : 알고스팟
**2**
input : m , n
output : m일 전까지 n미터 이상 기어올라갈 확률
**3**
풀이 아이디어
완전탐색으로 모든 경우의 수를 예측해보고 DP로 변환합니다. 변환시에 최대한 과거의 정보를 줄입니다. 
경우의 수를 계산하기 위해서 선택지를 만들어야하는데 이 선택지는 두가지 속성을 만족해야합니다.
1. 모든 경우는 이 선택지에 포함되어야합니다.
2. 어떤 경우도 두 개 이상의 선택지에 포함되지 않습니다.
**4**
알아낸것
주의해야할점은 C++ 에서 정밀도 조정이 있어야합니다.
cout.precision(11); 이 코드가 정밀도 조정을 해주는 역할을 했습니다.
memset으로 double이 초기화 되지않는다는 사실도 알았네요.
비대칭 타일링
**1**
출처 : 알고스팟
**2**
input : 타일의 길이
output : 비대칭 타일의 경우의수
**3**
풀이 아이디어
경우의 수를 생각해봤습니다.
저는 모든 경우의 수에서 대칭인경우의 수를 뺐습니다.
대칭인 경우는 두가지가 존재합니다.
홀수인 경우, 정가운데 세로모양의 타일이 있고 양쪽으로 타일들이 배치되는 경우가 있습니다.
짝수인 경우, 정가운데 세로모양의 타일이 있고 양쪽으로 타일들이 배치되는 경우와. 가로2개의 타일이 있고 양쪽으로 타일이 배치되는 경우가 있습니다.
**4**
실수한점
각 경우의 수에서 빼는 계산을 할때 MOD를 더해줘야되네요. 그리고 MOD를 더했을때 오버플로가 날수있으니 자료형도 유의해야하고요. MOD를 더하는 이유는 MOD와 같거나 큰 값을 가지는 경우의 수는 …
> [DP]장마가 찾아왔다 / [DP] 비대칭 타일링

- LeetCode/Array/Keyboard_Row/HyeonJeong.py
- LeetCode/Greedy/Car_Pooling/HyeonJeong.py
키보드의 한 행에 있는 알파벳 문자들만 이용해 만들 수 있는 단어를 반환하는 문제
풀이
1. 각 행에 존재하는 단어들을 문자열로 리스트를 만듦
2. 단어를 문자로 쪼개서 첫 번째 문자가 어떤 행에 속하는지 확인해서 다른 문자들 중 다른 행에 속한 문자가 있는지 확인
https://leetcode.com/problems/keyboard-row/
> [LeetCode] Keyboard Row & Car Pooling

- LeetCode/Greedy/Is_Subsequence/HyeonJoeng.py
t 문자열의 순서를 유지한 상태로 문자를 제거해서 s문자열을 만들 수 있는지 확인하는 문제
풀이
1. s와 t를 리스트로 만들어서 t가 s의 문자와 다른 경우에는 문자를 제거
2. s가 다 존재하는 경우에 while이 끝나므로 t의 문자 중에서 slist의 길이와 같은 인덱스까지만 비교해서 결과 반환
3. 
https://leetcode.com/problems/is-subsequence/submissions/
> [LeetCode] Is Subsequence

- BOJ/11066.파일 합치기/6047198844.cpp
- BOJ/5557.1학년/6047198844.cpp
파일 합치기
**1**
출처 : 백준
**2**
input : 파일비용
output : 파일을 합치는데 드는 비용의 최소값
**3**
풀이 아이디어
파일 C1 , C2 , C3 , C4를 합칠때 드는 비용의 경우의 수를 구해보겠습니다.
(C1) + (C2 + C3 + C4)
(C1 + C2) + (C3 + C4)
(C1 + C2 + C3) + C4
어떠한 순서로 합치건 최종단계는 위의 세가지 단계가 됩니다.
C2와 C3가 합쳐진 결과가 C1하고 합쳐진다고 했을때 최종 단계는 3번째가 될것이고.
C2와 C3가 합쳐진 결과가 C4하고 합쳐진다고 했을때 최종 단계는 1번째가 될것입니다.
즉 K를 그룹을 두개로 나누는수라고 했을때 K의 범위는 인덱스 0에서부터 인덱스 2까지 입니다 (C1~C3)   
그러면 다음과 같은 점화식을 구할수있습니다.
dp[i][j] = dp[i][k] + dp[k][j] + sum
이때 sum은 i~j의 합을 의미하는데 예시에서는
sum = C1 + C2 + C3 + C4 이됩니다.
이것을 더해주는 이유는 dp[i][k] + dp[k][j]의 합을 더해줘야하는데 이 합은 무조건 i~j구간의 합이기 때문입니다.
i와 j가 같을경우 그룹을 나눌수없기때문에 return 값은 0이됩니다. 다시말하자면 
dp[i][j]은 i-j 구간에서 파일를 합칠때 드는 최소 비용인데, i-j가 같을 경우에 파일의 개수가 1개이기때문에 합칠수가없다. 따라서 합치는데 드는 비용이 0입니다.
1학년
**1**
출처 : 백준
**2**
input : 수, 정답
output : 수식으로 만들수 있는 정답의 경우의 수 …
> [DP] 파일합치기 / [DP]1학년

- programmers/난이도별/level02.수식_최대화/rockmiin.py
정규 표현식을 사용해보았습니다. 문자열 처리에 편리한 것 같네요
> level02. 수식 최대화

- LeetCode/Greedy/Remove_Covered_Intervals/HyeonJeong.py
간격이 담긴 리스트에서 다른 간격에 포함되는 간격은 제거하는 문제
풀이
두 개씩 모든 간격이 비교될 수 있게 for문과 while문을(수정된 리스트의 해당 인덱스를 다시 검사할 수 있게) 이용
https://leetcode.com/problems/remove-covered-intervals/
> [LeetCode] Remove Covered Intervals

- BOJ/17070.파이프 옮기기1/6047198844.cpp
**1**
출처: 백준
**2**
input : 범위 / 벽이있는 위치
output : 경우의 수
**3**
풀이 아이디어
완전탐색으로 가능한 수를 구했습니다. 결국에는 겹치는 부분이 있습니다. 가로,세로,대각선이든 돌리게 되면 다른 모양으로 변형이되고 결국 겹치는 값이 생긴다는 뜻이죠. 메모이제이션을 적용하였습니다.  360도 회전 같은건 경우의 수에 없기 때문에 범위를 찾는데 있어 파이프의 오른쪽값에만 신경썻습니다.
> [DP]파이프 옮기기1

- LeetCode/Array/Arranging_Coins/HyeonJeong.java
n개의 동전으로 만들어지는 계단의 수를 구하는 문제
풀이
계단을 1층씩 쌓으면 시간 초과가 발생 -> 이진 탐색을 이용해서 탐색의 범위 축소
https://leetcode.com/problems/arranging-coins/solution/
> [LeetCode] Arranging Coins

- 알고스팟/조세푸스 문제/6047198844.cpp
**1**
출처 : 알고스팟
**2**
input : 사람수
output : 마지막 살아남는 두 사람의 번호
**3**
풀이 아이디어
풀어봤었던 문제인데요. 종만북 18과에 나와서 풀게되었네요. 
포인터 역할을 하는 반복자를 이용합니다.
list라는 자료구조를 사용한 이유는 중간에 삽입/삭제가 일어날경우 효율적인 자료구조이기 때문입니다.
list.end()를 지우지 않도록 조심해야합니다. 반복자가 list.end()로 이동했을때, list.begin()으로 끌어다줘야 list.end()를 지우지 않습니다. 반복자가 list.end()로 이동하는 경우는 현재 반복자를 지운후 다음을 가리키는 erase 연산 뒤, 그리고 반복자를 증가하는 연산에서 체크를 해줘야합니다.
> [자료구조]조세푸스 문제

- LeetCode/Linked_List/Swap_Nodes_in_Pairs/HyeonJeong.java
인접한 두 노드를 교환한 것의 head를 반환하는 문제
풀이
다음의 교환할 노드가 null이 아닐 때 while문이 돌아가게 함
while문 : 
1. 변수에 인접한 두 노드 중 앞 노드의 값을 넣음
2. 현재 노드에 다음 노드의 값을 넣음
3. 다음 노드를 현재 노드로 만들고, 현재 노드에 변수를 넣음
4. 마지막으로 교환될 다음 노드를 현재 노드로 만듦
https://leetcode.com/problems/swap-nodes-in-pairs/
> Swap Nodes in Pairs

- LeetCode/String/Maximum_69_Number/HyeonJeong.py
최대 1개의 숫자를 변경할 수 있는 문제에서 최대 숫자 반환 (6 -> 9, 9 -> 6으로 변경)
풀이
앞에서부터 숫자를 확인해서 6이 가장 먼저 나오는 경우에 9로 변경하는 것이 가장 큰 수를 만들 수 있음
1번 이하로 변경 할 수 있으므로 1번 변경하게 되는 즉시 해당 값을 반환하게 함
https://leetcode.com/problems/maximum-69-number/
> Maximum 69 Number

- BOJ/2468.안전 영역/rockmiin.py
BFS로 구현했습니다. 사전에 제일 깊은 길이를 찾은 후 그 길이만큼 탐색을 하여 각 길이마다 나올 수 있는 최대 영역의 수를 비교하여 큰 값을 res에 넣어주는 방식으로 구현했습니다.
> 2468.안전 영역 #BFS

- LeetCode/Linked_List/Remove_Linked_List_Elements/HyeonJeong.java
- LeetCode/Linked_List/Swap_Nodes_in_Pairs/HyeonJeong.java
val과 연결 리스트 노드의 값이 같은 경우
노드 제거
1. 첫 노드
-> 처음 주어지는 연결 리스트가 다음 노드부터 되게 함
2. 나머지 노드 
->  다음 노드(현재 노드의 next)가 제거되어야 할 노드인 경우로, 다음 노드의 다음 노드를 다음 노드를 가리키는 변수에 넣음
https://leetcode.com/problems/remove-linked-list-elements/
> Remove Linked List Elements

- LeetCode/Array/Fair_Candy_Swap/HyeonJeong.java
캔디바를 교환해서 서로 같은 양의 캔디를 얻게 될 때 각자의 교환하는 캔디바를 리스트로 반환하는 문제
풀이
1. 주어진 개인 당 캔디의 개수를 구함
2. 양쪽의 변경된 캔디 개수가 같아질 수 있는지 확인
https://leetcode.com/problems/fair-candy-swap/submissions/
> Fair Candy Swap

- BOJ/11052. 카드 구매하기/6047198844.cpp
- BOJ/11054.가장 긴 바이토닉 부분 수열/6047198844.cpp
가장 긴 바이토닉 부분 수열
**1**
출처 : 백준
**2**
input : 수열
output : 가장 긴 바이토닉 부분 수열의 길이
**3**
풀이 아이디어
좌측에서 시작, 긴 부분 수열을 구하고
우측에서 시작, 긴 부분 수열을 구해서
각각의 길이를 더한뒤 1을 제거합니다. LIS의 기본개념만 생각해보면 풀수있네요.
카드 구매하기
**1**
출처 : 백준
**2**
input : 카드
output : 민규가 카드 N개를 갖기 위해 지불해야 하는 금액의 최댓값
**3**
최적 부분 구조를 만족합니다.
따라서 4팩의 카드가 주어졌을때. 카드 4개를 갖기 위해 지불해야 하는 금액의 최댓값은 다음중 최대값입니다.
카드4팩 / 카드3팩 +카드1개일때 얻을수있는 최대값 / 카드2팩 + 카드2개일때 얻을수있는 최대값 / 카드 1팩 + 카드3개일때 얻을 수 있는 최대값
> [DP]가장 긴 바이토닉 부분 수열 / [DP] 카드 구매하기

- BOJ/4948.베르트랑 공준/6047198844.cpp
**1**
출처 : 백준
**2**
input : n
output : n초과 2n이하의 소수 개수
**3**
풀이 아이디어
소수를 구하고 n초과 2n이하 소수의 개수를 반환합니다.
> [소수]베르트랑 공준

- BOJ/1436.영화감독 숌/6047198844.cpp
- BOJ/2798.블랙잭/6047198844.cpp
영화감독 슘
**1**
출처 : 백준
**2**
input : N
output : N번째 연속인 666의 수
**3**
시간을 먼저 확인했어야한다. 주어진 시간은 2초다. 즉 약 2억번의 연산이 가능하다.
일정한 규칙을 찾으려고 시도했다. 규칙은 발견했어도 이걸 코드로 짜기에는 불규칙적이였다.
그것보다 더 간단한 방법은 그냥 연속된 6의 개수를 세는것이다. 즉 컴퓨터를 믿는것이다.
최대 세어 봤자 XXXXX666 의 경우 X에 0부터 10000까지 다 들어가도 천만이라는 숫자 안에 다 셀수있다. 
하지만 위와 같은 경우와 XXXX666X과 같은 경우의 수도 있기때문에 그 훨씬 이전에 끝난다.
6의 개수를 찾는 연산은 최대 8번 반복되므로 크게잡아 8천만이라는 연산횟수를 한다고 가정해도 연산의 횟수가 1억안이라는것을 알수있다.
블랙잭
**1**
출처 : 백준
**2**
input : 카드 , N, M
output : M에 가장 가까운 3개 카드의 합
**3**
코드에서 순서가 정말 중요했네요.
//index + 1의 선택을 고려하지않는수. 이미 조건 만족. 더이상 고려할것이없다 -> base case
if (cnt == 0 && sum <= M)
return sum;
//idx+1을 선택했을때의 수와 idx+1을 선택하지 않았을때의 수를 고려하는 수.
if (cnt < 0 || sum > M || idx + 1 >= N)
return 0;
위의 경우의 수가 항상 선이 되어야합니다. 아래는 단지 예외 처리일뿐이고요. index + 1의 선택을 고려하지않는수보다 아래의 경우의 수가 올라가게되면 답이 …
> [완전탐색]영화감독 슘 / [완전탐색] 블랙잭

- LeetCode/Linked_List/Palindrome_Linked_List/HyeonJeong.java
연결 리스트가 회문인지 확인하는 문제
풀이
1. 연결 리스트의 값들이 순서대로 담기 위해 ArrayList 이용
2. 넣어진 값의 개수(len)를 이용해서 중간을 기준으로 양 값이 같은지(회문) 확인
https://leetcode.com/problems/palindrome-linked-list/
> Palindrome Linked List

- BOJ/14888.연산자 끼워넣기/6047198844.cpp
- BOJ/7568.덩치/6047198844.cpp
덩치
**1**
출처 : 백준
**2**
input : 키 . 몸무게
output : 덩치 등수
**3**
풀이 아이디어
N=50입니다. 완전탐색으로 가능한 범위입니다.
연산자 끼워넣기
**1**
출처 : 백준
**2**
input : 숫자 / 연산자 수
output: 최소 / 최대 
**3**
2<=N<=11
-> 연산자의 조합 : 10! < 1억
> [완전탐색]덩치 / [완전탐색]연산자 끼워넣기

- BOJ/16234.인구 이동/rockmiin.py
처음에는 그룹을 찾을 때마다 adj값을 변경해주는 식으로 구현을 하였더니 틀렸습니다. 이 문제는 한 번 인구 이동을 할 때 여러 개의 그룹을 한 번에 값을 변경해주는 식으로 구현을 해줘야 했던 것 같습니다. BFS를 통해서 그룹을 찾아준 뒤에 res에 넣어주고 sum 값은 cum에 넣어준 다음에 평균 값으로 한꺼번에 변경해줍니다. 변경이 끝난 뒤에 cnt를 해주는 식으로 값을 도출해줍니다. 이 때 res값이 비어있다면 변경된 값이 없다는 의미이므로 break를 해주는 식으로 구현을 해주었습니다. 추가적으로 n과 m의 값이 작기 때문에 이런 식으로 매번 탐색하는 식으로 구현을 할 수 있었던 것 같습니다. 코드를 조금 두서없이 짠 것 같아 조언해주시면 감사하겠습니다 !
> 16234.인구 이동

- LeetCode/Math/Divisor_Game/HyeonJeong.java
교대로 게임을 해서 시작한 사람이 게임을 이기면 True, 지면 False를 반환하는 문제
풀이
N이 1이 될 때까지 for문으로 N이 나눠지는 값(1 ~ N-1)을 찾고, N을 N-(나눠지는 값)으로 변경시키는 것을 반복
https://leetcode.com/problems/divisor-game/submissions/
> Divisor Game

- BOJ/5639.이진 검색 트리/6047198844.cpp
- 알고스팟/너드인가, 너드가 아닌가 2/6047198844.cpp
이진 검색 트리
**1**
출처 : 백준
**2**
input : 이진 검색트리를 전위 순회 한것.
output : 이진 검색트리를 후위 순회 한 출력
**3**
풀이 아이디어
후위 순회 함수의 정의는
후위 순회 함수(전위 순회 한것)
루트 = 전위 순회 한것의 첫번째 인덱스
루트자식오른쪽값인덱스 = 루트보다 큰 인덱스중 가장 작은 인덱스 
후위 순회함수(두번째 인덱스 이상 , 루트자식오른쪽값인덱스 미만 인덱스)
후위 순회함수(루트자식오른쪽값인덱스, 전위 순회 한것 끝)
루트 출력
너드인가, 너드가 아닌가2
**1**
출처
알고스팟
**2**
input : 너드 x,y
output : 너드의 수
**3**
풀이 아이디어
문제 수를 x라고 하고 라면 그릇 수를 y라고 합시다.
어떤 노드를 추가하고자 할때 검사할것은 다음과 같습니다.
자신의 노드 x보다 바로 큰 x의 y가 작은 경우 추가 가능합니다.
자신의 노드 x보다 바로 큰 x의 y가 큰 경우 추가 불가능합니다. 그 이유는 x와 y 둘다 작기 때문입니다.
추가 가능한경우. 제거하는 경우를 생각해야합니다.
추가하고자 하는 x보다 작은데 y가 작다면 제거해야합니다. 끝까지 탐색해야겠죠.
> [트리]이진 검색 트리 / [트리] 너드인가, 너드가 아닌가2

- LeetCode/Array/Richest_Customer_Wealth/HyeonJeong.java
돈이 있는 금고가 2차원 배열이고 한 행마다 한 사람일 때, 가장 부자인 사람의 금액을 반환하는 문제
풀이
1. 배열의 행의 길이 만큼의 배열을 생성
2. for문을 통해 금고의 담긴 모든 금액을 합산
3. 결과가 최대값이 될 수 있게 if문으로 더 큰 값으로 변경
https://leetcode.com/problems/richest-customer-wealth/
> Richest Customer Wealth

- BOJ/2108.통계학/6047198844.cpp
- 알고스팟/변화하는 중간 값/6047198844.cpp
통계학
**1**
출처 : 백준
**2**
input : 수
output
산술평균, 중앙값, 최빈값, 범위
**3**
풀이 아이디어
문제의 조건에 맞게 각각을 구합니다. 반올림에 주의해야할것같습니다.
변화하는 중간값
**1**
출처 : 알고스팟
**2**
input : n , a , b
output : 자체 생성값으로 만든 배열의 중간값
**3**
풀이 아이디어
우선 배열을 둘로 쪼개어 생각합니다.
left와 right 배열로 나누어진다고 가정하고, right배열의 크기는 left와 같거나 left보다 1개 크다고 가정합시다.
이때 left의 최대 원소는 right의 최소 원소보다 작습니다.
left는 최대힙, right는 최소 힙으로 구현합니다.
삽입하고자하는 숫자를 ins_number이라고 하겠습니다.
left배열의 크기와 right 배열의 크기가 같은경우
**크기의 원칙**을 어기면 안됩니다.
두가지 방법이 있습니다.
left에 넣어야하는 경우, left에 있는 원소를 빼다가 right에 넣습니다 -> 크기 유지
-넣고자하는 수가 left보다 작을때 입니다.
right에 넣어야하는 경우, 그냥 넣습니다. 
-left가 비었을때와 넣고자하는 수가 left보다 크거나 같을때 입니다.  
right의 값이 곧 중앙값입니다.
left배열의 크기 + 1 이 right 배열의 크기인 경우
right에 넣어야하는 경우, right에 있는 원소를 빼다가 left에 넣습니다 -> 크기유지
left에 넣어야하는 경우, 그냥 넣습니다.
left의 값이 곧 중앙값입니다.
> [수학]통계학 / [힙] 변화하는 중간값

- BOJ/11279.최대 힙/6047198844.cpp
- BOJ/1181.단어 정렬/6047198844.cpp
- BOJ/1427.소트인사이드/6047198844.cpp
- BOJ/1927.최소 힙/6047198844.cpp
단어 정렬&소트인사이드
**1**
출처 : 백준
**2**
input : 문자열
output : 정렬된 문자열들
**3**
풀이 아이디어
기본 정렬 문제입니다.
최대 힙&최소 힙
**1**
출처 : 백준
**2**
input : 명령
output : 명령에 해당하는 출력
**3**
풀이 아이디어
기본 힙 구현입니다.
> [정렬]단어 정렬 / [정렬]소트인사이드 / [힙]최대 힙 / [힙]최소 힙

- BOJ/11286.절댓값 힙/6047198844.cpp
- programmers/난이도별/level01.신규_아이디_추천/6047198844.txt
- programmers/난이도별/level02.메뉴_리뉴얼/6047198844.cpp
신규 아이디 추천
**1**
출처 : 프로그래머스
**2**
input : 제약사항
output : 결과값
**3**
풀이 아이디어
조건에 따라 구현합니다.
메뉴 리뉴얼
**1**
출처 : 프로그래머스
**2**
input : 손님이 시킨 메뉴
output : 만든 코스요리
**3**
풀이 아이디어
조건에 따라 구현합니다... 딱히 특정 알고리즘을 쓰지는 않네요.
절댓값 힙
**1**
출처 : 백준
**2**
input : 값
output : 작은 절댓값
**3**
풀이 아이디어
힙을 하나만 쓰라는 규칙은 없죠. 힙을 두개썼습니다. 음수의 경우에는 최대힙. 양수의 경우에는 최소힙을 구현해서 두개의 힙을 하나의 배열처럼 사용합니다. 값이 없는 경우를 필터링하고 절댓값을 비교하여 같을 경우에는 음수를 출력하고 아니면 절대값이 같은 값을 출력합니다.
> [구현]신규 아이디 추천 / [구현]메뉴 리뉴얼 / [힙] 절댓값 힙

- BOJ/17404.RGB거리 2/6047198844.cpp
- BOJ/2252.줄 세우기/6047198844.cpp
- 알고스팟/고대어 사전/6047198844.cpp
고대어 사전
**1**
출처 : 알고스팟
**2**
input : 단어
output : 알파벳들의 순서
**3**
풀이 아이디어
위상정렬 문제였습니다. DFS를 활용하여 풀었습니다. 
줄 세우기
**1**
출처 : 백준
**2**
input : 일부 줄
output : 전체 줄의 순서
**3**
풀이 아이디어
위상정렬 문제
> [DFS]고대어 사전 / [DFS]줄 세우기

- BOJ/11728.배열 합치기/6047198844.cpp
**1**
출처 : 백준
**2**
입력 : 정렬된 두배열
출력 : 정렬된 합쳐진 하나의 배열
**3**
정렬 알고리즘은 O(nlogn)의 시간 복잡도가 걸립니다. 투포인터를 이용해서 O(n)에 구했습니다.
> [투포인터] 배열 합치기

- BOJ/1012.유기농 배추/6047198844.cpp
- BOJ/2798.블랙잭/6047198844.java
**1**
출처 : 백준
**2**
input : 배추심은곳
output : 애벌래의 최소 수
**3**
그래프의 형태를 알아야하는 문제입니다. 그래프의 형태 문제였기 때문에 DFS로 접근하였습니다.
> [DFS]유기농 배추 / [brute-force] 블랙잭

- LeetCode/DFS/Letter Combinations of a Phone Number/6047198844.cpp
- LeetCode/DFS/Number_of_Islands/6047198844.cpp
> [DFS]Letter Comibinations of a Phone Number / [DFS] /Number_of_Islands

- LeetCode/DFS/Recover_Binary_Search_Tree/6047198844.cpp
- LeetCode/DFS/Validate_Binary_Search_Tree/6047198844.cpp
https://velog.io/@6047198844/leetcode-Validate-Binary-Search-Tree
> [DFS]Validate_Binary_Search_Tree / [DFS]Validate_Binary_Search_Tree

- LeetCode/Array/Minimum_Value_to_Get_Positive_Step_by_Step_Sum/6047198844.cpp
**1**
https://velog.io/@6047198844/leetcode-Minimum-Value-to-Get-Positive-Step-by-Step-Sum
**2**
https://velog.io/@6047198844/%EB%B0%B1%EC%A4%80-%EC%98%A4%EC%9D%BC%EB%9F%AC-%ED%9A%8C%EB%A1%9C
> [Array]Minimum_Value_to_Get_Positive_Step_by_Step_Sum / [DFS] 오일러 회로

- LeetCode/DFS/Convert_BST_to_Greater_Tree/6047198844.cpp
- LeetCode/Sort/6047198844.cpp
**1**
https://velog.io/@6047198844/leetcode-Sort-List
follow up 이 어렵네요. 
**2**
https://velog.io/@6047198844/leetcode-Convert-BST-to-Greater-Tree
> [sort]Sort List / [dfs] Convert BST to Greater Tree

- LeetCode/Sliding_Window/Minimum_Window_Substring/6047198844.cpp
**1**
https://velog.io/@6047198844/leetcode-Minimum-Window-Substring
> [leetCode]Minimum_Window_Substring

- BOJ/2580.스도쿠/6047198844.cpp
- LeetCode/Linked_List/Merge Two Sorted Lists/6047198844.cpp
**1**
https://velog.io/@6047198844/leetcode-Merge-Two-Sorted-Lists
**2**
https://velog.io/@6047198844/%EB%B0%B1%EC%A4%80-%EC%8A%A4%EB%8F%84%EC%BF%A0
> [LinkedList]Merge Two Sorted Lists / [Backtracking]스도쿠

- BOJ/1085.직사각형에서 탈출/6047198844.cpp
- BOJ/1541.잃어버린 괄호/6047198844.cpp
- BOJ/2447.별찍기 - 10/6047198844.cpp
- BOJ/3009.네 번째 점/6047198844.cpp
- BOJ/3053.택시 기하학/6047198844.cpp
- BOJ/9020.골드바흐의 추측/6047198844.cpp
- LeetCode/Stack/Backspace-String-Compare/6047198844.cpp
**1**
https://velog.io/@6047198844/leetcode-Backspace-String-Compare
**2**
https://velog.io/@6047198844/%EB%B0%B1%EC%A4%80-%EB%B3%84%EC%B0%8D%EA%B8%B0-10
**3**
https://velog.io/@6047198844/%EB%B0%B1%EC%A4%80-%EA%B3%A8%EB%93%9C%EB%B0%94%ED%9D%90%EC%9D%98-%EC%B6%94%EC%B8%A1
**4**
https://velog.io/@6047198844/%EB%B0%B1%EC%A4%80-%EC%A7%81%EC%82%AC%EA%B0%81%ED%98%95%EC%97%90%EC%84%9C-%ED%83%88%EC%B6%9C
**5**
https://velog.io/@6047198844/%EB%B0%B1%EC%A4%80-%EB%84%A4-%EB%B2%88%EC%A7%B8-%EC%A0%90
> [stack]Backspace String Compare / [divide-and-conquer] 별찍기-10 / [math] 골드바흐의 추측 / [math] 직사각형에서 탈출 / [math] 네 번째 점 / [math] 택시 기하학

- BOJ/5086.배수와 약수/6047198844.cpp
- LeetCode/Tree/Same Tree/6047198844.cpp
**1**
https://velog.io/@6047198844/%EB%B0%B1%EC%A4%80-%EB%B0%B0%EC%88%98%EC%99%80-%EC%95%BD%EC%88%98
**2**
https://velog.io/@6047198844/leetcode-Same-Tree
> [math]행렬 곱셈 / [tree]Same Tree

- LeetCode/Backtracking/N-Queens/6047198844.txt
- LeetCode/DFS/Flatten Binary Tree to Linked List/6047198844.txt
- 알고스팟/단어 제한 끝말잇기/6047198844.cpp
**1**
https://velog.io/@6047198844/leetcode-Flatten-Binary-Tree-to-Linked-List
**2**
https://velog.io/@6047198844/%EC%95%8C%EA%B3%A0%EC%8A%A4%ED%8C%9F-%EB%8B%A8%EC%96%B4-%EC%A0%9C%ED%95%9C-%EB%81%9D%EB%A7%90%EC%9E%87%EA%B8%B0
**3**
https://velog.io/@6047198844/N-Queens
> [tree]Flatten Binary Tree to Linked List / [알고스팟]단어 제한 끝말잇기 / [backtracking] N-Queens

- LeetCode/DFS/Maximum_Depth_of_Binary_Tree/6047198844.java
- LeetCode/DFS/Symmetric_Tree/6047198844.java
- LeetCode/DP/Word_Break_II/6047198844.cpp
**1**
https://velog.io/@6047198844/leetcode-Symmetric-Tree
**2**
https://velog.io/@6047198844/leetcode-Maximum-Depth-of-Binary-Tree
> [leetcode]Symmetric tree & [leetcode]Maximum depth of Binary Tree & [leetcode]Word_Break_II

- BOJ/18870.좌표 압축/6047198844.cpp
- LeetCode/DFS/Maximum_Depth_of_N-ary_Tree/6047198844.java
- LeetCode/DFS/Minimum_Depth_of_Binary_Tree/6047198844.cpp
**1**
https://velog.io/@6047198844/leetcode-Minimum-Depth-of-Binary-Tree
**2**
https://velog.io/@6047198844/leetcode-Maximum-Depth-of-N-ary-Tree
**3**
https://velog.io/@6047198844/%EB%B0%B1%EC%A4%80-%EC%A2%8C%ED%91%9C-%EC%95%95%EC%B6%95
>  [leetcode] Minimum depth of binary tree / [leetcode]Maximum depth of n-ary tree / [백준]좌표 압축

- LeetCode/Math/Powerful_Integers/HyeonJeong.py
x와 y가 주어졌을 때, bound와 작거나 같은 x ** i + y ** j의 결과를 리스트로 반환하는 문제
풀이
x와 y가 1인 경우 / 둘 중 하나의 값만 1인 경우 / 둘 다 1이 아닌 경우로 나눠서 결과를 반환 시킴
while문을 이용해서 i와 j에 의한 값이 bound보다 작은 경우는 값이 결과 리스트에 넣어지게 구성함
* log(bound, x)는 x ** i <= bound를 만족시키는 최대 정수인 i를 반환
> [Leetcode] Powerful Integers

- BOJ/11051.이항 계수 2/6047198844.cpp
- BOJ/2981.검문/6047198844.cpp
- LeetCode/Array/Construct Binary Tree from Inorder and Postorder Traversal/6047198844.cpp
**1**
https://velog.io/@6047198844/%EB%B0%B1%EC%A4%80-%EA%B2%80%EB%AC%B8
> [백준]검문 / [백준]이항 계수2 / [leetcode]Construct Binary Tree from Inorder and Postorder Traversal

- LeetCode/Array/Minimum_Number_of_Days_to_Make_m_Bouquets/6047198844.cpp
- LeetCode/Binary_Search/Find_the_Smallest_Divisor_Given_a_Threshold/6047198844.cpp
- LeetCode/Binary_Search/Koko_Eating_Bananas/6047198844.cpp
[leetcode] Minimum Number of Days to Make m Bouquets
[leetcode] Find the Smallest Divisor Given a Threshold
[leetcode] Koko Eating Bananas
> [leetcode] Minimum Number of Days to Make m Bouquets / [leetcode] Find the Smallest Divisor Given a Threshold / [leetcode] Koko Eating Bananas

- LeetCode/Array/Kth_Missing_Positive_Number/HyeonJeong.py
arr 배열에서 누락된 k번째 정수 반환하는 문제
풀이
: k = 5~0까지 while문이 돌아가면서 arr 배열의 정수를 확인해서 k번째 누락된 정수가 반환하게 구성
> [LeetCode] Kth Missing Positive Number

- LeetCode/Breadth-first_Search/Shortest_Path_in_Binary_Matrix/6047198844.cpp
- LeetCode/Graph/Path_With_Minimum_Effort/6047198844.cpp
- LeetCode/Graph/Path_with_Maximum_Probability/6047198844.cpp
[leetcode]Shortest_Path_in_Binary_Matrix
[leetcode]Path with Maximum Probability
[leetcode]Path With Minimum Effort
> [leetcode]Shortest_Path_in_Binary_Matrix / [leetcode]Path with Maximum Probability / [leetcode]Path With Minimum Effort

- LeetCode/Hash_Table/Two_Sum/6047198844.cpp
- LeetCode/Heap/Network_Delay_Time/6047198844.cpp
> [leetcode]Two Sum / [leetcode]Network Delay Time

- BOJ/10844.쉬운 계단 수/rockmiin.py
DP문제입니다. 오랜만에 푸는데 앞으로 꾸준히 풀도록 하겠습니다 !
> 10844.쉬운 계단 수 #DP

- LeetCode/Array/Minimum_Path_Sum/6047198844.cpp
- LeetCode/Graph/Find_the_City_With_the_Smallest_Number_of_Neighbors_at_a_Threshold_Distance/6047198844.cpp
[leetcode] Find_the_City_With_the_Smallest_Number_of_Neighbors_at_a_Threshold_Distance
[leetcode] Minimum Path Sum
> [leetcode] Find_the_City_With_the_Smallest_Number_of_Neighbors_at_a_Threshold_Distance / [leetcode] Minimum Path Sum

- LeetCode/Math/Palindrome Number/6047198844.cpp
> [leetcode]Palindrome Number

- BOJ/11052.카드 구매하기/rockmiin.py
> 11052. 카드 구매하기 #DP

- LeetCode/String/Longest_Common_Prefix/6047198844.cpp
[leetcode] longest common prefix
> [leetcode] longest common prefix

- BOJ/15652.N과 M (4)/6047198844.cpp
> [백준]N과 M (4)

- LeetCode/Greedy/Maximize_Sum_Of_Array_After_K_Negations/6047198844.cpp
[leetcode]Maximize_Sum_Of_Array_After_K_Negations
> [leetcode]Maximize_Sum_Of_Array_After_K_Negations

- LeetCode/Math/Factorial_Trailing_Zeroes/HyeonJeong.py
n!의 결과에서 후행 0의 개수 구하는 문제
풀이
- math 모듈의 factorial 함수를 이용해서 n! 계산
- 결과를 문자로 리스트로 처리
-  맨 뒤의 인덱스부터 연속된 0의 개수 계산 
+ 팩토리얼(!)은 for문으로 계산하는 것보다 math의 factorial 함수가 훨씬 빠르게 처리할 수 있음
> [LeetCode] Factorial Trailing Zeroes

- BOJ/1157.단어 공부/6047198844.py
- LeetCode/Tree/Increasing_Order_Search_Tree/6047198844.cpp
[boj]단어 공부
[leetcode]Increasing_Order_Search_Tree
> [boj]단어 공부 / [leetcode]Increasing_Order_Search_Tree

- LeetCode/Array/Find_the_Duplicate_Number/6047198844.py
> Find the Duplicate Number

- BOJ/1316.그룹 단어 체커/6047198844.py
- LeetCode/Tree/Find_Bottom_Left_Tree_Value/6047198844.cpp
[leetcode]Find_Bottom_Left_Tree_Value
> [leetcode]Find_Bottom_Left_Tree_Value / [BOJ]그룹 단어 체커

- LeetCode/DP/Stone_Game II/6047198844.cpp
- LeetCode/DP/Stone_Game II/6047198844.py
**1**
https://velog.io/@6047198844/Stone-Game-II
요즘 여러가지 일이 많아서 게을렀네요. 다시 열심히 하겠습니당..
> [leetcode]Stone_Game II

- BOJ/2839.설탕 배달/6047198844.py
> [BOJ]설탕 배달

- programmers/난이도별/level02.최솟값_만들기/HyeonJeong.py
A와 B 배열에서 한 개씩 뽑아 두 수를 곱한 합이 최소가 되는 값을 구하는 문제
풀이
: A를 오름차순, B를 내림차순으로 정리, 같은 인덱스 번호끼리 곱한 결과의 합을 반환
https://programmers.co.kr/learn/courses/30/lessons/12941#
> [Programmers] 최솟값 만들기

- LeetCode/Array/Word Search/6047198844.py
- LeetCode/DP/House_Robber_III/6047198844.py
- LeetCode/Hash_Table/Valid_Sudoku/6047198844.py
- LeetCode/Linked_List/Add_Two_Numbers/6047198844.py
> [leetcode]Valid_Sudoku / [leetcode]Add Two Numbers / [leetcode]Word Search / [leetcode]House Robber III

- LeetCode/Array/Bulb_Switcher_III/HyeonJeong.py
문제
: 1~n까지 번호가 있는 전구에서 주어진 순서에 따라 전구에 불이 들어오고, 왼쪽부터 연속적으로 불이 들어온 경우 파란색이 됩니다. 이 상황에서 전구가 파란색이 되는 경우는 몇 번인지 반환하는 문제입니다.
풀이
1. 연속적으로 불이 들어왔는지 확인을 위해서 켜진 전구를 표시할 check 리스트 생성
2. check 리스트에서 왼쪽부터 불이 켜진 가장 오른쪽 인덱스의 번호까지 연속적으로 불이 들어왔는지 확인
(check에 켜진 전구는 0, 꺼진 전구는 1을 넣어 sum(check[:max_index])에 의해 확인할 수 있게 구성)
3. 시간 단축을 위해서 sum() 계산 전, 가장 오른쪽 인덱스까지 채워질 수 있을 만큼 전구를 켰는지 확인
https://leetcode.com/problems/bulb-switcher-iii/
> [LeetCode] Bulb Switcher III

- LeetCode/Array/Create_Target_Array_in_the_Given_Order/HyeonJeong.py
nums의 값을 target[nums의 인덱스와 같은 위치의 index값]에 넣어서 리스트를 반환하는 문제
풀이
: for문에서 enumerate로 nums의 인덱스 위치를 변수 i로 받아서 처리
target = target[:n] + [nums[i]] + target[n:]
> [LeetCode] Create Target Array in the Given Order

- LeetCode/Math/Find_Numbers_with_Even_Number_of_Digits/HyeonJeong.py
짝수의 개수 찾는 문제
풀이
- for문과 if문을 한번에 사용
- 짝수인지 확인후 리스트에 담아서 바로 반환
https://leetcode.com/problems/find-numbers-with-even-number-of-digits/
> [Leetcode] Find Numbers with Even Number of Digits

- LeetCode/String/ZigZag_Conversion/Seokbin.java
6. ZigZag Conversion
- 스트링 버퍼를 활용하기.
- 수직으로 내려가는 경우와 대각선으로 올라가는 경우로 각각 나눠서 풀기.
> [LeetCode] ZigZag Conversion

- LeetCode/Graph/Find_Center_of_Star_Graph/sangmandu.py
- LeetCode/Graph/Redundant_Connection/sangmandu.py
- programmers/난이도별/level02.2개_이하로_다른_비트/sangmandu.py
- programmers/난이도별/level02.행렬_테두리_회전하기/sangmandu.py
> [Level02] 2개 이하로 다른 비트, 행렬 테두리 회전하기, [LeetCode] Redundant Connection, Find Center of Star Graph

- programmers/난이도별/level03.다단계_칫솔_판매/sangmandu.py
- programmers/난이도별/level03.불량_사용자/sangmandu.py
> [Level03] 다단계 칫솔 판매, 불량 사용자

- LeetCode/Greedy/Group_the_People_Given_the_Group_Size_They_Belong_To/HyeonJeong.py
주어진 groupSizes에서 groupSizes[i]는 그 사람이 속한 그룹의 크기로, 각 사람마다 주어진 크기의 그룹에 속하도록 만든 리스트을 반환하는 문제
풀이
1. 각 그룹의 크기별로 사람들을 나누기 위해서 최대 그룹의 크기까지 만든 order_s 빈 리스트를 생성
2. for문을 이용해서 order_s[i]에는 i+1 크기의 그룹에 들어가는 사람끼리 묶이게 함
3. for문에서는 그룹의 크기와 사람의 수가 같은 경우는 바로 결과 리스트에 넣고, 그룹의 크기보다 큰 경우는 그룹을 쪼개서 결과 리스트에 넣도록 구성
https://leetcode.com/problems/group-the-people-given-the-group-size-they-belong-to/
> [LeetCode] Group the People Given the Group Size They Belong To

- BOJ/2110 공유기 설치/rockmiin.py
이진탐색으로 구현했습니다. 좌표를 탐색 구간으로 하기에는 10억으로 구간이 너무 넓어 공유기와 공유기 사이의 거리를 탐색 구간으로 구현하는 것이 포인트였던 것 같습니다. 방학이 되었으니 꾸준히 풀도록 노력하겠습니다
> 2110. 공유기 설치

- programmers/난이도별/level03.경주로_건설/sangmandu.py
[경주로 건설](https://programmers.co.kr/learn/courses/30/lessons/67259) 문제입니다.
문제에 오류가 있습니다.
[여기](https://programmers.co.kr/questions/18816)에 어떤 오류인지 자세히 적어놓았습니다.
오류를 해결할 수 있는 풀이로 풀어보고 싶었는데 2시간 정도 고민하다가 포기합니다.
다른 분들은 혹시 해결하실 수 있을까 해서 도움을 요청해요!!
아마 문제 오류를 먼저 보면 제 풀이랑 비슷하게 풀지 모르니,
먼저 풀어보시고 한번 오류까지도 해결할 수 있는 풀이를 고민해보시길 추천해요.
> [Level03] 경주로 건설

- programmers/난이도별/level03.경주로_건설/rockmiin.py
시작 지점을 오른쪽 방향으로 시작할건지, 아래 방향으로 시작할건지에 대하여 두번 BFS를 실행시켜주어 문제를 풀었습니다. q에 좌표(x, y)와 비용(c), 방향(d)를 넣어주어 구현을 했으며 코너가 생길 경우에 600원, 직진 도로인 경우는 100원을 추가해주었으며 방문을 한 적이 없거나 비용이 더 작을시에 cost배열을 갱신해주었습니다.
마지막으로 [n-1, n-1] 좌표에 도달하게 되면 금액을 result에 저장해주었는데 그 중 최소값을 return 해주는 방식으로 구현하였습니다.
> level03. 경주로 건설

- programmers/난이도별/level02.스킬트리/rockmiin.py
- programmers/난이도별/level02.짝지어_제거하기/rockmiin.py
for else문이 있다는 것을 처음 알았네요 break 없이 for문이 완전히 수행된다면 else문이 실행되는 느낌입니다.
> level02. 스킬트리

- BOJ/14888.연산자 끼워넣기/ms9849.cpp
- BOJ/14889. 스타트와 링크/ms9849.cpp
재귀를 이용하여 브루트 포스를 수행하고 모든 케이스들을 일일이 비교하는 방법으로 풀었습니다. 
구현 자체는 간단했지만 아이디어를 떠올리는 것이 조금 어려웠던 것 같습니다.
> [BOJ] 연산자 끼워넣기 / [BOJ] 스타트와 링크

- programmers/난이도별/level01.숫자_문자열과_영단어/sangmandu.py
> [Level01] 숫자 문자열과 영단어

- BOJ/12852.1로 만들기 2/ms9849.cpp
- BOJ/1932.정수 삼각형/ms9849.cpp
오늘은 DP와 관련된 기초 문제를 2개 풀었습니다. 
정수 삼각형은 아이디어를 금방 떠올렸지만
오히려 1로 만들기 문제에서 더 헤맸던 것 같습니다. 
이에 대한 원인은 직관적이지 않은 코드 작성인 것 같습니다. 
이로 인해 문제에서 제시한 "지나간 숫자 경로" 를 저장하는 아이디어를 떠올리기 어려웠던 것 같습니다.
앞으로는 알고리즘 문제 풀이를 하더라도 어느 정도는 코드를 간결하고 직관성 있게 작성하여 확장된 생각을 하기 쉽게 해야 할 것 같습니다.
> [BOJ] 1로 만들기 2 / [BOJ] 정수 삼각형

- programmers/난이도별/level02.거리두기_확인하기/sangmandu.py
> [Level02] 거리두기 확인하기

- BOJ/1764. 듣보잡/ms9849.cpp
제목때문에 풀게 된 문제였는데 여러 아이디어가 떠올라서 생각보다 고민했던 문제입니다.
배열을 정렬한 뒤 2회 등장한 문자열을 듣지도 보지도 못한 잡것으로 취급했습니다.
> [BOJ] 1764. 듣보잡

- BOJ/7569.토마토/ms9849.cpp
풀이는 5분만에 떠올리고 맞기까진 3시간이 걸린 문제였습니다.. 
3차원 배열에 익숙하지 않았던 점, 문제에서 제시한 조건을 잘못 읽어서 배열 접근 순서를 잘못 설정한 점, 방문한 정점을 확인하는  visited배열이 필요없음에도 처음엔 visited배열을 선언한 점, 모든 토마토가 이미 익은 상태로 주어진 데이터에 대한 처리를 하지 않은 점, 변수를 따로 선언해주지 않아 코드가 보기 힘들었던 점 등 여러 실수가 겹쳐 고난의 연속이였던 문제였습니다.
> [BOJ] 7569.토마토

- LeetCode/Math/Rotate_Image/HyeonJeong.py
이미지를 90도 회전시키는 문제
풀이
1. 손으로 작성해보면서 규칙을 찾으려고 함 -> 실패 
2. 타인의 풀이를 이해한 후 다시 코드 작성
- 새로운 matrix가 아닌 주어진 matrix를 이용해야 하므로 copy.deepcopy()를 이용해서 해당하는 값을 가져올 수 있게 함
- 의미있는 변수명을 사용하기 위해서 matrix의 행과 열을 c, r로 받음
- 90도를 회전하면 matrix[i][j]에서 matrix[j][값이 다음 행으로 갈수록 감소]의 규칙을 알게 됨
https://leetcode.com/problems/rotate-image/
> [LeetCode] Rotate Image

- LeetCode/Math/Number_of_Steps_to_Reduce_a_Number_to_Zero/HyeonJeong.py
짝수면 /2, 홀수면 -1를 시행해서 0을 만들때까지의 단계를 반환하는 문제
풀이
for문에서 if문을 이용해서 0이 될 때까지의 단계를 계산함
(else 대신 continue를 이용해서 시간을 줄임)
> [LeetCode] Number of Steps to Reduce a Number to Zero

- programmers/난이도별/level03.외벽점검/sangmandu.py
> [Level03] 외벽 점검

- LeetCode/String/Longest_Palindrome/HyeonJeong.py
주어진 문자열을 이용해서 최대 회문의 길이를 반환하는 문제
풀이
1. 가장 긴 홀수 개수의 알파벳들을 중앙에 배치하고, 짝수 개수의 알파벳들을 양옆에 배치
2. 알파벳의 종류를 리스트로 만들어서 각 개수를 구해서 사용 
-> 실패
3. [추가된 아이디어] 홀수 개수의 알파벳의 개수에서 -1로 짝수 개수의 알파벳처럼 이용할 수 있음
> [LeetCode] Longest Palindrome

- BOJ/1541.잃어버린 괄호/ms9849.cpp
- BOJ/6198.옥상 정원 꾸미기/ms9849.cpp
스스로 풀지 못하고 풀이를 본 문제였지만 monotone stack의 개념에 대해 알 수 있었습니다.
> [BOJ] 6198.옥상 정원 꾸미기

- programmers/난이도별/level02.멀쩡한_사각형/12eon.py
input : w, h (가로에 들어가는 사각형의 개수, 세로에 들어가는 사각형의 개수)
output : result (가로가 w, 세로가 h인 직사각형을 대각선으로 자를 때 사용할 수 있는 정사각형)
예시를 보고 최대공약수를 이용할 것 같다는 생각과 최대공약수가 1인 경우를 나눠야겠다는 생각은 들었지만, 2가지를 어떻게 조합해야할지 몰랐습니다.
타인의 코드를 통해서 규칙을 이해할 수 있었고, 해당 내용은 코드에 주석으로 달아놓았습니다. 
출처 : https://programmers.co.kr/learn/courses/30/lessons/62048
> [Programmers] 멀쩡한 사각형

- BOJ/15686.치킨 배달/6047198844.py
- BOJ/2098.외판원 순회/6047198844.py
- BOJ/2239.스도쿠/6047198844.py
- BOJ/2473.세 용액/6047198844.py
- BOJ/2887.행성 터널/6047198844.py
[백준]스도쿠] /[백준]행성 터널] / [백준]세 용액
> [백준]스도쿠] /[백준]행성 터널] / [백준]세 용액

- README.md
The problem occurred because you wrote the link twice. I fixed it.
#1068
> Fix programmers link in README.md

- LeetCode/Array/Add_Two_Numbers/wongueShin/_test.dart
- LeetCode/Array/Add_Two_Numbers/wongueShin/solution.dart
어제 문제가 저한태 좀 빡세서, 쉬운 문제부터 차근히 올라가고자 합니다!
>  LeetCode/Array/Add_Two_Numbers/wongueShin/solution.dart
