LeetCode/Union_Find/Surrounded_Regions/JeongShin.js
https://leetcode.com/problems/surrounded-regions/
X X X X
X O O X
X X O X
X O X X
이런식으로 X 에 둘러 쌓여 있는 O 들은 X 로 바꿔주는 문제 입니다. 따라서
X X X X
X X X X
X X X X
X O X X
를 반환해야 합니다. 
풀이
```JS
const visited = new Map(); // coords 방문 정보 
const parent = new Map(); // 해당 그룹이 유효한지 판단
```
BFS 알고리즘으로 O 에 해당되는 주변을 방문합니다. 이때 핵심은 1부터 시작하여 각 그룹 별로 숫자를 지정해줍니다. 
BFS 탐색 중 주변에 undefined 인 곳을 방문하게 되면 해당 그룹 정보를 false로 설정 합니다. 
BFS 를 마치면 visited 정보 숫자가 true 일 경우 X 로 바꿔주고 false 일 경우 그대로 O 로 놔둡니다. 
```JS
// visited
Map { '1,1' => 1, '1,2' => 1, '2,2' => 1, '3,1' => 2 } 
// parent
Map { 1 => true, 2 => false }
```
위의 예제의 경우 위와 같은 정보를 가지게 됩니다.
=> [union_find]surrounded regions 

programmers/난이도별/level02/스킬트리/HyeonJeong.py, programmers/난이도별/level02/스킬트리/README.md
문제 설명
skill : "CBD", skill_trees : ["BACDE", "CBADF", "AECB", "BDA"]  -> return 2
선행 스킬 : 어떤 스킬을 배우기 전에 먼저 배워야 하는 스킬
위 순서에 없는 다른 스킬(힐링 등)은 순서에 상관없이 배울 수 있습니다. 
제한 조건
> 스킬은 알파벳 대문자로 표기하며, 모든 문자열은 알파벳 대문자로만 이루어져 있습니다.
> 스킬 순서와 스킬트리는 문자열로 표기합니다.
> 선행 스킬 순서 skill의 길이는 1 이상 26 이하이며, 스킬은 중복해 주어지지 않습니다.
> skill_trees는 길이가 1 이상 20 이하인 배열이고, 원소는 길이가 2 이상 26 이하인 스킬을 나타내는 문자열이고, 스킬이 중복해 주어지지 않습니다.
=> [level02]스킬트리

programmers/난이도별/level02.더 맵게/6047198844.cpp, programmers/난이도별/level02.조이스틱/6047198844.cpp
더 맵게
**1**
출처 : https://programmers.co.kr/learn/courses/30/lessons/42626
**2**
input : 스코빌 지수를 담은 배열
output : 모든 음식의 스코빌 지수를 K 이상으로 만들기 위해 섞어야하는 최소 횟수
**3**
풀이 아이디어
섞은 음식의 스코빌 지수 = 가장 맵지 않은 음식의 스코빌 지수 + (두 번째로 맵지 않은 음식의 스코빌 지수 * 2) 가 이 문제에서 제시한 공식입니다. 처음에는 두개의 음식을 섞고 넣은 뒤 정렬하는식으로 전부 K이상이 될때까지 반복하려하였으나.. scoville의 길이(최대 1,000,000)를 보고 생각을 접었습니다. priority_queue를 이용하면 logn에 삽입을 할수있고 자동으로 정렬까지 해주기 때문에 priority_queue를 이용해야겠다고 생각했습니다.
구현은 어렵지 않습니다. 공식과 priority_queue를 이용합니다. priority_queue의 맨앞과 그 다음 값을 섞은 뒤 값을 계산해서 push합니다. 섞을때마다 answer값을 늘립니다. 섞어야하는 최소횟수를 구하는 것이니까요.
priority_queue의 size가 1이 됬는데도 K값에 도달하지 못했다면 그건 만들수없는겁니다. 따라서 -1을 반환합니다.
조이스틱
**1**
출처 : https://programmers.co.kr/learn/courses/30/lessons/42860
**2**
input : 완성해야 하는 이름
output : 조이스틱을 움직인 최소 횟수
**3**
풀이 아이디어 : 이 문제는 특이 합니다. 보통의 …
=> 프로그래머스 더맵게 & 조이스틱

BOJ/9465.스티커/Munang.py
1. 백준 알고리즘 9465 스티커 입니다.
https://www.acmicpc.net/problem/9465
2. input
- 테스트 케이스
- 스티커의 (세로) 열 개수
- 각 스티커 칸의 점수 (2* 스티커의 열 개수)
3. 풀이 아이디어
intro)
- 반드시 첫 번째(혹은 n번째)는 이래야 한다 ! 라는 명확성이 필요하다고 생각합니다. ( 이걸 아는데 이 문제로만 2주 넘게 걸렸습니다.. )
- 본 문제에서는 반드시 떼어져야만 하는 스티커의 규칙을 알아야 합니다.
- 그리고 이 명확성을 기반으로 일반화를 할 줄 알아야 문제를 풀 수 있다고 생각합니다.
1)
- 이 문제에서의 아이디어는 임의의 스티커를 뗀다고 하면, 그 이전에 반드시 떼어져야 하는 스티커가 무엇인지 생각하는 것 입니다.
- 예를들어, 
다음과 같이 20의 스티커가 떼어졌다고 하면 그 이전에 70 혹은 50이 반드시 떼어졌어야 합니다.
2) 
1)의 생각을 바탕으로 일반항을 세워보면 다음과 같습니다. (dp는 스티커 점수의 리스트이고, memo는 각 리스트 원소의 스티커를 떼었을때 이전까지 떼어졌던 스티커들의 합을 더한 리스트입니다.)
memo[0][k] = max(memo[1][k-1], memo[1][k-2]) + dp[0][k]
memo[1][k] = max(memo[0][k-1], memo[0][k-2]) + dp[1][k]
3) 
basecase로 k==1일때와 k==0일때는 별도로 지정하여 Bottom up방식으로 풀이했습니다.
if(k ==0):
memo[0][k] = dp[0][k]
memo[1][k] = …
=> BOJ 9465. 스티커

LeetCode/Backtracking/Subsets/JeongShin.js, LeetCode/String/Group_Anagrams/JeongShin.js
https://leetcode.com/problems/subsets/ 
```js
nums = [1,2,3]
//  [[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]
```
과 같이 배열이 있을때 가능한 모든 subset 을 구하는 문제 입니다. 
이 문제는 중복을 허용하기 때문에 backtracking 방법으로 풀이가 가능했습니다. 
순열, 조합 등의 문제는 주기적으로 풀어야 잘 안 까먹는거 같습니다 ㅎㅎ ,,, 😅
한 문제를 더 풀이하게 될 줄 모르고 브랜치 생성하지 않고 그냥 pr 을 올려서 어쩔 수 없이 두 문제 pr 이 되었습니다. 
https://leetcode.com/problems/group-anagrams/
```js 
strs = ["eat","tea","tan","ate","nat","bat"] 
// output : [["bat"],["nat","tan"],["ate","eat","tea"]]
```
과 같이 문자가 담긴 배열이 있을때 anagrams 끼리 묶는 문제 입니다. 
anagrams 기준은 같은 문자를 포함하면 anagram 이 됩니다. 
다양한 방법으로 쉽게 풀이 할 수 있지만 최대한 효율성을 고려하여 풀이 해보았습니다. 
sorting 비용이 가장 클거 같아서 sorting 을 사용하지 않고 알파벳 개수만 count 해서 string 으로 join 하여 Map에  같은 anagrams 의 answer 배열에서 위치 (인덱스)를 저장해두어 풀이 하였습니다.
=> [Backtracking] Subsets

programmers/난이도별/level02.뉴스_클러스터링/6047198844.cpp, programmers/난이도별/level02.영어_끝말잇기/6047198844.cpp, programmers/난이도별/level02.예상_대진표/6047198844.cpp, programmers/난이도별/level02.점프와_순간이동/6047198844.cpp
점프와 순간이동
**1**
출처 : 프로그래머스
https://programmers.co.kr/learn/courses/30/lessons/12980
**2**
input : 아이언 슈트 구매자가 이동하려는 거리
output : 건전지 사용량의 최솟값
**3**
풀이 아이디어 
처음에는 dp로 풀려고 했는데 N이 10억이라 모든 경우의 수를 다 집을수 없을 것같더라고요. 너무 어렵게 접근하나 생각해보니. 홀수의 경우만 건전지를 사용하면 될것같더라고요. 어쩌피 순간이동의 경우가 무조건 이득이니까요.
예를 들면 N이 5이면. 5는 일단 홀수니까 건전지 사용합니다. 2로 나눠주면 2가되고 2는 건전지 사용없습니다. 다시 2로 나누면 1이되고. 1은 홀수니까 건전지 사용합니다.
도합 2번의 건전지를 사용합니다. 역으로 계산을 하면 0에서 5로 가는 경우가 됩니다.
**4**
후기
처음에 너무 어렵게 생각했네요
영어 끝말잇기
**1**
출처 : 프로그래머스
https://programmers.co.kr/learn/courses/30/lessons/12981
**2**
input : 끝말잇기단어
output : 틀린 사람의 위치
**3**
풀이 아이디어 
체크해야될것은 두 가지입니다.
1. 자신의 단어 맨뒤와 다음 단어 맨앞이 같은지.
2. 중복된 글자인지.
틀린 단어를 발견하면
번호 : (index%인원수) + 1 / 차례 : (index/인원수) + 1
이렇게 처리되고
틀린 단어가 없으면
{0,0}을 반환합니다.
**4**
후기
구현 문제입니다.
예상 대진표
**1**
출처 : 프로그래머스 …
=> [level02]점프와 순간이동/영어 끝말잇기/예상 대진표/[1차]뉴스 클러스터링

LeetCode/Tree/Path_Sum_III/JeongShin.js
https://leetcode.com/problems/path-sum-iii/
```js
root = [10,5,-3,3,2,null,11,3,-2,null,1], sum = 8
```
다음과 같이 트리 구조에서 아래로 탐색을 하면서 sum 을 만들수 있는 경우의 수를 반환하는 문제 입니다. 
예제의 경우
1. path: 5 -> 3
2. path: 5 -> 2 -> 1
3. path: -3 -> 11 
즉, 3을 반환해야 합니다. 
이 문제의 어려웠던 점은 기존에 지나온 sum 들에 대한 데이터를 보관하면서 문제 풀이를 접근 해야 합니다. 
예를들어, target 이 12라 가정
트리 노드를 탐색 도중
```
Node  <- 여기 node 까지 오는 방법의 수 : 3, sum : 10 
/      \    
Node     Node  <- value : 2 라고 가정하면 
```
오른쪽 자식이 target 12 를 만족하기 때문에 이전 path 까지 오는 방법의 수 3을 모두 고려해줘야 합니다. 
또한 이 문제의 경우 루트부터 지나온 모든 sum 뿐만 아니라 subtree 에 해당 되는 path 까지 답에 포함되기 때문에 
1. 현재 sum의 빈도를 memo
2. sum - target 의 빈도를 answer 에 add (현재 sum을 유지하면서 subtree에 해당 되는 pathSum 의 빈도를 구할 수 있음) -> 이 부분이 가장 어려웠습니다 ㅜㅜ.
3. 모든 자식 노드 탐색
4. 현재 sum --; -> 현재 노드가 탐색을 마쳤기 때문에 해당 sum 은 이제 제외 시켜줘야함
의 방법으로 …
=> [Tree] Path Sum III 풀이

BOJ/10757.큰 수 A+B/6047198844.cpp, BOJ/1504.특정한 최단 경로/6047198844.cpp
**1**
출처 : 백준
**2**
input : 두개의 큰 수
output : 두개의 큰 수를 더한 값
**3**
풀이 아이디어
C++이 저장할수있는 수의 범위를 넘어서 int로 받을수가없습니다.
우선, 두개의 숫자를 string으로 받고, 짧은 길이의 string 앞에 0을 붙이는 식으로 해당 string의 길이를 동일하게 맞춰주었습니다.
그 후 뒤에서 부터 더했습니다. 올림이 있을경우에는, 해당 올림을 저장하고 나머지를 답에 더했습니다.
예를 들면 12345 123의 경우
12349 00123으로 먼저 길이를 맞추어 주었습니다.
뒤에서 부터 더해줍니다.
9+3 은 12입니다. 따라서 1의 올림이 있습니다. 해당 올림을 저장하고 나머지는 답에 붙입니다.
현재 답은 2입니다.
4와 2, 그리고 이전의 올림 1을 더합니다. 7입니다. 이번에는 올림수를 0으로 설정합니다. 나머지는 답에 붙입니다.
현재 답은 72입니다.
같은 방식으로 문자열 끝까지 진행합니다. 마지막에 올림이 있을 경우도 체크해주어야 하네요.
**1**
출처 : 백준
https://www.acmicpc.net/problem/1504
**2**
input : 간선
output : 경로
**3**
풀이 아이디어
일반 다익스트라입니다.
하지만 
1 -> v1 -> v2 -> N의 경우와
1 -> v2 -> v1 -> N의 경우를 따져야합니다.
v1 -> v2  / v2 -> v1 이 경우를 그냥 두 점을 잇는 간선이라고 생각했는데.
**두 점을 잇는 간선이 반드시 최단거리는 아니다 라는 점을** 생각하지 못했네요.
=> [구현]큰 수 A+B / [다익스트라]특정한 최단 경로

BOJ/11444.피보나치 수 6/11444_피보나치 수 6.cpp
**1**
출처 : 백준
https://www.acmicpc.net/problem/11444
**2**
input : N
output : 피보나치수 N
**3**
풀이 아이디어
우선 N이 엄청 큽니다. 일반 피보나치 수열로는 풀수없습니다. 이 문제는 고민하다가 답을 봤습니다. 분할 정복으로 풀어야하는 문제입니다.
기본행렬을
Fn+1 Fn
Fn Fn-1
로 잡고 행렬의 제곱을 통해서 구하면 됩니다. 예를 들어 기본 행렬의 3제곱을 하면. Fn 자리에 있는 값이 F3값이고, 5제곱을 하면 Fn 자리에 있는 값이 F5입니다.
=> [분할정복]피보나치수 6

BOJ/1725.히스토그램/1725_히스토그램.cpp, BOJ/1916.최소비용 구하기/1916_최소비용 구하기.cpp
**1**
출처 : 백준
https://www.acmicpc.net/problem/1725
**2**
input : 막대그래프
output : 가장 큰 직사각형 넒이
**3**
풀이 아이디어
종만북의 울타리 잘라내기와 동일한 문제입니다.
분할정복을 합니다. 3가지로 나누어서 분할정복합니다.
첫번째 경우, 중앙을 기준으로 왼쪽에 해가 위치하는 경우,
두번쨰 경우, 중앙을 기준으로 오른쪽에 해가 위치하는 경우,
세번째 경우, 중앙을 포함하여 해가 위치하는 경우.
base case의 경우는 히스토그램 막대기가 하나인경우입니다. 
stack으로도 풀수있다고하는데 알아봐야겠습니다.
**1**
출처 : 백준
https://www.acmicpc.net/problem/1916
**2**
input : N개의 도시 / M개의 버스
output : 최소거리비용
**3**
풀이 아이디어
한점에서 모든 정점까지의 최단거리를 구하고 도착지의 최단거리를 출력
다익스트라 알고리즘을 이용.
다익스트라는 ElogV의 시간복잡도를 가진다. 100,000 * log 1000 = 백만 이므로 제한시간 0.5초안에 가능.
=> [분할정복]히스토그램 / [다익스트라]최소비용구하기

BOJ/11401.이항계수 3/6047198844.cpp, BOJ/11657.타임머신/6047198844.cpp
이항계수3
**1**
출처 : 백준
https://www.acmicpc.net/problem/11401
**2**
input : 조합
output : 이항계수
**3**
풀이 아이디어
조합 nCr = N! / K! (N-K)! 를 mod 1,000,000,007로 나눈값이 정답이다.
1,000,000,007은 소수.
K!(N-K)! mod 1,000,000,007 할수없다. 0이 나올수있기 때문에. 따라서 페르마의소정리를 사용한다.
K!(N-K)!를 a라고 하면. 페르마의 소정리에 의해서 a^P = a mod P이다.
따라서 a^P-2 = a^-1 mod P이다.
N! / K! (N-K)!는 N! * (K! (N-K)!)^  1,000,000,007-2 와같다
이후 과정은 팩토리얼과 분할정복으로 푼다.
타임머신
**1**
출처 : 백준
https://www.acmicpc.net/problem/11657
**2**
input : 정점과 간선 (음수간선포함)
output : 한정점에서 모든정점까지의 최소거리.
**3**
풀이 아이디어
기본 벨판-포드 알고리즘을 이용해서 풀었다. 음수간선이 존재할때 한정점에서 모든정점의 최소거리를 구할때 사용한다.
따라서 시간복잡도가 O(VE)임에도 사용한다.
=> [분할정복/페르마의소정리/이항계수]이항계수3 , [벨만포드]타임머신

BOJ/14002.가장 긴 증가하는 부분 수열 4/와일드카드.cpp
**1**
출처 : 백준
https://www.acmicpc.net/problem/14002
**2**
input : 수열
output : 가장 긴 증가하는 부분 수열의 길이와 해당 수열
**3**
풀이 아이디어
DP로 풀었습니다. 시간 복잡도는 O(n^2)이 나옵니다. N이 1000이므로. 1초 내에 가능합니다.
길이는 d에 저장됩니다. 길이는 이전 수열요쇼중 자신보다 작으면서 해당 수열요소가 가지고 있는 최대길이 + 1 이 현재 수열 요소의 길이보다 클 경우 갱신됩니다.
v는 원소의 추적을 위해 사용했습니다.
=> [DP] 가장 긴 증가하는 부분 수열 4

programmers/난이도별/level02.메뉴 리뉴얼/rockmiin.py
2021 KAKAO BLIND RECRUITMENT에 나왔던 문제 입니다. 처음에 모든 메뉴를 다 원소로 받아와서 중복을 제거한 뒤 조합을 구성했는데 시간 초과가 났습니다. 그래서 orders를 받을 때마다 조합을 하여 딕셔너리 값을 1씩 추가해주는 방식으로 구현을 했습니다. 시간이 꽤 걸렸네요.
=> [프로그래머스] 메뉴 리뉴얼 

알고스팟/삼각형 위의 최대 경로/6047198844.cpp, 알고스팟/최대 증가 부분 수열/6047198844.cpp
삼각형 위의 최대 경로
**1**
출처 : 알고스팟
**2**
input : 정수 삼각형
output : 최대합
**3**
풀이 아이디어
부분 집합의 최적해가 전체 집합의 최적해가 됩니다. 이를 최적 부분 구조라고 합니다.
이 문제는 최적 부분 구조를 생각하기 가장 간단한 문제입니다.
왜냐하면 memo[y][x]가 (x,y)에서 가장 큰 최대합이라고 할때. memo[y][x] = arr[y][x] + max (memo[y+1][x+1], memo[y+1][x]) 입니다. 이때 memo[y+1][x+1], memo[y+1][x]이 arr[y][x]와 관련이 없습니다. arr[y][x]가 무슨값을 가지던. memo[y+1][x+1]는 (x+1,y+1)에서의 부분 집합의 최적해고, memo[y+1][x]는 (x,y+1)에서의 부분 집합의 최적해입니다.  
최대 증가 부분 수열
**1**
출처 : 알고스팟
**2**
input : 수열
output : 최대 증가 부분 수열의 길이
**3**
풀이 아이디어
최적 부분 구조를 이용합니다. 이 역시 부분 집합의 최적해가 전채 집합의 최적해가 됩니다.
3 2 1 7 5 4 2 6 이라는 수열이 존재한다고 할때. memo[i]를 i에서의 최대 증가 부분 수열의 길이라고 합시다.
memo[i]는 max(memo[index[i]보다 큰 index[i+1,i+2...i+N-1]값])
이때 memo[i]의 index[i]가 memo[index[i]보다 큰 index[i+1,i+2...i+N-1]값에 영향을 주지 않습니다.
직관적으로 부분집합의 해로. 전채 집합의 최적해를 …
=> [DP]삼각형 위의 최대 경로 / [DP] 최대 증가 부분 수열

LeetCode/Array/Find_Pivot_Index/HyeonJeong.java
배열에서 왼쪽과 오른쪽의 모든 숫자의 합이 같은 인덱스를 구하는 문제
풀이
1. 배열의 가장자리도 구하려는 인덱스가 될 수 있으므로 더해질 인덱스가 없는 경우에는 0을 가질 수 있도록 변수 선언
2. 기준이 될 인덱스는 제외시키고, 왼쪽과 오른쪽의 값이 구분되어 합이 누적될 수 있게 함
https://leetcode.com/problems/find-pivot-index/
=> [LeetCode] Find Pivot Index

알고스팟/삼각형 위의 최대 경로수 세기/6047198844.cpp, 알고스팟/타일링 방법의 수 세기/6047198844.cpp
**1**
출처 : 알고스팟
**2**
input : 타일 수
output : 만들수있는 타일링 방법의 수
**3**
풀이 아이디어
DP를 사용해서 풀었습니다.
2X2 타일의 가로길이를 n이라고 하면 n=1일때 1이 나오고. n==2일때는 2가 나옵니다.
나머지는 dp(n) = dp(n-1) + dp(n-2)로 처리가 되고요. 풀었던 문제였습니다.
**1**
출처 : 알고스팟
**2**
input : 경로
output : 최대 경로 개수 세기
**3**
풀이 아이디어
DP가 두번 이루어 집니다.
먼저 각 경로에서의 최대 값을 구합니다.
아래의 경우는
9
5 7
1 3 2
3 5 5 6
아래의 경우가 됩니다.
24
13 15
6 8 8
3 5 5 6
여기 까지는 저번에 풀이했었던 내용입니다.
여기서 최대 경로 개수를 세야합니다.
우선 맨 아래의 경우에는 무조건 경로 개수가 1입니다.
현재 경로의 수는 세가지 경우의 수의 합입니다.
left를 y+1, x의 최대 값, right 를 y+1, x+1의 최대값이라고 할때
left == right 인경우
결과는 양쪽 경로의 합입니다.
left < right 인경우
결과는 오른쪽 경로의 합입니다.
left > right 인경우
결과는 왼쪽 경로의 합입니다.
=> [알고스팟] 타일링 방법의 수 세기 / [알고스팟] 삼각형 위의 최대 경로수 세기

BOJ/2565.전깃줄/6047198844.cpp, 알고스팟/두니발 박사의 탈옥/6047198844.cpp
두니발 박사의 탈옥
**1**
출처 : 알고스팟
**2**
input : 감옥의 위치 , 경로, 지정동네
output: 지정 동네에 두니발 박사가 있을 확률
**3**
풀이 아이디어
드디어 종만북8장 문제를 꾸역꾸역 다풀엇네요. 하지만 완벽히 소화하려면 시간이 더 필요할것같습니다. 확실히 어려운 책인것같습니다. 숨겨진 의미가 많아서 읽을수록 배우는게 있습니다. 정리한 내용들은 스터디 저장소에 있습니다.
여튼 이 문제에 DP를 사용할수있었던 이유는
문제를 분할했을때 중복되는 문제가 존재하고 최적 부분 구조가 성립하기 때문이였는데요.
현재 동네에서 두니발 박사가 있을 확률은 이전동네와 관련이 없기때문에 가능했습니다. 따라서 그냥 현 위치에서 한 지점까지 갈확률에 그 지점에서 남은 기간동안 두니발 박사를 잡을 확률을 곱한것들의 모든 합이 정답이였네요.
전깃줄
**1**
출처 : 백준
**2**
input : 전깃줄
output : 끊어야하는 전깃줄의 최소수
**3**
풀이 아이디어
제일 긴 부분증가수열의 길이가 전깃줄을 가장 안끊어먹는(?) 방법입니다.
총길이 - 긴 부분증가수열의 길이하면 끊어야하는 전기줄의 개수를 얻게됩니다.
=> [DP]두니발 박사의 탈옥 / [DP]전깃줄

알고스팟/울타리 잘라내기 2/6047198844.cpp
**1**
출처 : 알고스팟
**2**
input : 판자 높이
output : 판자로 만들수있는 최대 크기의 사각형
**3**
풀이 아이디어
이전에 분할과 정복으로 풀었던 문제인데요 그때도 접근이 처음이라 어려웠습니다.
이번에는 스위핑 알고리즘과 스택을 이용해서 풀었습니다. 스위핑 알고리즘은 아직 종만북에서 공부를 안한 단계라 확실하게는 모릅니다. 이름만 들으면 하나씩 처리할때 조건에 맞으면 쓸어가서 그런가하기도 하고 여튼 이 방법이 스위핑 알고리즘이라고 합니다. 
모든 판자에 있어서 i번 판자의 최대 사각형을 구하는 것을 목표로 합니다. 현재 판자의 최대 사각형이란 현재 판자를 항상 포함해서 만들수있는 최대 사각형이라는 뜻입니다. 그렇다는것은 left와 right가 현재 판자의 최대 사각형 밖에 있는 사각형중 가장 가까운 사각형. 즉 , 경계라고 쳤을때 현재 판자보다 낮은 판자가 경계가 됩니다. 이것을 하나하나 해서 너비를 구하고 높이를 곱해서 넒이를 구하는 방식으로 구하면 O(n^2)이 나오고 이것은 분할 정복보다 비효율적입니다.
이걸 스택을 이용해서 O(N) 시간에 구현할수있습니다.
우선 스택에 길이가 0이고 인덱스 번호가 -1인 판자가 있다고 가정합니다. 이 상황은 스택이 empty일때를 의미합니다.
스택에 들어가는것은 left값은 정해졌는데 right값이 정해지지 않은 판자입니다.
right값은 언제 정해질까요? 바로 스택의 top값보다 현재 판자가 같거나 작을때 정해집니다.
스택의 top보다 현재 판자가 크다는것은 스택의 top의 right가 정해지지 않았다는 뜻입니다. 자신보다 현재 판자가 …
=> [DP]울타리 잘라내기 2

BOJ/1018.체스판 다시 칠하기/6047198844.cpp, BOJ/11055.가장 큰 증가 부분 수열/6047198844.cpp, 알고스팟/트리 순회 순서 변경/6047198844.cpp
체스판 다시 칠하기
**1**
출처 : 백준
**2**
input : 체스판
output : 잘못된 체스판의 칸의 개수
**3**
풀이 아이디어
브루트 포스를 쓰게 된 이유는
N과 M이 최대 50을 가질수있고 N과 M을 다 돈다고 가정해도 2500개의 채스판을 보게됩니다.
한 체스판은 64개의 칸으로 이루어져있습니다. 한 체스판을 두가지 경우로 보게됩니다 (WB 인 경우와 BW인 경우)
2500 * 64 * 2 해도 1억이 안나옵니다.
쉬운문제인데 시작하는 칸에 맞추어 정사각형 개수를 세었더니 틀렸었네요. 오래전에 못풀었던 문제인데 쉽게 풀었습니다.
트리 순회 순서 변경
**1**
출처 : 알고스팟
**2**
input : 전위순회 , 중위순회
output : 후위순회 출력값
**3**
풀이 아이디어
자료구조 시간에 배운 내용인데 손으로만 풀어봤습니다. 코딩으로 해본적은 처음입니다.
트리의 재귀적 성질을 이용합니다.
트리는 root와 subtree로 나눌수있습니다. 그리고 그것은 재귀적입니다. subtree에도 root가 존재하기 때문입니다.
root의 좌측 subtree 후위출력.
root의 우측 subtree 후위출력.
root 출력을 하게 되면 최종적으로 후위출력을 할수있다는것을 할수있습니다.
=> [brute-force]체스판 다시 칠하기 / [tree]트리 순회 순서 변경 / [DP] 가장 큰 증가 부분 수열

BOJ/16234.인구 이동/6047198844.cpp, BOJ/2231.분해합/6047198844.cpp
인구이동
**1**
출처 : 백준
**2**
input : 인구수
output : 인구 이동수
**3**
풀이 아이디어
조금 복잡한 BFS같네요.
한번 순회할때마다 인구이동이 가능한 그룹을 찾아서 해당 그룹을 바로 바꿔줍니다. **중요한것은 바꾼 그룹에 속한 원소들은 한번 순회하는 동안 다시 바뀌어서는 안됩니다.** 즉, 방문처리를 해줌으로써 다시 방문하지 못하도록 합니다.
순회했음에도 불구하고 그룹을 하나도 못찾았을때는 인구이동이 없는것이므로 정답을 반환합니다.
분해합
**1**
출처 : 백준
**2**
Input : N
Output : 최소생성자
**3**
풀이 아이디어 
각 숫자의 합을 N까지 더한다.
1000000 × 7 < 1억
=> [BFS]인구이동 / [완전탐색]분해합

BOJ/10610.30/6047198844.cpp, 알고스팟/삽입 정렬 뒤집기/6047198844.cpp, 알고스팟/팬미팅/6047198844.cpp
30
**1**
출처 : 백준
**2**
input : 수
output : 30의 배수가 되는수 / -1
**3**
scanf("%1d",&n)은 EOF인 경우 -1을 반환합니다. 따라서 ~연산을 할경우 0이됩니다.
삽입 정렬 뒤집기
**1**
출처 : 알고스팟
**2**
input : 왼쪽으로 몇 칸이나 이동했는가.
output : 원래의 수열
**3**
풀이 아이디어
원래의 수열로 만드는 알고리즘은 생각하기 어렵지 않습니다.
1부터 N까지의 수들 중에서 K번째 원소를 찾고 해당원소를 삭제하면 되는 문제이기 때문입니다.
문제는 이것을 저장하는 자료구조를 어떻게 선정할것인지가 문제입니다.
배열로 할경우 삭제에 있어서 O(N),
연결리스트로 할경우 K번째 원소를 찾는데 O(N)이기때문에 N번 삭제/찾는데 있어서 각각 O(N^2)이므로 둘다 적합하지는 않습니다. 
이진 검색트리가 k번째 원소가 무엇인지를 찾고, 삭제하는 작업을 수행하는데 빠릅니다.
set은 k번째 원소를 찾는 기능을 제공하지않습니다. 따라서 트립을 만들어서 사용했습니다. 
팬미팅
**1**
출처 : 알고스팟
**2**
input : 아이돌그룹 / 팬
output : 전체가 포옹한 경우
**3**
풀이 아이디어
카라츠바 곱셈법을 이용합니다. 상당히 까다롭고 시간도 빡빡합니다.
=> [BOJ]30 / [트립]삽입 정렬 뒤집기 / [분할정복] 팬미팅

programmers/난이도별/level03.입국심사/rockmiin.py
input : n(인원수), times(심사위원당 걸리는 시간 list)
output: 심사하는데 걸리는 최소 시간
범위가 매우 크기 때문에 브루트 포스는 못하겠다는 생각이 들었고, 이분 탐색을 적용
시간을 기준으로 이분 탐색을 적용하였고, 그 시간에 최대 몇 명의 인원을 심사할 수 있는지를 기준으로 start, end값을 조정해줌.
초반에 start, end의 초기값을 대략적으로 잡아놓은 다음에 여러 값을 시도해서 정답을 검출했음.
출처 : https://programmers.co.kr/learn/courses/30/lessons/43238
=> [Programmers] 입국심사
